import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import ContestPage from "../../src/components/contest/ContestPage";
import { StorageService } from "../../src/util/StorageService";
import { Verdict } from "../../src/types/CF/Submission";
import { formatTimestampDateTime } from "../../src/util/time";
import Theme, { ThemesType } from "../../src/util/Theme";
import { seedContestFixtures } from "../support/contestFixtures";
import { createRouterWrapper, LocationProbe } from "../support/router";

beforeEach(() => { resetFrontendMocks(); localStorage.clear(); seedContestFixtures(); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

function setup(query = "") {
  return render(<><ContestPage /><LocationProbe /></>, { wrapper: createRouterWrapper(`/contests?${query}`) });
}

function rowIds() {
  return within(screen.getByRole("table")).getAllByRole("row").slice(1).map((row) =>
    Number(within(row).getAllByRole("link")[0].getAttribute("href")!.split("/").pop()),
  );
}

async function openFilters() {
  // The filter trigger is icon-only; scope the lookup to its toolbar.
  fireEvent.click(screen.getByPlaceholderText("Search by Contest Name or Id").closest("ul")!.querySelector("li:last-child button")!);
  return screen.findByRole("dialog");
}

function checkbox(dialog: HTMLElement, title: string) {
  // Display checkboxes currently lack associated labels; scope by visible title.
  return within(within(dialog).getByTitle(title)).getByRole("checkbox");
}

// Generated by Codex and not thoroughly checked for correctness.
test("searching on a later page resets pagination and clearing restores category results", () => {
  StorageService.saveObject(StorageService.Keys.Contest.Filter, { perPage: 2 });
  StorageService.saveObject(StorageService.Keys.Contest.Page, 1);
  setup();
  expect(rowIds()).toEqual([102, 15000]);
  fireEvent.change(screen.getByPlaceholderText("Search by Contest Name or Id"), { target: { value: " rOuNd 100 " } });
  expect(rowIds()).toEqual([100]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
  fireEvent.change(screen.getByPlaceholderText("Search by Contest Name or Id"), { target: { value: "" } });
  expect(rowIds()).toEqual([100, 101]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("categories support single, multiple, All, and empty selection", () => {
  setup();
  fireEvent.click(screen.getByRole("button", { name: "Div. 3" }));
  expect(rowIds()).toEqual([200]);
  fireEvent.click(screen.getByTitle("Enable Multiselect"));
  fireEvent.click(screen.getByRole("button", { name: "Div. 1" }));
  expect(rowIds()).toEqual([200, 201]);
  fireEvent.click(screen.getByRole("button", { name: "All" }));
  expect(rowIds()).toEqual([100, 101, 102, 15000, 200, 201]);
  fireEvent.click(screen.getByRole("button", { name: "All" }));
  expect(rowIds()).toEqual([]);
  fireEvent.click(screen.getByTitle("Disable Multiselect"));
  expect(rowIds()).toEqual([100, 101, 102, 15000]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("solve-status buttons filter rows and retain acceptance precedence", async () => {
  setup();
  const dialog = await openFilters();
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.ATTEMPTED }));
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.UNSOLVED }));
  expect(rowIds()).toEqual([100, 102]);
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.SOLVED }));
  expect(rowIds()).toEqual([]);
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.ATTEMPTED }));
  expect(rowIds()).toEqual([101]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("excluding practice changes contest and problem statuses together", async () => {
  setup();
  const alpha = screen.getByTitle("Alpha Dynamic,Rating:800");
  expect(alpha.parentElement!.classList.contains(frontend.theme!.bgSuccess)).toBe(true);
  const dialog = await openFilters();
  fireEvent.click(within(dialog).getByRole("button", { name: "PRACTICE" }));
  expect(alpha.parentElement!.classList.contains(frontend.theme!.bgSuccess)).toBe(false);
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.ATTEMPTED }));
  fireEvent.click(within(dialog).getByRole("button", { name: Verdict.UNSOLVED }));
  expect(rowIds()).toEqual([102]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("display toggles affect dates, ratings, rating colors, and names and restore on remount", async () => {
  const first = setup();
  expect(screen.getByRole("link", { name: "CF 100" })).toBeDefined();
  const dialog = await openFilters();
  fireEvent.click(checkbox(dialog, "Show Date?"));
  fireEvent.click(checkbox(dialog, "Show Rating?"));
  fireEvent.click(checkbox(dialog, "Show Color?"));
  fireEvent.click(checkbox(dialog, "Show Short Name?"));
  fireEvent.click(within(dialog).getByRole("button", { name: "Close" }));
  await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull());
  const assertDisplay = () => {
    expect(screen.getByRole("link", { name: "Codeforces Round 100 (Div. 2)" })).toBeDefined();
    expect(screen.getByText(formatTimestampDateTime(frontend.contests[0].startTimeSeconds!))).toBeDefined();
    const problem = screen.getByTitle("Alpha Dynamic,Rating:800");
    expect(problem.textContent).toBe("A. Alpha Dynamic");
    expect(problem.classList.contains("text-dark")).toBe(true);
    expect(problem.classList.contains("rating-gray")).toBe(false);
  };
  assertDisplay();
  first.unmount();
  setup();
  assertDisplay();
});

// Generated by Codex and not thoroughly checked for correctness.
test("next, previous, last, first, and page size controls preserve numbering", () => {
  StorageService.saveObject(StorageService.Keys.Contest.Filter, { perPage: 1 });
  setup();
  fireEvent.click(screen.getByRole("button", { name: ">" }));
  expect(rowIds()).toEqual([101]);
  expect(screen.getByRole("link", { name: "CF 101" }).closest("tr")!.firstElementChild!.textContent).toBe("2");
  fireEvent.click(screen.getByRole("button", { name: "<" }));
  expect(rowIds()).toEqual([100]);
  fireEvent.click(screen.getByRole("button", { name: ">>" }));
  expect(rowIds()).toEqual([15000]);
  fireEvent.click(screen.getByRole("button", { name: "<<" }));
  fireEvent.change(screen.getByRole("combobox", { name: "Per Page" }), { target: { value: "4" } });
  expect(rowIds()).toEqual([100, 101, 102, 15000]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("narrowing category results from a late page resets to a valid page", () => {
  StorageService.saveObject(StorageService.Keys.Contest.Filter, { perPage: 1 });
  StorageService.saveObject(StorageService.Keys.Contest.Page, 3);
  setup();
  fireEvent.click(screen.getByRole("button", { name: "Div. 3" }));
  expect(rowIds()).toEqual([200]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("reroll selects another eligible contest, category changes stay valid, and cancel exits random mode", () => {
  const random = vi.spyOn(Math, "random").mockReturnValue(0);
  setup();
  fireEvent.click(screen.getByTitle("Find Random Contest"));
  expect(rowIds()).toEqual([100]);
  expect((screen.getByRole("combobox", { name: "Per Page" }) as HTMLSelectElement).disabled).toBe(true);
  random.mockReturnValue(0.99);
  fireEvent.click(screen.getByTitle("Find Random Contest"));
  expect(rowIds()).toEqual([15000]);
  fireEvent.click(screen.getByRole("button", { name: "Div. 3" }));
  expect(rowIds()).toEqual([200]);
  expect(new URLSearchParams(screen.getByTestId("location").textContent!.split("?")[1]).get("random")).toBe("true");
  fireEvent.click(screen.getByTitle("Cancel Random"));
  expect(rowIds()).toEqual([200]);
  expect(new URLSearchParams(screen.getByTestId("location").textContent!.split("?")[1]).has("random")).toBe(false);
  expect((screen.getByRole("combobox", { name: "Per Page" }) as HTMLSelectElement).disabled).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty results cannot choose a random row and disable pagination", () => {
  setup("q=no-match");
  fireEvent.click(screen.getByTitle("Find Random Contest"));
  expect(rowIds()).toEqual([]);
  expect(screen.getByText("Showing 0 of 0")).toBeDefined();
  expect(screen.getByText("Page 0 of 0")).toBeDefined();
  expect((screen.getByRole("button", { name: ">" }) as HTMLButtonElement).disabled).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("missing problem metadata renders empty cells without losing contest navigation", () => {
  setup();
  fireEvent.click(screen.getByRole("button", { name: "Div. 1" }));
  expect(rowIds()).toEqual([201]);
  const row = screen.getByRole("link", { name: "CF 201" }).closest("tr")!;
  expect(within(row).getAllByRole("cell")).toHaveLength(4);
  expect(within(row).getAllByRole("link")).toHaveLength(1);
  expect(row.querySelectorAll("td.EMPTY")).toHaveLength(2);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("theme %s problem links and verdict colors agree with accepted/attempted data", (theme) => {
  frontend.theme = new Theme(theme);
  setup();
  expect(screen.getByRole("link", { name: "CF 100" }).getAttribute("href")).toBe("https://codeforces.com/contest/100");
  const solved = screen.getByTitle("Alpha Dynamic,Rating:800");
  expect(solved.getAttribute("href")).toBe("https://codeforces.com/contest/100/problem/A");
  expect(solved.getAttribute("target")).toBe("_blank");
  expect(solved.getAttribute("rel")).toBe("noreferrer");
  expect(solved.parentElement!.classList.contains(frontend.theme!.bgSuccess)).toBe(true);
  expect(screen.getByTitle("Beta Graph,Rating:1200").parentElement!.classList.contains(frontend.theme!.bgDanger)).toBe(true);
  expect(screen.getByTitle("Delta Unrated,Rating:Not Rated").textContent).toContain("N/A");
});

// Generated by Codex and not thoroughly checked for correctness.
test("shared acceptance and three split problems render independent problem links", () => {
  setup();
  fireEvent.click(screen.getByRole("button", { name: "Div. 3" }));
  for (const [index, rating] of [["A1", 1200], ["A2", 1400], ["A3", 1600]] as const) {
    const link = screen.getByTitle(`Split ${index},Rating:${rating}`);
    expect(link.getAttribute("href")).toBe(`https://codeforces.com/contest/200/problem/${index}`);
    expect(link.parentElement!.classList.contains(frontend.theme!.bgSuccess)).toBe(index === "A1");
  }
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problems", "contests"])("contest page waits for %s and then displays the loaded rows", (source) => {
  frontend.loading = source === "problems";
  frontend.contestLoading = source === "contests";
  const view = setup();
  expect(screen.getByLabelText("three-dots-loading")).toBeDefined();
  expect(screen.queryByRole("table")).toBeNull();
  frontend.loading = false;
  frontend.contestLoading = false;
  view.rerender(<><ContestPage /><LocationProbe /></>);
  expect(screen.queryByLabelText("three-dots-loading")).toBeNull();
  expect(rowIds()).toEqual([100, 101, 102, 15000]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problems", "contests"])("contest page reports %s failures and recovers when cleared", (source) => {
  if (source === "problems") frontend.problemError = "Problems unavailable";
  else frontend.contestError = "Contests unavailable";
  const view = setup();
  expect(screen.getByRole("alert").textContent).toContain(source === "problems" ? "Problems unavailable" : "Contests unavailable");
  expect(screen.queryByRole("table")).toBeNull();
  frontend.problemError = undefined;
  frontend.contestError = undefined;
  view.rerender(<><ContestPage /><LocationProbe /></>);
  expect(screen.queryByRole("alert")).toBeNull();
  expect(rowIds()).toEqual([100, 101, 102, 15000]);
});
