import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import useContestPage from "../../src/components/contest/useContestPage";
import { ContestCat } from "../../src/types/CF/Contest";
import { ParticipantType } from "../../src/types/CF/Party";
import { Verdict } from "../../src/types/CF/Submission";
import { StorageService } from "../../src/util/StorageService";
import { seedContestFixtures } from "../support/contestFixtures";
import { createRouterWrapper } from "../support/router";

beforeEach(() => { resetFrontendMocks(); localStorage.clear(); seedContestFixtures(); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

function setup(query = "") {
  return renderHook(useContestPage, { wrapper: createRouterWrapper(`/contests?${query}`) });
}

// Generated by Codex and not thoroughly checked for correctness.
test.each([[" rOuNd 100 ", [100]], ["15000", [15000]], ["no match", []], ["", [100, 101, 102, 15000]]])(
  "search %j matches full names or IDs ignoring case and outer whitespace", (search, expected) => {
    const hook = setup();
    act(() => hook.result.current.updateFilter({ search }));
    expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual(expected);
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("URL search overrides saved search while preserving saved display options", () => {
  StorageService.saveObject(StorageService.Keys.Contest.Filter, { search: "100", showDate: true });
  const hook = setup("q=101&extra=keep");
  expect(hook.result.current.filter).toMatchObject({ search: "101", showDate: true });
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([101]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("single-category mode defaults an empty selection and retains only the first selected category", () => {
  const hook = setup();
  act(() => hook.result.current.setCategories([]));
  expect(hook.result.current.filter.selectedCategories).toEqual([ContestCat.DIV2]);
  act(() => hook.result.current.setCategories([ContestCat.DIV3, ContestCat.DIV2]));
  expect(hook.result.current.filter.selectedCategories).toEqual([ContestCat.DIV3]);
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([200]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("multiselect accepts several or no categories and disabling it retains the first", () => {
  const hook = setup();
  act(() => hook.result.current.setUpdatedCanSelectMultipleCategories(true));
  act(() => hook.result.current.setCategories([ContestCat.DIV3, ContestCat.DIV1]));
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([200, 201]);
  act(() => hook.result.current.setUpdatedCanSelectMultipleCategories(false));
  expect(hook.result.current.filter.selectedCategories).toEqual([ContestCat.DIV3]);
  act(() => hook.result.current.setUpdatedCanSelectMultipleCategories(true));
  act(() => hook.result.current.setCategories([]));
  expect(hook.result.current.contestList.contests).toEqual([]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [[Verdict.SOLVED], [100, 102]], [[Verdict.ATTEMPTED], [101]], [[Verdict.UNSOLVED], [15000]],
  [[Verdict.SOLVED, Verdict.ATTEMPTED], [100, 101, 102]], [[], []],
])("status selection %j gives any acceptance precedence over failed submissions", (statuses, expected) => {
  const hook = setup();
  act(() => hook.result.current.setSolveStatus(new Set(statuses)));
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual(expected);
  expect(StorageService.getSet(StorageService.Keys.Contest.SolveStatus, [])).toEqual(new Set(statuses));
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [ParticipantType.PRACTICE, [100]], [ParticipantType.VIRTUAL, [102]], [ParticipantType.CONTESTANT, []],
])("only %s submissions contribute to solved contest membership", (participant, expected) => {
  const hook = setup();
  act(() => hook.result.current.setSolveStatus(new Set([Verdict.SOLVED])));
  act(() => hook.result.current.setParticipant(new Set([participant])));
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual(expected);
  expect(StorageService.getSet(StorageService.Keys.Contest.ParticipantType, [])).toEqual(new Set([participant]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("excluding all participant types removes status contributions and deduplicates repeated submissions", () => {
  frontend.submissions.push(frontend.submissions[1]);
  const hook = setup();
  expect([...hook.result.current.submissions.get(100)!.get(Verdict.SOLVED)!]).toEqual(["A"]);
  act(() => hook.result.current.setParticipant(new Set()));
  expect(hook.result.current.submissions.size).toBe(0);
  act(() => hook.result.current.setSolveStatus(new Set([Verdict.UNSOLVED])));
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([100, 101, 102, 15000]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("filter, status, participant and page preferences restore after remount", () => {
  const first = setup();
  act(() => {
    first.result.current.updateFilter({ showDate: true, showRating: false, showColor: false, showShortName: false, perPage: 1 });
    first.result.current.setSolveStatus(new Set([Verdict.SOLVED]));
    first.result.current.setParticipant(new Set([ParticipantType.PRACTICE, ParticipantType.VIRTUAL]));
    first.result.current.setSelected(1);
  });
  first.unmount();
  const second = setup();
  expect(second.result.current.filter).toMatchObject({ showDate: true, showRating: false, showColor: false, showShortName: false, perPage: 1 });
  expect(second.result.current.solveStatus).toEqual(new Set([Verdict.SOLVED]));
  expect(second.result.current.participant).toEqual(new Set([ParticipantType.PRACTICE, ParticipantType.VIRTUAL]));
  expect(second.result.current.currentPageContests.map((contest) => contest.id)).toEqual([102]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("consecutive page slices contain each filtered contest once", () => {
  const hook = setup();
  act(() => hook.result.current.updateFilter({ perPage: 2 }));
  expect(hook.result.current.currentPageContests.map((contest) => contest.id)).toEqual([100, 101]);
  act(() => hook.result.current.setSelected(1));
  expect(hook.result.current.currentPageContests.map((contest) => contest.id)).toEqual([102, 15000]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problems", "contests"])("random mode waits for %s data before choosing a valid contest", (source) => {
  frontend.loading = source === "problems";
  frontend.contestLoading = source === "contests";
  const hook = setup("random=true");
  expect(hook.result.current.isRandomActive).toBe(false);
  frontend.loading = false;
  frontend.contestLoading = false;
  hook.rerender();
  expect(hook.result.current.isRandomActive).toBe(true);
  expect(hook.result.current.currentPageContests).toHaveLength(1);
  expect([100, 101, 102, 15000]).toContain(hook.result.current.currentPageContests[0].id);
});

// Generated by Codex and not thoroughly checked for correctness.
test("random selection follows category changes and remains safe for empty results", () => {
  vi.spyOn(Math, "random").mockReturnValue(0);
  const hook = setup("random=true");
  expect(hook.result.current.currentPageContests[0].id).toBe(100);
  act(() => hook.result.current.setCategories([ContestCat.DIV3]));
  expect(hook.result.current.currentPageContests.map((contest) => contest.id)).toEqual([200]);
  act(() => hook.result.current.updateFilter({ search: "no match" }));
  expect(hook.result.current.currentPageContests).toEqual([]);
  expect(hook.result.current.isRandomActive).toBe(false);
  act(() => hook.result.current.updateFilter({ search: "" }));
  expect(hook.result.current.isRandomActive).toBe(true);
  act(() => hook.result.current.setRandomContest(undefined));
  expect(hook.result.current.isRandomActive).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("zero-problem contests are excluded and expanded shared acceptance contributes to status", () => {
  const hook = setup();
  act(() => {
    hook.result.current.setUpdatedCanSelectMultipleCategories(true);
    hook.result.current.setCategories(Object.values(ContestCat));
  });
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([100, 101, 102, 15000, 200, 201]);
  act(() => hook.result.current.setSolveStatus(new Set([Verdict.SOLVED])));
  expect(hook.result.current.contestList.contests.map((contest) => contest.id)).toEqual([100, 102, 200]);
});
