import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import App from "../../src/App";
import { StorageService } from "../../src/util/StorageService";
import Theme, { ThemesType } from "../../src/util/Theme";
import { seedProblemFixtures } from "../support/problemFixtures";
import { NavigationProbe, type NavigationState } from "../support/router";

const lazyPage = vi.hoisted(() => ({ pending: undefined as Promise<void> | undefined }));
// Test routing and Suspense in the real App shell; unrelated page content is a boundary.
vi.mock("../../src/hooks/useAppBootstrap", () => ({ default: () => {} }));
vi.mock("../../src/components/home/HomePage", async () => {
  const { createElement } = await import("react");
  return { default: () => createElement("h1", {}, "Home page") };
});
vi.mock("../../src/components/stats/StatPage", async () => {
  const { createElement } = await import("react");
  return { default: () => {
    if (lazyPage.pending) throw lazyPage.pending;
    return createElement("h1", {}, "Stats page");
  } };
});
vi.mock("../../src/components/list/ListPage", async () => {
  const { createElement } = await import("react");
  return { default: () => {
    if (lazyPage.pending) throw lazyPage.pending;
    return createElement("h1", {}, "Lists page");
  } };
});
vi.mock("../../src/components/comment/CommentPage", async () => {
  const { createElement } = await import("react");
  return { default: () => {
    if (lazyPage.pending) throw lazyPage.pending;
    return createElement("h1", {}, "Comments page");
  } };
});

let navigation: NavigationState;
beforeEach(() => {
  resetFrontendMocks();
  localStorage.clear();
  seedProblemFixtures();
  lazyPage.pending = undefined;
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

function setup(entry: string) {
  return render(<MemoryRouter initialEntries={[entry]}>
    <NavigationProbe onChange={(state) => { navigation = state; }} />
    <App />
  </MemoryRouter>);
}

async function assertRoute(path: string) {
  if (path === "/problems" || path === "/problems/random") {
    expect(await screen.findByPlaceholderText("Problem Name or Id")).toBeDefined();
  } else if (path === "/contests") {
    expect(await screen.findByPlaceholderText("Search by Contest Name or Id")).toBeDefined();
  } else {
    const heading = ({ "/": "Home page", "/stats": "Stats page", "/comments": "Comments page", "/lists": "Lists page" })[path];
    expect(await screen.findByRole("heading", { name: heading })).toBeDefined();
  }
}

// Generated by Codex and not thoroughly checked for correctness.
test.each(["/", "/problems", "/problems/random", "/contests", "/stats", "/comments"])(
  "FE-001 direct entry and remount keep %s with a usable menu", async (path) => {
    const entry = path === "/problems/random" ? `${path}?random=true` : path;
    const view = setup(entry);
    await assertRoute(path);
    expect(navigation.pathname).toBe(path);
    expect(screen.getByRole("link", { name: "Problems" })).toBeDefined();
    view.unmount();
    setup(entry);
    await assertRoute(path);
    expect(navigation.pathname).toBe(path);
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("FE-001 the real menu changes App routes without losing the shared shell", async () => {
  setup("/");
  for (const [link, path] of [["Problems", "/problems"], ["Contests", "/contests"], ["Stats", "/stats"], ["Issues", "/comments"], ["logoCFTracker", "/"]]) {
    fireEvent.click(screen.getByRole("link", { name: link }));
    await assertRoute(path);
    expect(navigation.pathname).toBe(path);
  }
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["/stats", "/comments", "/lists"])("FE-003 Suspense displays loading until %s is ready", async (path) => {
  frontend.authenticated = true;
  let resolve!: () => void;
  lazyPage.pending = new Promise<void>((done) => { resolve = done; });
  setup(path);
  expect(await screen.findByText("Loading...")).toBeDefined();
  expect(screen.getByRole("link", { name: "Problems" })).toBeDefined();
  await act(async () => { lazyPage.pending = undefined; resolve(); });
  await assertRoute(path);
  expect(screen.queryByText("Loading...")).toBeNull();
});

async function checkProblemHistory(destination: "Stats" | "Contests", path: string) {
  setup("/problems?useFilterStorage=false&q=Alpha&extra=keep");
  expect(await screen.findByRole("link", { name: "Alpha Dynamic" })).toBeDefined();
  fireEvent.change(screen.getByPlaceholderText("Problem Name or Id"), { target: { value: "Beta" } });
  expect(screen.getByRole("link", { name: "Beta Graph" })).toBeDefined();
  expect(new URLSearchParams(navigation.search).get("extra")).toBe("keep");
  fireEvent.click(screen.getByRole("link", { name: destination }));
  await assertRoute(path);
  await act(async () => navigation.navigate(-1));
  expect(navigation.pathname).toBe("/problems");
  expect(screen.getByRole("link", { name: "Beta Graph" })).toBeDefined();
  expect((screen.getByPlaceholderText("Problem Name or Id") as HTMLInputElement).value).toBe("Beta");
  expect(new URLSearchParams(navigation.search).get("extra")).toBe("keep");
  await act(async () => navigation.navigate(1));
  await assertRoute(path);
}

// Generated by Codex and not thoroughly checked for correctness.
test("FE-004 Back and Forward restore problem search and unrelated parameters through Stats", async () => {
  await checkProblemHistory("Stats", "/stats");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["", "Round"])("FE-004 one Back from Contests restores Problems with saved search %j", async (search) => {
  StorageService.saveObject(StorageService.Keys.Contest.Filter, { search });
  await checkProblemHistory("Contests", "/contests");
  expect((screen.getByPlaceholderText("Search by Contest Name or Id") as HTMLInputElement).value).toBe(search);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-004 contest search edits replace history and preserve unrelated parameters", async () => {
  setup("/problems?useFilterStorage=false&q=Alpha");
  await act(async () => navigation.navigate("/contests?extra=keep"));
  const input = screen.getByPlaceholderText("Search by Contest Name or Id");
  for (const search of ["Round", "101", ""]) {
    fireEvent.change(input, { target: { value: search } });
    const params = new URLSearchParams(navigation.search);
    expect(params.get("extra")).toBe("keep");
    expect(params.get("q")).toBe(search || null);
  }
  await act(async () => navigation.navigate(-1));
  expect(navigation.pathname).toBe("/problems");
  expect(screen.getByRole("link", { name: "Alpha Dynamic" })).toBeDefined();
  await act(async () => navigation.navigate(1));
  expect(navigation.pathname).toBe("/contests");
  expect(new URLSearchParams(navigation.search).get("extra")).toBe("keep");
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-005 the app shell and menu render the selected theme", () => {
  frontend.theme = new Theme(ThemesType.DARK);
  const view = setup("/problems");
  expect(view.container.querySelector('[data-theme="dark"]')).not.toBeNull();
  expect(screen.getByRole("table").classList.contains("table-dark")).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("the real AuthGuard redirects anonymous list access to Home", async () => {
  setup("/lists");
  await assertRoute("/");
  expect(navigation.pathname).toBe("/");
  expect(screen.queryByRole("heading", { name: "Lists page" })).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("authenticated list access renders the list route and menu link", async () => {
  frontend.authenticated = true;
  frontend.backendAvailable = true;
  setup("/lists");
  await assertRoute("/lists");
  expect(screen.getByRole("link", { name: "Lists" })).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-007 unknown routes currently retain the menu and can recover through Problems", async () => {
  vi.spyOn(console, "warn").mockImplementation(() => {});
  setup("/unknown-page");
  expect(screen.queryByRole("heading")).toBeNull();
  expect(screen.queryByRole("table")).toBeNull();
  fireEvent.click(screen.getByRole("link", { name: "Problems" }));
  await assertRoute("/problems");
  expect(navigation.pathname).toBe("/problems");
});
