import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import Menu from "../../src/components/Menu";
import Theme, { ThemesType } from "../../src/util/Theme";
import { createRouterWrapper, LocationProbe } from "../support/router";

beforeEach(() => { resetFrontendMocks(); localStorage.clear(); });
afterEach(cleanup);

function setup() {
  return render(<><Menu /><LocationProbe /></>, { wrapper: createRouterWrapper("/problems") });
}

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  ["logoCFTracker", "/"], ["Issues", "/comments"], ["Stats", "/stats"], ["Problems", "/problems"], ["Contests", "/contests"],
])("the %s menu link navigates to %s", (name, path) => {
  setup();
  fireEvent.click(screen.getByRole("link", { name }));
  expect(screen.getByTestId("location").textContent).toBe(path);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("theme %s offers the opposite theme without changing the route", (theme) => {
  frontend.theme = new Theme(theme);
  setup();
  fireEvent.click(screen.getByTitle("Change Theme"));
  expect(frontend.changeThemeMod).toHaveBeenCalledWith(theme === ThemesType.LIGHT ? ThemesType.DARK : ThemesType.LIGHT);
  expect(screen.getByTestId("location").textContent).toBe("/problems");
});

// Generated by Codex and not thoroughly checked for correctness.
test("information popover identifies the creator and source repository", async () => {
  setup();
  fireEvent.click(screen.getByTitle("Created by Bashem"));
  const creator = await screen.findByRole("link", { name: "bashem" });
  expect(creator.getAttribute("href")).toBe("https://codeforces.com/profile/bashem");
  const popover = creator.closest<HTMLElement>('[role="tooltip"]')!;
  const source = within(popover).getAllByRole("link").find((link) => link.getAttribute("href")?.includes("github.com"));
  expect(source?.getAttribute("href")).toBe("https://github.com/mbashem/cftracker");
  expect(screen.getByTestId("location").textContent).toBe("/problems");
});

// Generated by Codex and not thoroughly checked for correctness.
test("menu submission refresh invokes synchronization without navigation", () => {
  setup();
  fireEvent.click(screen.getByTitle("Refresh Submissions"));
  expect(frontend.syncUserSubmissions.mock.calls).toEqual([[]]);
  expect(screen.getByTestId("location").textContent).toBe("/problems");
});

// Generated by Codex and not thoroughly checked for correctness.
test("menu handle editing submits the entered text and supports clearing", () => {
  frontend.handles = ["tourist", "@Petr"];
  setup();
  expect(screen.getByText("@tourist, @Petr")).toBeDefined();
  fireEvent.click(screen.getByTitle("Click to edit handles"));
  const input = screen.getByRole("textbox", { name: "Handles" });
  fireEvent.change(input, { target: { value: " tourist, Benq " } });
  fireEvent.submit(input.closest("form")!);
  expect(frontend.updateUsers).toHaveBeenCalledWith("tourist, Benq");
  fireEvent.click(screen.getByTitle("Click to edit handles"));
  fireEvent.change(screen.getByRole("textbox", { name: "Handles" }), { target: { value: "" } });
  fireEvent.submit(screen.getByRole("textbox", { name: "Handles" }).closest("form")!);
  expect(frontend.updateUsers).toHaveBeenLastCalledWith("");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [false, false], [false, true], [true, false], [true, true],
])("menu backend=%s authenticated=%s gates list and sign-in actions", (backend, authenticated) => {
  frontend.backendAvailable = backend;
  frontend.authenticated = authenticated;
  setup();
  expect(screen.queryByRole("link", { name: "Lists" }) !== null).toBe(backend && authenticated);
  const signIn = screen.queryByTitle("Sign in with GitHub");
  expect(signIn !== null).toBe(backend && !authenticated);
  if (signIn) expect(signIn.getAttribute("href")).toBe("https://backend.example.test/auth/github/login");
  if (backend && authenticated) {
    // Logout currently shares the refresh title; identify the icon within the navigation.
    const logout = screen.getByRole("navigation").querySelector('svg[data-icon="arrow-right-from-bracket"]')?.closest("a");
    expect(logout).not.toBeUndefined();
    fireEvent.click(logout!);
    expect(frontend.logout).toHaveBeenCalledOnce();
  }
});

// Generated by Codex and not thoroughly checked for correctness.
test("menu collapse toggle opens and closes the navigation", async () => {
  setup();
  const toggle = screen.getByRole("button", { name: "Toggle navigation" });
  expect(toggle.classList.contains("collapsed")).toBe(true);
  fireEvent.click(toggle);
  expect(toggle.classList.contains("collapsed")).toBe(false);
  const collapse = document.getElementById("basic-navbar-nav")!;
  await waitFor(() => expect(collapse.classList.contains("show")).toBe(true));
  fireEvent.click(toggle);
  expect(toggle.classList.contains("collapsed")).toBe(true);
  await waitFor(() => expect(collapse.classList.contains("collapsing")).toBe(false));
  expect(collapse.classList.contains("show")).toBe(false);
});
