import { analytics } from "../support/analyticsMocks";
import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { configureStore } from "@reduxjs/toolkit";
import { Provider } from "react-redux";
import { act, cleanup, renderHook } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import type { PropsWithChildren } from "react";
import useAppBootstrap from "../../src/hooks/useAppBootstrap";
import submissionsReducer, { errorFetchingUserSubmissions, requestUserSubmissions } from "../../src/data/reducers/userSubmissionsSlice";
import Theme, { ThemesType } from "../../src/util/Theme";

vi.mock("../../src/hooks/useCallbackHandler", () => ({ default: () => {} }));

beforeEach(() => {
  resetFrontendMocks();
  localStorage.clear();
  document.body.classList.remove("bg-dark", "bg-light");
  analytics.initialize.mockClear();
  analytics.send.mockClear();
});
afterEach(() => {
  cleanup();
  document.body.classList.remove("bg-dark", "bg-light");
  vi.restoreAllMocks();
});

function setup() {
  const store = configureStore({ reducer: { userSubmissions: submissionsReducer } });
  const wrapper = ({ children }: PropsWithChildren) => (
    <Provider store={store}><MemoryRouter initialEntries={["/problems?q=alpha"]}>{children}</MemoryRouter></Provider>
  );
  return { ...renderHook(useAppBootstrap, { wrapper }), store };
}

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problems", "contests"] as const)("waits for both datasets when %s resolve first", (first) => {
  frontend.loading = true;
  frontend.contestLoading = true;
  frontend.handles = ["tourist"];
  const hook = setup();
  expect(frontend.syncUserSubmissions).not.toHaveBeenCalled();
  if (first === "problems") frontend.loading = false;
  else frontend.contestLoading = false;
  hook.rerender();
  expect(frontend.syncUserSubmissions).not.toHaveBeenCalled();
  frontend.loading = false;
  frontend.contestLoading = false;
  hook.rerender();
  expect(frontend.syncUserSubmissions.mock.calls).toEqual([[false]]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("startup delays synchronization for more than two handles and resynchronizes a changed selection", () => {
  frontend.handles = ["tourist", "Petr", "Benq"];
  const hook = setup();
  expect(frontend.syncUserSubmissions.mock.calls).toEqual([[true]]);
  hook.rerender();
  expect(frontend.syncUserSubmissions.mock.calls).toEqual([[true]]);
  frontend.handles = ["tourist"];
  frontend.userId += 1;
  hook.rerender();
  expect(frontend.syncUserSubmissions.mock.calls).toEqual([[true], [false]]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("API and submission failures produce feedback without reporting empty errors", () => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  const hook = setup();
  expect(frontend.showErrorToast).not.toHaveBeenCalled();
  frontend.problemError = "Problems unavailable";
  frontend.contestError = "Contests unavailable";
  hook.rerender();
  const request = requestUserSubmissions(["tourist"]);
  act(() => {
    hook.store.dispatch(request);
    hook.store.dispatch(errorFetchingUserSubmissions({
      handle: "tourist", requestId: request.payload.requestId, error: "Submissions unavailable",
    }));
  });
  expect(frontend.showErrorToast.mock.calls).toEqual([
    ["Problems unavailable"], ["Contests unavailable"], ["Submissions unavailable"],
  ]);
  frontend.problemError = "";
  frontend.contestError = undefined;
  hook.rerender();
  expect(frontend.showErrorToast).toHaveBeenCalledTimes(3);
});

// Generated by Codex and not thoroughly checked for correctness.
test("theme changes update body background without retaining the opposite theme", () => {
  const hook = setup();
  expect(document.body.classList.contains("bg-light")).toBe(true);
  expect(document.body.classList.contains("bg-dark")).toBe(false);
  frontend.theme = new Theme(ThemesType.DARK);
  hook.rerender();
  expect(document.body.classList.contains("bg-dark")).toBe(true);
  expect(document.body.classList.contains("bg-light")).toBe(false);
  frontend.theme = new Theme(ThemesType.LIGHT);
  hook.rerender();
  expect(document.body.classList.contains("bg-light")).toBe(true);
  expect(document.body.classList.contains("bg-dark")).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("startup tracking sends the current pathname and query title through the analytics boundary", () => {
  setup();
  expect(analytics.send).toHaveBeenCalledWith({ hitType: "pageview", page: "/problems", title: "/problems?q=alpha" });
});
