import { analytics } from "../support/analyticsMocks";
import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import { useNavigate } from "react-router";
import usePageTracking from "../../src/hooks/usePageTracking";
import { createRouterWrapper } from "../support/router";
beforeEach(() => { analytics.initialize.mockReset(); analytics.send.mockReset(); });
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("page tracking records route and query changes but not unrelated rerenders", () => {
  const hook = renderHook(() => { usePageTracking(); return useNavigate(); }, { wrapper: createRouterWrapper("/problems?q=dp") });
  expect(analytics.send).toHaveBeenLastCalledWith({ hitType: "pageview", page: "/problems", title: "/problems?q=dp" });
  hook.rerender(); expect(analytics.send).toHaveBeenCalledTimes(1);
  act(() => { void hook.result.current("/problems?q=graphs"); });
  expect(analytics.send).toHaveBeenLastCalledWith({ hitType: "pageview", page: "/problems", title: "/problems?q=graphs" });
  act(() => { void hook.result.current("/stats"); });
  expect(analytics.send).toHaveBeenLastCalledWith({ hitType: "pageview", page: "/stats", title: "/stats" });
  expect(analytics.send).toHaveBeenCalledTimes(3);
});
