import { cleanup, act, renderHook } from "@testing-library/react";
import { Provider } from "react-redux";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import type { PropsWithChildren } from "react";
import { ThemesType } from "../../src/util/Theme";
import { StorageService } from "../../src/util/StorageService";

beforeEach(() => {
  localStorage.clear();
  sessionStorage.clear();
  vi.spyOn(console, "log").mockImplementation(() => {});
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

async function setup() {
  // Reload the real store to exercise its actual storage bootstrap and subscriber.
  vi.resetModules();
  const { default: store } = await import("../../src/data/store");
  const { default: useTheme } = await import("../../src/data/hooks/useTheme");
  const wrapper = ({ children }: PropsWithChildren) => <Provider store={store}>{children}</Provider>;
  return renderHook(useTheme, { wrapper });
}

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("FE-005 theme %s persists through the real store and restores on reload", async (theme) => {
  const first = await setup();
  act(() => first.result.current.changeThemeMod(theme));
  expect(first.result.current.theme.themeType).toBe(theme);
  expect(StorageService.getObject(StorageService.Keys.StateV2, { appState: { themeMod: 0 } }).appState.themeMod).toBe(theme);
  first.unmount();
  const second = await setup();
  expect(second.result.current.theme.themeType).toBe(theme);
});
