import { expect, test } from "vitest";
import { Compared } from "../../src/util/Comparator";
import lowerBound from "../../src/util/lowerBound";
import upperBound from "../../src/util/upperBound";
import { ProblemLite } from "../../src/types/CF/Problem";

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  { values: [], target: 10, lower: 0, upper: 0 },
  { values: [10], target: 5, lower: 0, upper: 0 },
  { values: [10], target: 10, lower: 0, upper: 1 },
  { values: [10], target: 20, lower: 1, upper: 1 },
  { values: [10, 20, 20, 40], target: 5, lower: 0, upper: 0 },
  { values: [10, 20, 20, 40], target: 20, lower: 1, upper: 3 },
  { values: [10, 20, 20, 40], target: 30, lower: 3, upper: 3 },
  { values: [10, 20, 20, 40], target: 40, lower: 3, upper: 4 },
  { values: [10, 20, 20, 40], target: 50, lower: 4, upper: 4 },
])("bounds locate $target in $values including duplicates and empty ranges", ({ values, target, lower, upper }) => {
  const problems = values.map(value => new ProblemLite(value, "A"));
  const before = [...problems];
  expect(lowerBound(problems, new ProblemLite(target, "A"))).toBe(lower);
  expect(upperBound(problems, new ProblemLite(target, "A"))).toBe(upper);
  expect(problems).toEqual(before);
});

// Generated by Codex and not thoroughly checked for correctness.
test("lower bound accepts callbacks returning Compared enum values", () => {
  expect(lowerBound([10, 20, 20, 40], 30, (first, second) => first < second ? Compared.LESS : first > second ? Compared.GREATER : Compared.EQUAL)).toBe(3);
});

// Generated by Codex and not thoroughly checked for correctness.
test("upper bound uses Compared enum results to skip all equal entries", () => {
  let calls = 0;
  const create = (value: number) => ({ value, compareTo: (other: { value: number }) => {
    if (++calls > 20) throw new Error("Search failed to terminate");
    if (value < other.value) return Compared.LESS;
    if (value > other.value) return Compared.GREATER;
    return Compared.EQUAL;
  } });
  expect(upperBound([10, 20, 20, 40].map(create), create(20))).toBe(3);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([2, -2, NaN])("upper bound rejects invalid comparator result %s instead of looping", result => {
  const value = { compareTo: () => result };
  expect(() => upperBound([value], value)).toThrow(new RangeError("Comparator must return a Compared enum value"));
});
