import { setupBackendMock } from "../support/backendMocks";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
import { StorageService } from "../../src/util/StorageService";
let backend: ReturnType<typeof setupBackendMock>;
let fetchCodeforcesApi: typeof import("../../src/util/codeforcesApi").fetchCodeforcesApi;
const url = "https://codeforces.com/api/user.status?handle=tourist";
beforeEach(async () => {
  localStorage.clear(); vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 9, 4, 12));
  backend = setupBackendMock(); vi.resetModules(); vi.stubEnv("VITE_DEBUG_MODE", "true");
  ({ fetchCodeforcesApi } = await import("../../src/util/codeforcesApi"));
  vi.spyOn(console, "log").mockImplementation(() => {});
});
afterEach(() => { backend.dispose(); vi.restoreAllMocks(); vi.unstubAllEnvs(); vi.useRealTimers(); localStorage.clear(); });

// Generated by Codex and not thoroughly checked for correctness.
test("debug API calls reuse cached responses until the exact thirty-minute expiry", async () => {
  backend.respond({ status: "OK", result: [1] });
  expect(await fetchCodeforcesApi(url)).toEqual({ status: "OK", result: [1] });
  await fetchCodeforcesApi(url); expect(backend.fetchMock).toHaveBeenCalledTimes(1);
  vi.advanceTimersByTime(30 * 60 * 1000);
  backend.respond({ status: "OK", result: [2] });
  expect(await fetchCodeforcesApi(url)).toEqual({ status: "OK", result: [2] });
  expect(backend.fetchMock).toHaveBeenCalledTimes(2);
});

// Generated by Codex and not thoroughly checked for correctness.
test("concurrent debug calls share one request and failed requests remain retryable", async () => {
  let resolve!: (value: Response) => void;
  backend.fetchMock.mockImplementationOnce(() => new Promise(done => { resolve = done; }));
  const first = fetchCodeforcesApi(url), second = fetchCodeforcesApi(url);
  expect(backend.fetchMock).toHaveBeenCalledTimes(1);
  resolve(Response.json({ status: "OK", result: [] }));
  expect(await first).toEqual(await second);
  backend.fetchMock.mockRejectedValueOnce(new Error("Offline"));
  await expect(fetchCodeforcesApi(url + "&page=2")).rejects.toThrow("Offline");
  backend.respond({ status: "OK", result: [] });
  await expect(fetchCodeforcesApi(url + "&page=2")).resolves.toEqual({ status: "OK", result: [] });
});

// Generated by Codex and not thoroughly checked for correctness.
test("malformed cache JSON falls back to a request and stale unrelated entries are pruned", async () => {
  localStorage.setItem(StorageService.Keys.Codeforces.DebugApiCache, "{invalid");
  backend.respond({ status: "OK", result: [] }); await fetchCodeforcesApi(url);
  StorageService.saveMap(StorageService.Keys.Codeforces.DebugApiCache, new Map([["old", { cachedAt: 0, response: [] }]]));
  await fetchCodeforcesApi(url + "&page=2");
  expect(StorageService.getMap(StorageService.Keys.Codeforces.DebugApiCache, []).has("old")).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("ordinary mode does not cache requests and HTTP failures reject even with JSON bodies", async () => {
  vi.resetModules(); vi.stubEnv("VITE_DEBUG_MODE", "false");
  ({ fetchCodeforcesApi } = await import("../../src/util/codeforcesApi"));
  backend.respond({ status: "OK", result: [] }); await fetchCodeforcesApi(url); await fetchCodeforcesApi(url);
  expect(backend.fetchMock).toHaveBeenCalledTimes(2);
  backend.respond({ status: "FAILED" }, 503);
  await expect(fetchCodeforcesApi(url)).rejects.toThrow("503");
});
