import { expect, test } from "vitest";
import Problem from "../../src/types/CF/Problem";
import Submission, { Verdict, getSimpleVerdict, SimpleVerdict } from "../../src/types/CF/Submission";
import { createSubmission } from "../support/submissionFixtures";
import { sortSubmissions } from "../../src/util/sortMethods";

// Generated by Codex and not thoroughly checked for correctness.
test("problem cloning preserves metadata and creates independent tag arrays", () => {
  const problem = new Problem(15000, "A2", "Alpha", "PROGRAMMING", 1200, ["dp"], 42);
  problem.points = 500; problem.problemsetName = "set";
  const copy = problem.clone();
  expect(copy.solvedCount).toBe(42); expect(copy.points).toBe(500); expect(copy.problemsetName).toBe("set");
  copy.setTags(["math"]); expect(problem.getTags()).toEqual(["dp"]);
  const tags = problem.getTags(); tags.push("graphs"); expect(problem.tags).toEqual(["dp"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("submission clones preserve verdict, dates and independent author/problem metadata", () => {
  const original = createSubmission(1, new Problem(100, "A", "Alpha", "PROGRAMMING", 800, ["dp"], 42), Verdict.OK, 100);
  const copy = new Submission(original);
  copy.author.members[0].handle = "other"; copy.problem.tags.push("math");
  expect(original.author.members[0].handle).toBe("tourist"); expect(original.problem.tags).toEqual(["dp"]);
  expect(copy.submissionDate).toEqual(new Date(100000)); expect(copy.simpleVerdict).toBe(SimpleVerdict.SOLVED);
  expect(getSimpleVerdict()).toBe(SimpleVerdict.UNSOLVED); expect(getSimpleVerdict(Verdict.WRONG_ANSWER)).toBe(SimpleVerdict.ATTEMPTED);
});

// Generated by Codex and not thoroughly checked for correctness.
test("submission sorting prioritizes accepted results and treats failed ties as equal", () => {
  const problem = new Problem(100, "A", "Alpha", "PROGRAMMING", 800, []);
  const failed = createSubmission(1, problem, Verdict.WRONG_ANSWER, 100);
  const accepted = createSubmission(2, problem, Verdict.OK, 200);
  expect(sortSubmissions(failed, failed)).toBe(0);
  expect(sortSubmissions(accepted, failed)).toBeLessThan(0);
  expect(sortSubmissions(failed, accepted)).toBeGreaterThan(0);
});
