import { expect, test } from "vitest";
import Problem, { ProblemLite } from "../../src/types/CF/Problem";
import { sortByContestId, sortById, sortByCompare, sortByRating, sortBySolveCount, sortSubmissions } from "../../src/util/sortMethods";

import { Verdict } from "../../src/types/CF/Submission";
import { createSubmission } from "../support/submissionFixtures";

// Generated by Codex and not thoroughly checked for correctness.
test("canonical problem IDs retain multi-character indexes and high contest IDs", () => {
  expect(new ProblemLite(15000, "A2").id).toBe("15000A2");
  expect(new ProblemLite(100, "B").equal(new ProblemLite(100, "B"))).toBe(true);
  expect(new ProblemLite(100, "B").equal(new ProblemLite(101, "B"))).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("problem comparisons order by numeric contest ID then index", () => {
  const problems = [new ProblemLite(100, "B"), new ProblemLite(9, "A"), new ProblemLite(100, "A")];
  expect([...problems].sort(sortByCompare).map(problem => problem.id)).toEqual(["9A", "100A", "100B"]);
  expect([...problems].sort(sortByContestId).map(problem => problem.id)).toEqual(["9A", "100A", "100B"]);
  expect([...problems].sort(sortById).map(problem => problem.id)).toEqual(["100A", "100B", "9A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([sortByContestId, sortById, sortByCompare])("problem comparator %s reports equal values as zero and reverses ordering", compare => {
  const first = new ProblemLite(100, "A");
  const equal = new ProblemLite(100, "A");
  const later = new ProblemLite(100, "B");
  expect(compare(first, equal)).toBe(0);
  expect(compare(first, later)).toBeLessThan(0);
  expect(compare(later, first)).toBeGreaterThan(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [undefined, undefined, 0], [undefined, 1200, -1], [1200, undefined, 1],
  [1200, 1400, -1], [1400, 1200, 1], [1200, 1200, 0],
])("rating sorting compares %s with %s as %s", (first, second, expected) => {
  expect(sortByRating(
    new Problem(100, "A", "First", "PROGRAMMING", first, []),
    new Problem(100, "B", "Second", "PROGRAMMING", second, []),
  )).toBe(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([[0, 10, -1], [10, 0, 1], [10, 10, 0]])("solve-count sorting compares %s with %s as %s", (first, second, expected) => {
  expect(sortBySolveCount(
    new Problem(100, "A", "First", "PROGRAMMING", undefined, [], first),
    new Problem(100, "B", "Second", "PROGRAMMING", undefined, [], second),
  )).toBe(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [100, "A", Verdict.OK, 100, "A", Verdict.OK, 0],
  [100, "A", Verdict.OK, 100, "A", Verdict.WRONG_ANSWER, -1],
  [100, "A", Verdict.WRONG_ANSWER, 100, "A", Verdict.OK, 1],
  [100, "A", Verdict.WRONG_ANSWER, 100, "A", Verdict.TIME_LIMIT_EXCEEDED, 0],
  [100, "A", Verdict.OK, 100, "B", Verdict.OK, -1],
  [100, "B", Verdict.OK, 100, "A", Verdict.OK, 1],
  [101, "A", Verdict.OK, 100, "A", Verdict.OK, 1],
  [100, "A", Verdict.OK, 101, "A", Verdict.OK, -1],
])("submission sorting compares %s%s (%s) with %s%s (%s) as %s", (firstContest, firstIndex, firstVerdict, secondContest, secondIndex, secondVerdict, expected) => {
  const first = new Problem(firstContest, firstIndex, "First", "PROGRAMMING", undefined, []);
  const second = new Problem(secondContest, secondIndex, "Second", "PROGRAMMING", undefined, []);
  expect(sortSubmissions(createSubmission(1, first, firstVerdict, 0), createSubmission(2, second, secondVerdict, 0))).toBe(expected);
});
