// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { StorageService } from "../../src/util/StorageService";

const keys = StorageService.Keys.Problem;

beforeEach(() => localStorage.clear());
afterEach(() => vi.restoreAllMocks());

test("JWT storage preserves the raw token and reports successful writes and removal", () => {
  expect(StorageService.getJWTToken()).toBeNull();
  expect(StorageService.setJWTToken("test-token")).toBe(true);
  expect(localStorage.getItem(StorageService.Keys.JwtToken)).toBe("test-token");
  expect(StorageService.getJWTToken()).toBe("test-token");
  expect(StorageService.removeJWTToken()).toBe(true);
  expect(StorageService.getJWTToken()).toBeNull();
});

test.each(["getItem", "setItem", "removeItem"] as const)("JWT storage handles %s failures", (operation) => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  vi.spyOn(Storage.prototype, operation).mockImplementation(() => {
    throw new DOMException("Storage unavailable", "SecurityError");
  });
  if (operation === "getItem") expect(StorageService.getJWTToken()).toBeNull();
  if (operation === "setItem") expect(StorageService.setJWTToken("test-token")).toBe(false);
  if (operation === "removeItem") expect(StorageService.removeJWTToken()).toBe(false);
});

test("migrates the four legacy problem entries into filter V2 and removes the old entries", () => {
  const filter = { minRating: 1200, showUnrated: false, minContestDate: "2026-01-01", search: "dp" };
  StorageService.saveObject(keys.Filter, filter);
  StorageService.saveObject(keys.Page, 0);
  StorageService.saveSet(keys.Tags, new Set(["dp", "math"]));
  StorageService.saveSet(keys.SolveStatus, new Set(["ATTEMPTED"]));
  const expected = { ...filter, selected: 0, tags: ["dp", "math"], solveStatus: ["ATTEMPTED"] };

  expect(StorageService.getValue(keys.FilterV2, {})).toEqual(expected);
  expect(JSON.parse(localStorage.getItem(keys.FilterV2)!)).toEqual(expected);
  expect(localStorage.getItem(keys.Filter)).toBeNull();
  expect(localStorage.getItem(keys.Page)).toBeNull();
  expect(localStorage.getItem(keys.Tags)).toBeNull();
  expect(localStorage.getItem(keys.SolveStatus)).toBeNull();
});

test("existing V2 preferences take priority and are not migrated again", () => {
  StorageService.saveObject(keys.FilterV2, { search: "new" });
  StorageService.saveObject(keys.Filter, { search: "old" });
  const write = vi.spyOn(Storage.prototype, "setItem");
  expect(StorageService.getValue(keys.FilterV2, {})).toEqual({ search: "new" });
  expect(write).not.toHaveBeenCalled();
});

test("migration is not repeated after legacy values change", () => {
  StorageService.saveObject(keys.Filter, { search: "original" });
  StorageService.getValue(keys.FilterV2, {});
  StorageService.saveObject(keys.Filter, { search: "changed" });
  expect(StorageService.getValue(keys.FilterV2, {})).toEqual({ search: "original" });
});

test("partial legacy entries preserve empty arrays and use defaults for missing fields", () => {
  StorageService.saveObject(keys.Tags, []);
  const defaults = { minRating: 0, selected: 0, tags: ["dp"] };
  expect(StorageService.getValue(keys.FilterV2, defaults)).toEqual({ ...defaults, tags: [] });
  expect(JSON.parse(localStorage.getItem(keys.FilterV2)!)).toEqual({ tags: [] });
});

test("missing legacy data does not create a migration entry", () => {
  expect(StorageService.getValue(keys.FilterV2, { selected: 0 })).toEqual({ selected: 0 });
  expect(localStorage.getItem(keys.FilterV2)).toBeNull();
});

test("migration and subsequent reads merge defaults identically without persisting them", () => {
  const defaults = Object.freeze({ perPage: 100, minRating: 1200, showUnrated: true, search: "default" });
  const legacy = { minRating: 0, showUnrated: false, search: "" };
  StorageService.saveObject(keys.Filter, legacy);

  const firstRead = StorageService.getObject(keys.FilterV2, defaults);
  const secondRead = StorageService.getObject(keys.FilterV2, defaults);

  expect(firstRead).toEqual({ perPage: 100, ...legacy });
  expect(secondRead).toEqual(firstRead);
  expect(JSON.parse(localStorage.getItem(keys.FilterV2)!)).toEqual(legacy);
  expect(defaults).toEqual({ perPage: 100, minRating: 1200, showUnrated: true, search: "default" });
});

test.each(["broken JSON", "null", "[]"])("invalid legacy filter %s does not discard other entries", (filter) => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  localStorage.setItem(keys.Filter, filter);
  StorageService.saveObject(keys.Page, 3);
  expect(StorageService.getValue(keys.FilterV2, {})).toEqual({ selected: 3 });
  expect(localStorage.getItem(keys.Filter)).toBeNull();
});

test("failed migration writes preserve legacy data and can be retried", () => {
  StorageService.saveObject(keys.Filter, { search: "saved" });
  vi.spyOn(console, "log").mockImplementation(() => {});
  const write = vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => {
    throw new DOMException("Storage full", "QuotaExceededError");
  });
  expect(StorageService.getValue(keys.FilterV2, {})).toEqual({ search: "saved" });
  expect(localStorage.getItem(keys.FilterV2)).toBeNull();
  expect(localStorage.getItem(keys.Filter)).toBe('{"search":"saved"}');
  write.mockRestore();
  StorageService.getValue(keys.FilterV2, {});
  expect(localStorage.getItem(keys.FilterV2)).toBe('{"search":"saved"}');
  expect(localStorage.getItem(keys.Filter)).toBeNull();
});

test("cleanup failure does not discard the successfully migrated value", () => {
  StorageService.saveObject(keys.Filter, { search: "saved" });
  vi.spyOn(console, "log").mockImplementation(() => {});
  vi.spyOn(Storage.prototype, "removeItem").mockImplementation(() => {
    throw new DOMException("Storage unavailable", "SecurityError");
  });
  expect(StorageService.getValue(keys.FilterV2, {})).toEqual({ search: "saved" });
  expect(localStorage.getItem(keys.FilterV2)).toBe('{"search":"saved"}');
});

// Generated by Codex and not thoroughly checked for correctness.
test("sets and maps round-trip with insertion order and nested values", () => {
  expect(StorageService.saveValue("tags", new Set(["graphs", "dp"]))).toBe(true);
  expect([...StorageService.getValue("tags", new Set<string>())]).toEqual(["graphs", "dp"]);
  const entries = new Map([["page", { value: 0 }], ["rating", { value: 1200 }]]);
  expect(StorageService.saveValue("positions", entries)).toBe(true);
  expect([...StorageService.getValue("positions", new Map<string, { value: number }>())]).toEqual([...entries]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["broken JSON", "{}", "null", "123", '["not a map entry"]'])("collection reads recover from malformed stored value %s", stored => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  localStorage.setItem("collection", stored);
  const defaultMap = new Map([["page", 1]]);
  expect(StorageService.getMap("collection", defaultMap)).toEqual(defaultMap);
  if (!stored.startsWith("[")) expect(StorageService.getSet("collection", ["dp"])).toEqual(new Set(["dp"]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("missing collections return independent defaults and do not mutate caller values", () => {
  const defaultSet = new Set(["dp"]);
  const defaultMap = new Map([["page", 1]]);
  const set = StorageService.getValue("tags", defaultSet);
  const map = StorageService.getValue("map", defaultMap);
  set.add("math"); map.set("page", 2);
  expect(defaultSet).toEqual(new Set(["dp"]));
  expect(defaultMap).toEqual(new Map([["page", 1]]));
  expect(localStorage.length).toBe(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("object reads merge partial preferences without mutating nested defaults", () => {
  const defaults = { page: 1, enabled: true, nested: { rating: 1200 } };
  StorageService.saveObject("preferences", { page: 0, enabled: false });
  expect(StorageService.getObject("preferences", defaults)).toEqual({ ...defaults, page: 0, enabled: false });
  expect(defaults).toEqual({ page: 1, enabled: true, nested: { rating: 1200 } });
});

// Generated by Codex and not thoroughly checked for correctness.
test("saving undefined removes a value while explicit JSON null is preserved", () => {
  StorageService.saveValue("optional", "saved");
  expect(StorageService.saveValue("optional", undefined)).toBe(true);
  expect(localStorage.getItem("optional")).toBeNull();
  expect(StorageService.saveValue("nullable", null)).toBe(true);
  expect(localStorage.getItem("nullable")).toBe("null");
  expect(StorageService.getObject("nullable", "default")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed serialization preserves the previously saved object", () => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  StorageService.saveObject("object", { page: 1 });
  const cyclic: { self?: unknown } = {};
  cyclic.self = cyclic;
  expect(StorageService.saveObject("object", cyclic)).toBe(false);
  expect(StorageService.getObject("object", {})).toEqual({ page: 1 });
});

// Generated by Codex and not thoroughly checked for correctness.
test("blocked reads and writes return fallback values and false results for all collection types", () => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  vi.spyOn(Storage.prototype, "getItem").mockImplementation(() => { throw new DOMException("Blocked", "SecurityError"); });
  vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new DOMException("Full", "QuotaExceededError"); });
  expect(StorageService.getObject("object", { page: 1 })).toEqual({ page: 1 });
  expect(StorageService.getSet("tags", ["dp"])).toEqual(new Set(["dp"]));
  expect(StorageService.getMap("map", [["page", 1]])).toEqual(new Map([["page", 1]]));
  expect(StorageService.saveObject("object", { page: 2 })).toBe(false);
  expect(StorageService.saveSet("tags", new Set(["dp"]))).toBe(false);
  expect(StorageService.saveMap("map", new Map([["page", 1]]))).toBe(false);
});
