import { expect, test } from "vitest";
import Theme, { Color, ThemesType } from "../../src/util/Theme";

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [Color.Gray, "#9e9e9e", "#6c757d"],
  [Color.Green, "#66bb6a", "#2e7d32"],
  [Color.Cyan, "#26c6da", "#006064"],
  [Color.Blue, "#42a5f5", "#1565c0"],
  [Color.Violet, "#ab47bc", "#6a1b9a"],
  [Color.Orange, "#ffa726", "#e65100"],
  [Color.LightRed, "#FFCDD2", "#EF9A9A"],
  [Color.Red, "#ef5350", "#b71c1c"],
  [Color.DeepRed, "#c62828", "#842029"],
  [Color.Yellow, "#fdd835", "#fbc02d"],
  [Color.Purple, "#6a1b9a", "#3e2a63"],
  [Color.Teal, "#00838f", "#0d5a6e"],
  [Color.Pink, "#ad1457", "#6e2142"],
  [Color.LightPink, "#F8BBD0", "#F48FB1"],
  [Color.Indigo, "#283593", "#3e1f79"],
  [Color.Lime, "#827717", "#4c6b10"],
  [Color.Maroon, "#7b1f1f", "#420d09"],
  [Color.Navy, "#1b2a3b", "#00274d"],
  [Color.Olive, "#556b2f", "#4b5320"],
  [Color.Brown, "#4e342e", "#4e3629"],
  [Color.Coral, "#d84315", "#8b3a3a"],
  [Color.Slate, "#455a64", "#495057"],
  [Color.Gold, "#8d6e63", "#7a5c00"],
  [Color.Lavender, "#512da8", "#3f0071"],
  [Color.Mint, "#00796b", "#14544f"],
  [Color.ConstrastingColor, "#212121", "#f5f5f5"],
  [Color.Black, "#424242", "#212121"],
])("palette color %s has its light and dark values", (color, light, dark) => {
  expect(new Theme(ThemesType.LIGHT).hexColor(color)).toBe(light);
  expect(new Theme(ThemesType.DARK).hexColor(color)).toBe(dark);
});

// Generated by Codex and not thoroughly checked for correctness.
test("unknown palette colors fall back to the theme background", () => {
  expect(new Theme().hexColor(-1 as Color)).toBe("#ffffff");
  expect(new Theme(ThemesType.DARK).hexColor(-1 as Color)).toBe("#000000");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [799, "text-dark", "text-light"],
  [800, "rating-gray", "dark-rating-gray"],
  [1199, "rating-gray", "dark-rating-gray"],
  [1200, "rating-green", "dark-rating-green"],
  [1399, "rating-green", "dark-rating-green"],
  [1400, "rating-cyan", "dark-rating-cyan"],
  [1599, "rating-cyan", "dark-rating-cyan"],
  [1600, "rating-blue", "dark-rating-blue"],
  [1899, "rating-blue", "dark-rating-blue"],
  [1900, "rating-violet", "dark-rating-violet"],
  [2099, "rating-violet", "dark-rating-violet"],
  [2100, "rating-orange", "dark-rating-orange"],
  [2399, "rating-orange", "dark-rating-orange"],
  [2400, "rating-red", "dark-rating-red"],
  [2999, "rating-red", "dark-rating-red"],
  [3000, "rating-legendary", "dark-rating-legendary"],
])("rating %s chooses the CSS class for each theme", (rating, light, dark) => {
  expect(new Theme().color(rating)).toBe(light);
  expect(new Theme(ThemesType.DARK).color(rating)).toBe(dark);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [1199, Color.Gray], [1200, Color.Green], [1399, Color.Green],
  [1400, Color.Cyan], [1599, Color.Cyan], [1600, Color.Blue],
  [1899, Color.Blue], [1900, Color.Violet], [2099, Color.Violet],
  [2100, Color.Yellow], [2299, Color.Yellow], [2300, Color.Orange],
  [2399, Color.Orange], [2400, Color.Red], [2599, Color.Red],
  [2600, Color.DeepRed], [2999, Color.DeepRed], [3000, Color.Maroon],
])("rating %s maps to palette color %s at rank boundaries", (rating, expected) => {
  expect(Theme.colorForRating(rating)).toBe(expected);
});
