import { afterEach, expect, test, vi } from "vitest";
import { delay, formatDateInputValue, formatDateInputLabel, formatTimestampDate, formatTimestampDateTime, getDaysInMonth, getDaysInYear, getDayOfTheYear, getWeekNumber, getLocalizedWeekdays, parseDateInputValue } from "../../src/util/time";

afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("local leap-day input round-trips and timestamp seconds use local date/time", () => {
  const date = new Date(2024, 1, 29, 13, 5);
  expect(formatDateInputValue(date)).toBe("2024-02-29");
  expect(parseDateInputValue("2024-02-29")).toEqual(new Date(2024, 1, 29));
  expect(formatTimestampDate(date.getTime() / 1000)).toBe("29/02/2024");
  expect(formatTimestampDateTime(date.getTime() / 1000)).toBe("29/02/2024, 13:05");
  expect(formatDateInputLabel("2024-02-29")).toBe("29/02/2024");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["2023-02-29", "2024-02-30", "2026-04-31", "2026-00-01", "2026-13-01", "2026-01-00", "2026-1-01", "invalid"])("date input rejects impossible or malformed value %s without normalizing it", value => {
  expect(parseDateInputValue(value)).toBeUndefined();
  expect(formatDateInputLabel(value)).toBe(value);
});

// Generated by Codex and not thoroughly checked for correctness.
test("calendar lengths account for leap years and century exceptions", () => {
  expect(getDaysInYear(1900)).toBe(365);
  expect(getDaysInYear(2000)).toBe(366);
  expect(getDaysInYear(2024)).toBe(366);
  expect(getDaysInYear(2026)).toBe(365);
  expect(getDaysInMonth(2024, 2)).toBe(29);
  expect(getDaysInMonth(2026, 2)).toBe(28);
  expect(getDaysInMonth(2026, 4)).toBe(30);
  expect(getDaysInMonth(2026, 12)).toBe(31);
});

// Generated by Codex and not thoroughly checked for correctness.
test("day and week numbers use local calendar boundaries with Sunday-start weeks", () => {
  expect(getDayOfTheYear(new Date(2024, 0, 1))).toBe(1);
  expect(getDayOfTheYear(new Date(2024, 1, 29))).toBe(60);
  expect(getDayOfTheYear(new Date(2024, 11, 31))).toBe(366);
  expect(getWeekNumber(new Date(2026, 0, 1))).toBe(0);
  expect(getWeekNumber(new Date(2026, 0, 3))).toBe(0);
  expect(getWeekNumber(new Date(2026, 0, 4))).toBe(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("localized weekdays start at Sunday regardless of today's weekday", () => {
  vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 9, 7, 12));
  expect(getLocalizedWeekdays("en-US", "short")).toEqual(["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]);
  expect(getLocalizedWeekdays("en-US", "long")).toEqual(["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("delay resolves after its requested duration", async () => {
  vi.useFakeTimers();
  const complete = vi.fn();
  const pending = delay(100).then(complete);
  await vi.advanceTimersByTimeAsync(99);
  expect(complete).not.toHaveBeenCalled();
  await vi.advanceTimersByTimeAsync(1);
  await pending;
  expect(complete).toHaveBeenCalledTimes(1);
});
