// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { expect, test } from "vitest";
import { removeUndefinedFields } from "../../src/util/util";

test("removes only undefined fields and preserves other values", () => {
  expect(removeUndefinedFields({
    missing: undefined,
    zero: 0,
    disabled: false,
    empty: "",
    nullable: null,
    notANumber: NaN,
  })).toStrictEqual({ zero: 0, disabled: false, empty: "", nullable: null, notANumber: NaN });
});

test("returns a shallow copy without mutating the input", () => {
  interface State {
    page: number;
    search: string | undefined;
    nested: { missing: undefined };
  }
  const input: State = { page: 1, search: undefined, nested: { missing: undefined } };
  const result = removeUndefinedFields(input);

  expect(result).toStrictEqual({ page: 1, nested: { missing: undefined } });
  expect(result).not.toBe(input);
  expect(result.nested).toBe(input.nested);
  expect(input).toStrictEqual({ page: 1, search: undefined, nested: { missing: undefined } });
});

test("returns an empty object for empty inputs or only undefined fields", () => {
  expect(removeUndefinedFields({})).toStrictEqual({});
  expect(removeUndefinedFields({ first: undefined, second: undefined })).toStrictEqual({});
});
