// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { expect, test } from "vitest";
import { isEqual, removeUndefinedFields } from "../../src/util/util";

test("removes only undefined fields and preserves other values", () => {
  expect(removeUndefinedFields({
    missing: undefined,
    zero: 0,
    disabled: false,
    empty: "",
    nullable: null,
    notANumber: NaN,
  })).toStrictEqual({ zero: 0, disabled: false, empty: "", nullable: null, notANumber: NaN });
});

test("returns a shallow copy without mutating the input", () => {
  interface State {
    page: number;
    search: string | undefined;
    nested: { missing: undefined; };
  }
  const input: State = { page: 1, search: undefined, nested: { missing: undefined } };
  const result = removeUndefinedFields(input);

  expect(result).toStrictEqual({ page: 1, nested: { missing: undefined } });
  expect(result).not.toBe(input);
  expect(result.nested).toBe(input.nested);
  expect(input).toStrictEqual({ page: 1, search: undefined, nested: { missing: undefined } });
});

test("returns an empty object for empty inputs or only undefined fields", () => {
  expect(removeUndefinedFields({})).toStrictEqual({});
  expect(removeUndefinedFields({ first: undefined, second: undefined })).toStrictEqual({});
});

test("compares nested objects independently of key insertion order", () => {
  expect(isEqual(
    { page: 1, filter: { tags: ["dp", "math"], rating: 1200 } },
    { filter: { rating: 1200, tags: ["dp", "math"] }, page: 1 },
  )).toBe(true);
  expect(isEqual({ filter: { rating: 1200 } }, { filter: { rating: 1400 } })).toBe(false);
});

test("distinguishes missing fields from fields containing undefined", () => {
  expect(isEqual({}, { field: undefined })).toBe(false);
  expect(isEqual({ field: undefined }, { field: undefined })).toBe(true);
});

test("preserves array order and compares primitive types strictly", () => {
  expect(isEqual([1, 2], [2, 1])).toBe(false);
  expect(isEqual([1, { page: 2 }], [1, { page: 2 }])).toBe(true);
  expect(isEqual(1, "1")).toBe(false);
  expect(isEqual(undefined, null)).toBe(false);
  expect(isEqual(NaN, NaN)).toBe(true);
});

test("compares sets and maps without depending on insertion order", () => {
  expect(isEqual(new Set(["dp", "math"]), new Set(["math", "dp"]))).toBe(true);
  expect(isEqual(new Set(["dp"]), new Set(["math"]))).toBe(false);
  expect(isEqual(
    new Map([["page", { value: 1 }], ["rating", { value: 1200 }]]),
    new Map([["rating", { value: 1200 }], ["page", { value: 1 }]]),
  )).toBe(true);
  expect(isEqual(new Map([["page", 1]]), new Map([["page", 2]]))).toBe(false);
});

test("compares dates and cyclic objects", () => {
  expect(isEqual(new Date("2026-01-01"), new Date("2026-01-01"))).toBe(true);
  expect(isEqual(new Date("2026-01-01"), new Date("2026-01-02"))).toBe(false);

  interface CyclicValue {
    value: number;
    self?: CyclicValue;
  }
  const left: CyclicValue = { value: 1 };
  const right: CyclicValue = { value: 1 };
  left.self = left;
  right.self = right;
  expect(isEqual(left, right)).toBe(true);
  right.value = 2;
  expect(isEqual(left, right)).toBe(false);
});
