// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { afterEach, expect, test, vi } from "vitest";
import { clampNumber, getRandomInteger, getFormattedString, getContestUrl, getProblemUrl, getUserInfoURL, isEqual, removeUndefinedFields, getUserSubmissionsURL, parseQuery, isNonNANNumber, isStringNumber } from "../../src/util/util";

test("removes only undefined fields and preserves other values", () => {
  expect(removeUndefinedFields({
    missing: undefined,
    zero: 0,
    disabled: false,
    empty: "",
    nullable: null,
    notANumber: NaN,
  })).toStrictEqual({ zero: 0, disabled: false, empty: "", nullable: null, notANumber: NaN });
});

test("returns a shallow copy without mutating the input", () => {
  interface State {
    page: number;
    search: string | undefined;
    nested: { missing: undefined; };
  }
  const input: State = { page: 1, search: undefined, nested: { missing: undefined } };
  const result = removeUndefinedFields(input);

  expect(result).toStrictEqual({ page: 1, nested: { missing: undefined } });
  expect(result).not.toBe(input);
  expect(result.nested).toBe(input.nested);
  expect(input).toStrictEqual({ page: 1, search: undefined, nested: { missing: undefined } });
});

test("returns an empty object for empty inputs or only undefined fields", () => {
  expect(removeUndefinedFields({})).toStrictEqual({});
  expect(removeUndefinedFields({ first: undefined, second: undefined })).toStrictEqual({});
});

test("compares nested objects independently of key insertion order", () => {
  expect(isEqual(
    { page: 1, filter: { tags: ["dp", "math"], rating: 1200 } },
    { filter: { rating: 1200, tags: ["dp", "math"] }, page: 1 },
  )).toBe(true);
  expect(isEqual({ filter: { rating: 1200 } }, { filter: { rating: 1400 } })).toBe(false);
});

test("distinguishes missing fields from fields containing undefined", () => {
  expect(isEqual({}, { field: undefined })).toBe(false);
  expect(isEqual({ field: undefined }, { field: undefined })).toBe(true);
});

test("preserves array order and compares primitive types strictly", () => {
  expect(isEqual([1, 2], [2, 1])).toBe(false);
  expect(isEqual([1, { page: 2 }], [1, { page: 2 }])).toBe(true);
  expect(isEqual(1, "1")).toBe(false);
  expect(isEqual(undefined, null)).toBe(false);
  expect(isEqual(NaN, NaN)).toBe(true);
});

test("compares sets and maps without depending on insertion order", () => {
  expect(isEqual(new Set(["dp", "math"]), new Set(["math", "dp"]))).toBe(true);
  expect(isEqual(new Set(["dp"]), new Set(["math"]))).toBe(false);
  expect(isEqual(
    new Map([["page", { value: 1 }], ["rating", { value: 1200 }]]),
    new Map([["rating", { value: 1200 }], ["page", { value: 1 }]]),
  )).toBe(true);
  expect(isEqual(new Map([["page", 1]]), new Map([["page", 2]]))).toBe(false);
});

test("compares dates and cyclic objects", () => {
  expect(isEqual(new Date("2026-01-01"), new Date("2026-01-01"))).toBe(true);
  expect(isEqual(new Date("2026-01-01"), new Date("2026-01-02"))).toBe(false);

  interface CyclicValue {
    value: number;
    self?: CyclicValue;
  }
  const left: CyclicValue = { value: 1 };
  const right: CyclicValue = { value: 1 };
  left.self = left;
  right.self = right;
  expect(isEqual(left, right)).toBe(true);
  right.value = 2;
  expect(isEqual(left, right)).toBe(false);
});

afterEach(() => vi.restoreAllMocks());

// Generated by Codex and not thoroughly checked for correctness.
test.each([[0, 3], [0.5, 6], [0.999999999999, 9]])("random source %s returns an in-range integer %s", (random, expected) => {
  vi.spyOn(Math, "random").mockReturnValue(random);
  expect(getRandomInteger(3, 10)).toBe(expected);
  expect(getRandomInteger(5, 6)).toBe(5);
});

// Generated by Codex and not thoroughly checked for correctness.
test("random selection supports negative ranges with an exclusive upper bound", () => {
  vi.spyOn(Math, "random").mockReturnValue(0.999999999999);
  expect(getRandomInteger(-5, -1)).toBe(-2);
});

// Generated by Codex and not thoroughly checked for correctness.
test("clamping handles NaN, infinities and inclusive endpoints", () => {
  expect(clampNumber(NaN, 0, 10)).toBe(0);
  expect(clampNumber(-Infinity, 0, 10)).toBe(0);
  expect(clampNumber(Infinity, 0, 10)).toBe(10);
  expect(clampNumber(0, 0, 10)).toBe(0);
  expect(clampNumber(10, 0, 10)).toBe(10);
  expect(clampNumber(3.5, 0, 10)).toBe(3.5);
});

// Generated by Codex and not thoroughly checked for correctness.
test("number formatting uses explicit US grouping and requested decimal precision", () => {
  expect(getFormattedString(12345.678)).toBe("12,345.68");
  expect(getFormattedString(12, { minimumFractionDigits: 2 })).toBe("12.00");
});

// Generated by Codex and not thoroughly checked for correctness.
test("Codeforces link helpers retain high IDs and problem indexes and normalize handle separators", () => {
  expect(getContestUrl(15000)).toBe("https://codeforces.com/contest/15000");
  expect(getProblemUrl(15000, "A2")).toBe("https://codeforces.com/contest/15000/problem/A2");
  expect(getUserInfoURL(" tourist,jiangly ")).toBe("https://codeforces.com/api/user.info?handles=tourist;jiangly");
});

// Generated by Codex and not thoroughly checked for correctness.
test("submission URLs include pagination only for a nonzero limit", () => {
  expect(getUserSubmissionsURL("tourist", 25)).toBe("https://codeforces.com/api/user.status?handle=tourist&&from=1&count=25");
  expect(getUserSubmissionsURL("tourist", 0)).toBe("https://codeforces.com/api/user.status?handle=tourist");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([" ?name=%E2%9C%93&tag=dp&empty=&flag&tag=graphs ", "name=%E2%9C%93&tag=dp&empty=&flag&tag=graphs"])(
  "query parsing decodes values, preserves empty flags and lets later keys replace earlier ones: %s", query => {
    expect(parseQuery(query)).toEqual({ name: "✓", tag: "graphs", empty: "", flag: "" });
    expect(parseQuery("%74ag=math%20problems")).toEqual({ tag: "math problems" });
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("query parsing rejects malformed percent escapes", () => {
  expect(() => parseQuery("tag=%ZZ")).toThrow(URIError);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [0, true], [-1.5, true], [Infinity, true], [NaN, false], ["1", false], [undefined, false], [null, false],
])("non-NaN numeric guard classifies %s as %s", (value, expected) => {
  expect(isNonNANNumber(value)).toBe(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([["42", true], [" -1.5 ", true], ["", true], ["Infinity", true], ["NaN", false], ["12px", false]])(
  "numeric string conversion classifies %j as %s", (value, expected) => {
    expect(isStringNumber(value)).toBe(expected);
  },
);
