// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { expect, test } from "vitest";
import { validateValue, validators } from "../../src/util/validators";

test("validates values with the supplied validator", () => {
  expect(validateValue<number>("2", 1, validators.number)).toBe(2);
  expect(validateValue<number>("invalid", 1, validators.number)).toBe(1);
});

test("trusts unvalidated object properties without restoring missing properties", () => {
  const defaultValue = { page: 1, search: "default", enabled: true };

  expect(validateValue(
    { page: "2", search: 3 },
    defaultValue,
    { page: validators.nonNegativeInteger },
  )).toEqual({ page: 2, search: 3 });
});

test("lets validators decide how to handle missing object properties", () => {
  const defaultValue: {
    minContestDate: string | undefined;
    maxContestDate: string | undefined;
    status: string;
  } = {
    minContestDate: "2026-01-01",
    maxContestDate: "2026-06-30",
    status: "SOLVED",
  };

  expect(validateValue(
    { status: "ATTEMPTED" },
    defaultValue,
    {
      minContestDate: validators.date,
      maxContestDate: validators.date,
      status: validators.string,
    },
  )).toStrictEqual({
    status: "ATTEMPTED",
    minContestDate: undefined,
    maxContestDate: undefined,
  });
});

test("validates a single enum value", () => {
  const validateTheme = validators.enumValue([1, 2] as const);

  expect(validateTheme(2, 1)).toBe(2);
  expect(validateTheme(3, 1)).toBe(1);
});

test("parses scalar values without a fallback", () => {
  expect(validateValue<number>("7", undefined, validators.nonNegativeInteger)).toBe(7);
  expect(validateValue<number>("invalid", undefined, validators.nonNegativeInteger)).toBeUndefined();
  expect(validateValue<boolean>("true", undefined, validators.boolean)).toBe(true);
  expect(validateValue<boolean>("invalid", undefined, validators.boolean)).toBeUndefined();
});

test("parses enum arrays without a fallback", () => {
  const validator = validators.enumArray(["SOLVED", "ATTEMPTED"]);
  expect(validateValue<string[]>("SOLVED,ATTEMPTED", undefined, validator)).toEqual(["SOLVED", "ATTEMPTED"]);
  expect(validateValue<string[]>(123, undefined, validator)).toBeUndefined();
  expect(validateValue<string[]>("invalid", undefined, validator)).toBeUndefined();
});

test("retains undefined results from property validators", () => {
  interface Filter {
    page: number;
    search: string;
    minContestDate: string | undefined;
  }
  expect(validateValue<Filter>(
    { page: "invalid", minContestDate: "invalid", search: "url" },
    undefined,
    { page: validators.nonNegativeInteger, search: validators.string, minContestDate: validators.date },
  )).toStrictEqual({ page: undefined, minContestDate: undefined, search: "url" });
});

test("assigns validator results for missing properties without a fallback", () => {
  expect(validateValue<{ page: number }>(
    {},
    undefined,
    { page: validators.number },
  )).toStrictEqual({ page: undefined });
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([null, undefined, "", "  ", "invalid", Infinity, NaN, "1.5", -1, Number.MAX_SAFE_INTEGER + 1])(
  "integer validation falls back on invalid URL/storage input %j", value => {
    expect(validators.nonNegativeInteger(value, 7)).toBe(7);
    expect(validators.positiveInteger(value, undefined)).toBeUndefined();
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("integer validation preserves zero only when allowed and accepts numeric URL strings", () => {
  expect(validators.nonNegativeInteger("0", 7)).toBe(0);
  expect(validators.positiveInteger("0", 7)).toBe(7);
  expect(validators.positiveInteger(" 25 ", undefined)).toBe(25);
  expect(validators.integer("-2", undefined)).toBe(-2);
  expect(validators.number("1.5", undefined)).toBe(1.5);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["TRUE", "1", 1, 0, "", null])("boolean validation rejects unsupported representations %j", value => {
  expect(validators.boolean(value, undefined)).toBeUndefined();
  expect(validators.boolean(value, false)).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("tag and status arrays trim, deduplicate and reject mixed or unknown values", () => {
  expect(validators.stringArray(" dp, graphs,dp, ,", undefined)).toEqual(["dp", "graphs"]);
  expect(validators.stringArray([" math ", "dp", "math"], undefined)).toEqual(["math", "dp"]);
  expect(validators.stringArray(["dp", 1], ["graphs"])).toEqual(["graphs"]);
  const status = validators.enumArray(["SOLVED", "ATTEMPTED"]);
  expect(status("SOLVED,unknown", ["ATTEMPTED"])).toEqual(["ATTEMPTED"]);
  expect(status("", undefined)).toEqual([]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("date validators clear optional dates, accept leap days and retain valid fallback dates", () => {
  expect(validators.date("", "2026-01-01")).toBeUndefined();
  expect(validators.date(undefined, "2026-01-01")).toBeUndefined();
  expect(validators.date("2024-02-29", undefined)).toBe("2024-02-29");
  expect(validators.date("2026-02-29", "2026-01-01")).toBe("2026-01-01");
  expect(validators.date("2026-02-30", undefined)).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("optional strings retain a fallback for non-string values", () => {
  expect(validators.optionalString(12, "saved")).toBe("saved");
  expect(validators.optionalString(null, undefined)).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("undefined property validators leave supplied values untouched", () => {
  expect(validateValue({ page: "raw", search: 12 }, { page: 1, search: "saved" }, {
    page: undefined, search: validators.string,
  })).toEqual({ page: "raw", search: "saved" });
});
