// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { expect, test } from "vitest";
import { validateValue, validators } from "../../src/util/validators";

test("validates values with the supplied validator", () => {
  expect(validateValue<number>("2", 1, validators.number)).toBe(2);
  expect(validateValue<number>("invalid", 1, validators.number)).toBe(1);
});

test("trusts unvalidated object properties without restoring missing properties", () => {
  const defaultValue = { page: 1, search: "default", enabled: true };

  expect(validateValue(
    { page: "2", search: 3 },
    defaultValue,
    { page: validators.nonNegativeInteger },
  )).toEqual({ page: 2, search: 3 });
});

test("lets validators decide how to handle missing object properties", () => {
  const defaultValue: {
    minContestDate: string | undefined;
    maxContestDate: string | undefined;
    status: string;
  } = {
    minContestDate: "2026-01-01",
    maxContestDate: "2026-06-30",
    status: "SOLVED",
  };

  expect(validateValue(
    { status: "ATTEMPTED" },
    defaultValue,
    {
      minContestDate: validators.date,
      maxContestDate: validators.date,
      status: validators.string,
    },
  )).toStrictEqual({
    status: "ATTEMPTED",
    minContestDate: undefined,
    maxContestDate: undefined,
  });
});

test("validates a single enum value", () => {
  const validateTheme = validators.enumValue([1, 2] as const);

  expect(validateTheme(2, 1)).toBe(2);
  expect(validateTheme(3, 1)).toBe(1);
});

test("parses scalar values without a fallback", () => {
  expect(validateValue<number>("7", undefined, validators.nonNegativeInteger)).toBe(7);
  expect(validateValue<number>("invalid", undefined, validators.nonNegativeInteger)).toBeUndefined();
  expect(validateValue<boolean>("true", undefined, validators.boolean)).toBe(true);
  expect(validateValue<boolean>("invalid", undefined, validators.boolean)).toBeUndefined();
});

test("parses enum arrays without a fallback", () => {
  const validator = validators.enumArray(["SOLVED", "ATTEMPTED"]);
  expect(validateValue<string[]>("SOLVED,ATTEMPTED", undefined, validator)).toEqual(["SOLVED", "ATTEMPTED"]);
  expect(validateValue<string[]>(123, undefined, validator)).toBeUndefined();
  expect(validateValue<string[]>("invalid", undefined, validator)).toBeUndefined();
});

test("retains undefined results from property validators", () => {
  interface Filter {
    page: number;
    search: string;
    minContestDate: string | undefined;
  }
  expect(validateValue<Filter>(
    { page: "invalid", minContestDate: "invalid", search: "url" },
    undefined,
    { page: validators.nonNegativeInteger, search: validators.string, minContestDate: validators.date },
  )).toStrictEqual({ page: undefined, minContestDate: undefined, search: "url" });
});

test("assigns validator results for missing properties without a fallback", () => {
  expect(validateValue<{ page: number }>(
    {},
    undefined,
    { page: validators.number },
  )).toStrictEqual({ page: undefined });
});
