# syntax=docker/dockerfile:1.7-labs
FROM golang:1.22.3-alpine AS builder

WORKDIR /build
COPY --exclude=.env* . /build
RUN go build -o api_bin ./cmd/api/main.go

FROM alpine

WORKDIR /app
COPY --from=builder /build/api_bin .
COPY .env.docker .env
EXPOSE 8080
CMD [ "/app/api_bin" ]