import { beforeEach, afterEach, expect, test, vi } from "vitest";
import { StorageService } from "../../src/util/StorageService";
beforeEach(() => { vi.resetModules(); localStorage.clear(); vi.spyOn(console, "log").mockImplementation(() => {}); });
afterEach(() => { localStorage.clear(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("a saved session restores identity and its verified handle, and logout persists their removal", async () => {
  const user = { id: 7, githubId: 42, githubUsername: "octocat", email: "test@example.test", avatarUrl: "", cfHandle: "tourist", cfVerifiedHandle: "tourist", admin: false, jwtToken: "saved-session" };
  StorageService.saveObject(StorageService.Keys.StateV2, { userList: { id: 1, handles: ["tourist"], error: "", user } });
  StorageService.setJWTToken("saved-session");
  const { default: store } = await import("../../src/data/store");
  const { removeUser } = await import("../../src/data/reducers/userSlice");
  expect(store.getState().userList.user?.githubUsername).toBe("octocat");
  expect(store.getState().userList.user?.cfVerifiedHandle).toBe("tourist");
  expect(store.getState().userList.handles).toEqual(["tourist"]);
  store.dispatch(removeUser()); StorageService.removeJWTToken();
  const persisted = StorageService.getObject<{ userList?: { user?: unknown } }>(StorageService.Keys.StateV2, {});
  expect(persisted.userList?.user).toBeUndefined();
  expect(StorageService.getJWTToken()).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("an older saved session restores identity without inventing a verified handle", async () => {
  const user = { id: 7, githubId: 42, githubUsername: "octocat", email: "test@example.test", avatarUrl: "", cfHandle: "tourist", cfVerified: true, admin: false, jwtToken: "saved-session" };
  StorageService.saveObject(StorageService.Keys.StateV2, { userList: { id: 1, handles: ["tourist"], error: "", user } });
  const { default: store } = await import("../../src/data/store");
  expect(store.getState().userList.user?.githubUsername).toBe("octocat");
  expect(store.getState().userList.user?.cfVerifiedHandle).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("corrupt persisted session JSON restores initial state without a startup crash", async () => {
  localStorage.setItem(StorageService.Keys.StateV2, "{invalid");
  const { default: store } = await import("../../src/data/store");
  expect(store.getState().userList.user).toBeUndefined();
  expect(store.getState().userList.handles).toEqual([]);
  expect(store.getState().appState.loaded).toBe(false);
});
