import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import { useLocation } from "react-router";
import useCallbackHandler from "../../src/hooks/useCallbackHandler";
import { createRouterWrapper } from "../support/router";

beforeEach(resetFrontendMocks);
afterEach(cleanup);
function callback(entry: string) {
  return renderHook(() => { useCallbackHandler(); return useLocation(); }, { wrapper: createRouterWrapper(entry) });
}

// Generated by Codex and not thoroughly checked for correctness.
test("callback forwards decoded OAuth parameters once, announces authentication and opens contests", async () => {
  const hook = callback("/callback/auth-gh?code=code%2B1&state=state%26two");
  await waitFor(() => expect(hook.result.current.pathname).toBe("/contests"));
  expect(frontend.handleGithubCallback).toHaveBeenCalledExactlyOnceWith("code+1", "state&two");
  expect(frontend.showGeneralToast).toHaveBeenCalledWith("Authenticating...");
  expect(frontend.showErrorToast).not.toHaveBeenCalled();
});

// Generated by Codex and not thoroughly checked for correctness.
test("missing state rejects locally and navigates without an authentication request", () => {
  const hook = callback("/callback/auth-gh?code=code");
  expect(hook.result.current.pathname).toBe("/contests");
  expect(frontend.handleGithubCallback).not.toHaveBeenCalled();
  expect(frontend.showErrorToast).toHaveBeenCalledWith("Authentication failed!");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["/callback/auth-gh?state=state", "/callback/auth-gh", "/problems?code=code&state=state"])(
  "incomplete or unrelated callback %s currently remains on its route without requesting authentication", entry => {
    const hook = callback(entry);
    expect(hook.result.current.pathname).toBe(entry.split("?")[0]);
    expect(frontend.handleGithubCallback).not.toHaveBeenCalled();
    expect(frontend.showErrorToast).not.toHaveBeenCalled();
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("rejected authentication displays the failure after navigating to contests", async () => {
  frontend.handleGithubCallback.mockRejectedValue(new Error("Invalid state"));
  const hook = callback("/callback/auth-gh?code=code&state=state");
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("Invalid state"));
  expect(hook.result.current.pathname).toBe("/contests");
});
