import { backendUser, listApi, setupBackendMock } from "../support/backendMocks";
import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import useUser from "../../src/hooks/useUser";
import { errorAuthenticatingUser } from "../../src/data/reducers/userSlice";
import { StorageService } from "../../src/util/StorageService";

let backend: ReturnType<typeof setupBackendMock>;
beforeEach(() => {
  localStorage.clear();
  backend = setupBackendMock();
  vi.spyOn(console, "log").mockImplementation(() => {});
});
afterEach(() => { cleanup(); backend.dispose(); localStorage.clear(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("GitHub callback maps the user, clears the previous error and persists the token", async () => {
  backend.respond({ user: backendUser, token: "test-session" });
  backend.store.dispatch(errorAuthenticatingUser({ errorMessage: "Previous failure" }));
  const hook = renderHook(useUser, { wrapper: backend.wrapper });
  expect(hook.result.current.isAuthenticated).toBe(false);
  await act(async () => hook.result.current.handleGithubCallback("code +/?", "state &?"));
  expect(hook.result.current.user).toEqual({
    id: 7, githubId: 42, githubUsername: "octocat", email: "octocat@example.test",
    avatarUrl: "https://example.test/avatar", cfHandle: "tourist", cfVerified: true, admin: false, jwtToken: "test-session",
  });
  expect(hook.result.current.isAuthenticated).toBe(true);
  expect(backend.store.getState().userList.error).toBe("");
  expect(StorageService.getJWTToken()).toBe("test-session");
  const request = backend.requests[0];
  const url = new URL(request.url);
  expect(url.pathname).toBe("/auth/github/callback");
  expect(url.searchParams.get("code")).toBe("code +/?");
  expect(url.searchParams.get("state")).toBe("state &?");
  expect(request.method).toBe("GET");
  expect(request.credentials).toBe("include");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([[401, { error: "Invalid state" }, "Invalid state"], [403, {}, "Authentication failed!"], [500, {}, "Authentication failed!"]])(
  "callback HTTP %i rejection leaves the user anonymous and records feedback", async (status, body, message) => {
    backend.respond(body, status as number);
    const hook = renderHook(useUser, { wrapper: backend.wrapper });
    await act(async () => { await expect(hook.result.current.handleGithubCallback("bad", "state")).rejects.toThrow(message as string); });
    expect(hook.result.current.isAuthenticated).toBe(false);
    expect(backend.store.getState().userList.error).toBe(message);
    expect(StorageService.getJWTToken()).toBeNull();
  },
);

// Generated by Codex and not thoroughly checked for correctness.
test("logout clears Redux identity and stops sending authorization on subsequent requests", async () => {
  backend.respond({ user: backendUser, token: "test-session" });
  const hook = renderHook(useUser, { wrapper: backend.wrapper });
  await act(async () => hook.result.current.handleGithubCallback("code", "state"));
  backend.respond({ lists: [] });
  await act(async () => { await backend.store.dispatch(listApi.endpoints.getAllLists.initiate()).unwrap(); });
  expect(backend.requests[backend.requests.length - 1]?.headers.get("Authorization")).toBe("Bearer test-session");
  act(() => hook.result.current.logout());
  expect(hook.result.current.user).toBeUndefined();
  expect(hook.result.current.isAuthenticated).toBe(false);
  expect(StorageService.getJWTToken()).toBeNull();
  await act(async () => { await backend.store.dispatch(listApi.endpoints.getAllLists.initiate(undefined, { forceRefetch: true })).unwrap(); });
  expect(backend.requests[backend.requests.length - 1]?.headers.has("Authorization")).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("network failures reject authentication with fallback feedback and no saved identity", async () => {
  backend.fetchMock.mockRejectedValue(new TypeError("Network unavailable"));
  const hook = renderHook(useUser, { wrapper: backend.wrapper });
  await act(async () => { await expect(hook.result.current.handleGithubCallback("code", "state")).rejects.toThrow("Authentication failed!"); });
  expect(hook.result.current.isAuthenticated).toBe(false);
  expect(backend.store.getState().userList.error).toBe("Authentication failed!");
  expect(StorageService.getJWTToken()).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("logout in another hook instance prevents a pending callback from restoring identity", async () => {
  let resolve!: (value: Response) => void;
  backend.fetchMock.mockImplementationOnce(() => new Promise(done => { resolve = done; }));
  const callback = renderHook(useUser, { wrapper: backend.wrapper });
  const menu = renderHook(useUser, { wrapper: backend.wrapper });
  let pending!: Promise<void>;
  act(() => { pending = callback.result.current.handleGithubCallback("pending", "state"); });
  await vi.waitFor(() => expect(backend.fetchMock).toHaveBeenCalledTimes(1));
  act(() => menu.result.current.logout());
  await act(async () => { resolve(Response.json({ user: backendUser, token: "late-session" })); await pending; });
  expect(callback.result.current.isAuthenticated).toBe(false);
  expect(StorageService.getJWTToken()).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("a superseded authentication response cannot replace the latest identity", async () => {
  let resolveOld!: (value: Response) => void;
  backend.fetchMock.mockImplementationOnce(() => new Promise(done => { resolveOld = done; })).mockResolvedValueOnce(Response.json({ user: { ...backendUser, github_username: "latest" }, token: "latest-session" }));
  const hook = renderHook(useUser, { wrapper: backend.wrapper });
  let old!: Promise<void>;
  act(() => { old = hook.result.current.handleGithubCallback("old", "state"); });
  await vi.waitFor(() => expect(backend.fetchMock).toHaveBeenCalledTimes(1));
  await act(async () => { await hook.result.current.handleGithubCallback("new", "state"); });
  await act(async () => { resolveOld(Response.json({ user: backendUser, token: "old-session" })); await old; });
  expect(hook.result.current.user?.githubUsername).toBe("latest");
  expect(StorageService.getJWTToken()).toBe("latest-session");
});
