export const BACKEND_API_URL = import.meta.env.VITE_BACKEND_API_URL
export const GITHUB_OAUTH_CLIENT_ID = import.meta.env.VITE_GITHUB_OAUTH_CLIENT_ID
export const GITHUB_OAUTH_REDIRECT_URI = import.meta.env.VITE_GITHUB_OAUTH_REDIRECT_URI
export const IS_BACKEND_AVAILABLE = import.meta.env.VITE_IS_BACKEND_AVAILABLE
export const BACKEND_NOT_AVAILBLE_MESSAGE = import.meta.env.VITE_BACKEND_NOT_AVAILBLE_MESSAGE