import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { charts, resetChartMocks } from "../support/chartMocks";
import { cleanup, render } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import BarChart from "../../src/components/common/charts/BarChart";
import PieChart from "../../src/components/common/charts/PieChart";
import Theme, { Color, ThemesType } from "../../src/util/Theme";
import type { TooltipItem, TooltipModel } from "chart.js";

beforeEach(() => { resetFrontendMocks(); resetChartMocks(); });
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("bar theme %s maps scalar and per-bar colors and keeps tooltip data", (theme) => {
  frontend.theme = new Theme(theme);
  render(<BarChart title="Ratings" labels={[800, 1200]} dataSets={[
    { label: "Solved", data: [1, 2], color: [Color.Gray, Color.Green] },
    { label: "Attempted", data: [3, 4], color: Color.LightRed },
    { label: "Unspecified", data: [0, 0] },
  ]} />);
  const chart = charts.bars.get("Ratings")!;
  expect(chart.data.datasets[0].backgroundColor).toEqual(theme === ThemesType.LIGHT ? ["#9e9e9e", "#66bb6a"] : ["#6c757d", "#2e7d32"]);
  expect(chart.data.datasets[1].backgroundColor).toBe(theme === ThemesType.LIGHT ? "#FFCDD2" : "#EF9A9A");
  expect(chart.data.datasets[2].backgroundColor).toBeUndefined();
  expect(chart.options).toMatchObject({ responsive: true, plugins: { legend: { display: true }, title: { text: "Ratings" } }, scales: { y: { beginAtZero: true } } });
  const label = chart.options!.plugins!.tooltip!.callbacks!.label!;
  expect(label.call({} as TooltipModel<"bar">, { raw: 12.345 } as TooltipItem<"bar">)).toBe("12.35");
  expect(label.call({} as TooltipModel<"bar">, { raw: "invalid" } as TooltipItem<"bar">)).toBe("unknown");
});

// Generated by Codex and not thoroughly checked for correctness.
test("bar chart updates theme colors on redraw with stable labels and dataset arrays", () => {
  const labels = [800];
  const dataSets = [{ label: "AC", data: [50], color: Color.Gray }];
  const view = render(<BarChart title="Stable" labels={labels} dataSets={dataSets} yMax={100} />);
  expect(charts.bars.get("Stable")!.data.datasets[0].backgroundColor).toBe("#9e9e9e");
  frontend.theme = new Theme(ThemesType.DARK);
  view.rerender(<BarChart title="Stable" labels={labels} dataSets={dataSets} yMax={101} />);
  expect(charts.bars.get("Stable")!.data.datasets[0].backgroundColor).toBe("#6c757d");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("pie theme %s uses distinct fallback colors and aligned labels", (theme) => {
  frontend.theme = new Theme(theme);
  render(<PieChart title="Verdicts" labels={["OK", "WA", "TLE"]} dataSets={[{ label: "Submissions", data: [
    { data: 3, backgroundColor: Color.Green }, { data: 2, backgroundColor: Color.Red }, { data: 1 },
  ] }]} />);
  const chart = charts.pies.get("Verdicts")!;
  expect(chart.data.labels).toEqual(["OK", "WA", "TLE"]);
  expect(chart.data.datasets[0].data).toEqual([3, 2, 1]);
  const colors = chart.data.datasets[0].backgroundColor as string[];
  expect(colors.slice(0, 2)).toEqual(theme === ThemesType.LIGHT ? ["#66bb6a", "#ef5350"] : ["#2e7d32", "#b71c1c"]);
  expect(new Set(colors).size).toBe(3);
  expect(chart.data.datasets[0].borderColor).toEqual(colors);
  expect(chart.options).toMatchObject({ responsive: true, maintainAspectRatio: false, plugins: { legend: { position: "bottom" } } });
});

// Generated by Codex and not thoroughly checked for correctness.
test("pie data labels calculate percentages and hide zero values without NaN", () => {
  render(<PieChart title="Percentages" labels={["Accepted", "Attempted", "Unused"]} dataSets={[{ label: "Counts", data: [{ data: 3 }, { data: 2 }, { data: 0 }] }]} />);
  const chart = charts.pies.get("Percentages")!;
  const formatter = chart.options!.plugins!.datalabels!.formatter!;
  const context = { chart: { data: chart.data } } as Parameters<typeof formatter>[1];
  expect(formatter(3, context)).toBe("60.0%");
  expect(formatter(2, context)).toBe("40.0%");
  expect(formatter(0, context)).toBe("");
  expect(formatter(0, { chart: { data: { datasets: [{ data: [0, 0] }] } } } as Parameters<typeof formatter>[1])).toBe("");
  const tooltip = chart.options!.plugins!.tooltip!.callbacks!.label!;
  expect(tooltip.call({} as TooltipModel<"pie">, { raw: 3 } as TooltipItem<"pie">)).toBe("3");
});
