import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { charts, resetChartMocks } from "../support/chartMocks";
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import StatPage from "../../src/components/stats/StatPage";
import { seedStatisticsFixtures } from "../support/statisticsFixtures";
import { createSubmission } from "../support/problemFixtures";
import { Verdict } from "../../src/types/CF/Submission";
import { ContestCat } from "../../src/types/CF/Contest";

beforeEach(() => { resetFrontendMocks(); resetChartMocks(); localStorage.clear(); });
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("empty state gives way to all configured charts and returns after handles clear", () => {
  const view = render(<StatPage />);
  expect(screen.getByText("No data available")).toBeDefined();
  expect(screen.queryAllByRole("img")).toHaveLength(0);
  seedStatisticsFixtures();
  view.rerender(<StatPage />);
  for (const title of ["Submissions By Verdict", "Solve Count By Ratings", "Rating By AC Percentage", "Div. 2"]) {
    expect(screen.getByRole("img", { name: title })).toBeDefined();
  }
  expect(screen.getByRole("combobox", { name: "Select heatmap year" })).toBeDefined();
  expect(screen.queryByText("No data available")).toBeNull();
  frontend.submissions = [];
  view.rerender(<StatPage />);
  expect(screen.getByText("No data available")).toBeDefined();
  expect(screen.queryAllByRole("img")).toHaveLength(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("verdict chart aligns labels with F1 counts instead of deduplicating problems", () => {
  seedStatisticsFixtures();
  render(<StatPage />);
  const data = charts.pies.get("Submissions By Verdict")!.data;
  expect(data.labels).toEqual(["OK", "WRONG_ANSWER"]);
  expect(data.datasets[0].data).toEqual([3, 2]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("rating chart counts distinct rated problems and excludes unrated acceptances", () => {
  seedStatisticsFixtures();
  render(<StatPage />);
  const data = charts.bars.get("Solve Count By Ratings")!.data;
  expect(data.datasets.map((dataset) => dataset.label)).toEqual(["Solved", "Attempted"]);
  expect(data.datasets[0].data).toEqual([1, ...Array(27).fill(0)]);
  expect(data.datasets[1].data).toEqual([0, 0, 0, 0, 1, ...Array(23).fill(0)]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("F1 rating AC percentages count submissions, leaving unused buckets at zero", () => {
  seedStatisticsFixtures();
  render(<StatPage />);
  const chart = charts.bars.get("Rating By AC Percentage")!;
  expect(chart.data.datasets[0].data[0]).toBeCloseTo(200 / 3);
  expect(chart.data.datasets[0].data.slice(1)).toEqual(Array(27).fill(0));
  expect(chart.options!.scales!.y).toMatchObject({ min: 0, max: 100 });
});

// Generated by Codex and not thoroughly checked for correctness.
test("one acceptance and one rejection yield 50 percent and refresh to 100 percent", () => {
  seedStatisticsFixtures();
  frontend.submissions = [frontend.submissions[0], frontend.submissions[1]];
  const view = render(<StatPage />);
  expect(charts.bars.get("Rating By AC Percentage")!.data.datasets[0].data[0]).toBe(50);
  frontend.submissions = [frontend.submissions[1]];
  view.rerender(<StatPage />);
  expect(charts.bars.get("Rating By AC Percentage")!.data.datasets[0].data[0]).toBe(100);
});

// Generated by Codex and not thoroughly checked for correctness.
test("category charts count raw submissions and provide identifiable verdict slices", () => {
  seedStatisticsFixtures();
  render(<StatPage />);
  const category = charts.pies.get("Div. 2")!.data;
  expect(category.labels).toEqual(["SOLVED", "ATTEMPTED", "UNSOLVED"]);
  expect(category.datasets[0].data).toEqual([3, 2, 0]);
  expect(screen.queryByRole("img", { name: "Div. 1" })).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("missing categories and absent contests group into Others", () => {
  seedStatisticsFixtures();
  frontend.contests[0].category = undefined;
  frontend.submissions.push(createSubmission(6, frontend.problems[2], Verdict.OK, 600));
  frontend.contests = frontend.contests.filter((contest) => contest.id !== 101);
  render(<StatPage />);
  expect(charts.pies.get(ContestCat.OTHERS)!.data.datasets[0].data).toEqual([3, 2, 0]);
  expect(charts.pies.get(ContestCat.DIV2)!.data.datasets[0].data).toEqual([1, 0, 0]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("expanded shared submissions do not inflate category totals", () => {
  seedStatisticsFixtures();
  frontend.rawSubmissions = [...frontend.submissions];
  const shared = createSubmission(2, frontend.problems[2], Verdict.OK, 200);
  shared.fromShared = true;
  frontend.submissions.push(shared);
  render(<StatPage />);
  expect(charts.pies.get("Div. 2")!.data.datasets[0].data).toEqual([3, 2, 0]);
});
