import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { act, cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import SubmissionsHeatMap from "../../src/components/stats/charts/SubmissionsHeatMap";
import { Verdict } from "../../src/types/CF/Submission";
import { StorageService } from "../../src/util/StorageService";
import Theme, { ThemesType } from "../../src/util/Theme";
import { createSubmission, seedProblemFixtures } from "../support/problemFixtures";

beforeEach(() => {
  resetFrontendMocks();
  localStorage.clear();
  seedProblemFixtures();
  const dates = [new Date(2025, 0, 1, 0, 1), new Date(2024, 1, 29, 23, 59), new Date(2023, 11, 31, 23, 59), new Date(2024, 0, 1, 0, 1), new Date(2024, 1, 29, 0, 1)];
  // Deliberately unordered, with two submissions on local leap day.
  frontend.submissions = dates.map((date, index) => createSubmission(index + 1, frontend.problems[0], Verdict.WRONG_ANSWER, date.getTime() / 1000));
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

function cells(svg: SVGSVGElement) { return svg.querySelectorAll("rect"); }
function select(value: string) {
  fireEvent.change(screen.getByRole("combobox", { name: "Select heatmap year" }), { target: { value } });
}

// Generated by Codex and not thoroughly checked for correctness.
test("All groups local year boundaries and leap day without reordering source submissions", () => {
  const ids = frontend.submissions.map((submission) => submission.id);
  const view = render(<SubmissionsHeatMap />);
  select("all");
  const svgs = view.container.querySelectorAll("svg");
  expect(svgs).toHaveLength(3);
  expect(cells(svgs[0])).toHaveLength(365);
  expect(cells(svgs[1])).toHaveLength(366);
  expect(cells(svgs[2])).toHaveLength(365);
  fireEvent.mouseEnter(cells(svgs[0])[364]);
  expect(screen.getByText("Sun Dec 31 2023: 1")).toBeDefined();
  fireEvent.mouseEnter(cells(svgs[1])[0]);
  expect(screen.getByText("Mon Jan 01 2024: 1")).toBeDefined();
  fireEvent.mouseEnter(cells(svgs[1])[59]);
  expect(screen.getByText("Thu Feb 29 2024: 2")).toBeDefined();
  fireEvent.mouseEnter(cells(svgs[2])[0]);
  expect(screen.getByText("Wed Jan 01 2025: 1")).toBeDefined();
  expect(frontend.submissions.map((submission) => submission.id)).toEqual(ids);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty dates display zero and leaving a cell removes its tooltip", () => {
  const view = render(<SubmissionsHeatMap />);
  select("2024");
  const svg = view.container.querySelector("svg")!;
  fireEvent.mouseEnter(cells(svg)[58]);
  expect(screen.getByText("Wed Feb 28 2024: 0")).toBeDefined();
  fireEvent.mouseLeave(cells(svg)[58]);
  expect(screen.queryByText("Wed Feb 28 2024: 0")).toBeNull();
  expect(cells(svg)[58].getAttribute("fill")).toBe("#c7c9d4");
  expect(cells(svg)[59].getAttribute("fill")).toBe("rgba(58, 74, 148, 0.4)");
});

// Generated by Codex and not thoroughly checked for correctness.
test("high daily counts saturate heatmap color instead of exceeding its maximum", () => {
  frontend.submissions = Array.from({ length: 7 }, (_, index) => createSubmission(index + 1, frontend.problems[0], Verdict.OK, new Date(2024, 1, 29, 12).getTime() / 1000));
  const view = render(<SubmissionsHeatMap />);
  expect(cells(view.container.querySelector("svg")!)[59].getAttribute("fill")).toBe("rgba(58, 74, 148, 1)");
  fireEvent.mouseEnter(cells(view.container.querySelector("svg")!)[59]);
  expect(screen.getByText("Thu Feb 29 2024: 7")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("defaults to newest year and lists year options newest first", () => {
  render(<SubmissionsHeatMap />);
  const input = screen.getByRole("combobox", { name: "Select heatmap year" }) as HTMLSelectElement;
  expect(input.value).toBe("2025");
  expect(within(input).getAllByRole("option").map((option) => option.textContent)).toEqual(["All", "2025", "2024", "2023"]);
  expect(StorageService.getObject(StorageService.Keys.Stats.SubmissionHeatMapYear, 0)).toBe(2025);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["2024", "all"])("selection %s persists and restores on remount", (year) => {
  const first = render(<SubmissionsHeatMap />);
  select(year);
  expect(StorageService.getObject(StorageService.Keys.Stats.SubmissionHeatMapYear, undefined)).toBe(year === "all" ? "all" : 2024);
  first.unmount();
  const second = render(<SubmissionsHeatMap />);
  expect((screen.getByRole("combobox", { name: "Select heatmap year" }) as HTMLSelectElement).value).toBe(year);
  expect(second.container.querySelectorAll("svg")).toHaveLength(year === "all" ? 3 : 1);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([2020, "invalid"])("unavailable saved year %s falls back to the newest available year", (year) => {
  StorageService.saveObject(StorageService.Keys.Stats.SubmissionHeatMapYear, year);
  render(<SubmissionsHeatMap />);
  expect((screen.getByRole("combobox", { name: "Select heatmap year" }) as HTMLSelectElement).value).toBe("2025");
  expect(StorageService.getObject(StorageService.Keys.Stats.SubmissionHeatMapYear, 0)).toBe(2025);
});

// Generated by Codex and not thoroughly checked for correctness.
test("changing handles removes an unavailable selected year and refreshes counts", () => {
  const view = render(<SubmissionsHeatMap />);
  select("2024");
  frontend.submissions = [createSubmission(10, frontend.problems[0], Verdict.OK, new Date(2026, 0, 1, 12).getTime() / 1000)];
  view.rerender(<SubmissionsHeatMap />);
  expect((screen.getByRole("combobox", { name: "Select heatmap year" }) as HTMLSelectElement).value).toBe("2026");
  expect(StorageService.getObject(StorageService.Keys.Stats.SubmissionHeatMapYear, 0)).toBe(2026);
  expect(view.container.querySelectorAll("svg")).toHaveLength(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty history has only All and no invalid calendar", () => {
  frontend.submissions = [];
  const view = render(<SubmissionsHeatMap />);
  const input = screen.getByRole("combobox", { name: "Select heatmap year" }) as HTMLSelectElement;
  expect(input.value).toBe("all");
  expect(within(input).getAllByRole("option")).toHaveLength(1);
  expect(view.container.querySelector("svg")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("heatmap responds to resize and theme changes with counts unchanged", () => {
  const originalWidth = window.innerWidth;
  const view = render(<SubmissionsHeatMap />);
  const resize = (width: number) => {
    Object.defineProperty(window, "innerWidth", { configurable: true, value: width });
    act(() => { window.dispatchEvent(new Event("resize")); });
  };
  try {
    resize(1440);
    expect(cells(view.container.querySelector("svg")!)[0].getAttribute("width")).toBe("13");
    resize(375);
    expect(cells(view.container.querySelector("svg")!)[0].getAttribute("width")).toBe("5");
    frontend.theme = new Theme(ThemesType.DARK);
    select("2024");
    expect(view.container.querySelector("svg text")!.classList.contains("text-light")).toBe(true);
    fireEvent.mouseEnter(cells(view.container.querySelector("svg")!)[59]);
    expect(screen.getByText("Thu Feb 29 2024: 2")).toBeDefined();
  } finally { resize(originalWidth); }
});
