import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import useStatPage from "../../src/components/stats/useStatPage";
import { SimpleVerdict, Verdict } from "../../src/types/CF/Submission";
import { seedStatisticsFixtures } from "../support/statisticsFixtures";
import { createSubmission } from "../support/problemFixtures";

beforeEach(() => { resetFrontendMocks(); localStorage.clear(); });
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("empty submissions produce empty groups and no data state", () => {
  const hook = renderHook(useStatPage);
  expect(hook.result.current.hasSubmissionData).toBe(false);
  expect(hook.result.current.submissionsByVerdict.size).toBe(0);
  expect(hook.result.current.problemIDsBySimpleVerdict.size).toBe(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("F1 counts all three acceptances and both rejected submissions", () => {
  seedStatisticsFixtures();
  const hook = renderHook(useStatPage);
  expect(hook.result.current.hasSubmissionData).toBe(true);
  expect(hook.result.current.submissionsByVerdict.get(Verdict.OK)?.map((submission) => submission.id)).toEqual([2, 3, 4]);
  expect(hook.result.current.submissionsByVerdict.get(Verdict.WRONG_ANSWER)?.map((submission) => submission.id)).toEqual([1, 5]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([false, true])("rated problems deduplicate with acceptance precedence even if order is reversed=%s", (reverse) => {
  seedStatisticsFixtures();
  if (reverse) frontend.submissions.reverse();
  const hook = renderHook(useStatPage);
  const groups = hook.result.current.problemIDsBySimpleVerdict;
  expect(groups.get(SimpleVerdict.SOLVED)?.get(800)).toEqual(new Set(["100A"]));
  expect(groups.get(SimpleVerdict.ATTEMPTED)?.get(800)?.size).toBe(0);
  expect(groups.get(SimpleVerdict.ATTEMPTED)?.get(1200)).toEqual(new Set(["100B"]));
  expect([...groups.get(SimpleVerdict.SOLVED)!.keys()]).toEqual([800]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("acceptances from another handle remove the same problem from attempted counts", () => {
  seedStatisticsFixtures();
  const accepted = createSubmission(6, frontend.problems[1], Verdict.OK, 600);
  accepted.author.members = [{ handle: "Petr" }];
  frontend.submissions.push(accepted);
  const hook = renderHook(useStatPage);
  expect(hook.result.current.problemIDsBySimpleVerdict.get(SimpleVerdict.ATTEMPTED)?.get(1200)?.size).toBe(0);
  expect(hook.result.current.problemIDsBySimpleVerdict.get(SimpleVerdict.SOLVED)?.get(1200)).toEqual(new Set(["100B"]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("statistics use raw submissions rather than shared-contest expansion", () => {
  seedStatisticsFixtures();
  frontend.rawSubmissions = [...frontend.submissions];
  const shared = createSubmission(2, frontend.problems[2], Verdict.OK, 200);
  shared.fromShared = true;
  frontend.submissions.push(shared);
  const hook = renderHook(useStatPage);
  expect(hook.result.current.submissionsByVerdict.get(Verdict.OK)).toHaveLength(3);
  expect(hook.result.current.problemIDsBySimpleVerdict.get(SimpleVerdict.SOLVED)?.has(1600)).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("statistics recalculate when handles change without mutating source submission order", () => {
  seedStatisticsFixtures();
  const originalIds = frontend.submissions.map((submission) => submission.id);
  const hook = renderHook(useStatPage);
  expect(frontend.submissions.map((submission) => submission.id)).toEqual(originalIds);
  frontend.submissions = [];
  hook.rerender();
  expect(hook.result.current.hasSubmissionData).toBe(false);
  expect(hook.result.current.submissionsByVerdict.size).toBe(0);
});
