import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import IndividualListPage from "../../src/components/list/individual-list/IndividualListPage";
import { seedProblemFixtures } from "../support/problemFixtures";

beforeEach(() => { resetFrontendMocks(); seedProblemFixtures(); });
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("individual list loading is replaced by a visible failure for missing or inaccessible lists", () => {
  frontend.individualListLoading = true;
  const view = render(<IndividualListPage listId={5} />);
  expect(screen.getByLabelText("three-dots-loading")).toBeDefined();
  frontend.individualListLoading = false;
  frontend.individualListError = { status: 404 };
  view.rerender(<IndividualListPage listId={5} />);
  expect(screen.getByRole("alert").textContent).toBe("Failed to load this list.");
  expect(screen.queryByRole("table")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty lists keep headers; unknown metadata preserves the problem ID and delete control", () => {
  frontend.individualList = { id: 5, userId: 1, name: "Practice", createdAt: "2026-01-01", items: [] };
  const view = render(<IndividualListPage listId={5} />);
  expect(screen.getAllByRole("row")).toHaveLength(1);
  frontend.individualList = { ...frontend.individualList, items: [
    { listId: 5, problemId: "100A", position: 0, createdAt: "2026-01-01" },
    { listId: 5, problemId: "missing", position: 1, createdAt: "2026-01-01" },
  ] };
  view.rerender(<IndividualListPage listId={5} />);
  expect(screen.getByText("Alpha Dynamic")).toBeDefined();
  expect(screen.getByText("missing")).toBeDefined();
  expect(screen.getByRole("button", { name: "Remove missing from list" })).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed item removal displays feedback without an unhandled rejection and allows retry", async () => {
  frontend.individualList = { id: 5, userId: 1, name: "Practice", createdAt: "2026-01-01", items: [
    { listId: 5, problemId: "100A", position: 0, createdAt: "2026-01-01" },
  ] };
  frontend.deleteProblemFromList.mockRejectedValueOnce(new Error("Remove denied"));
  render(<IndividualListPage listId={5} />);
  fireEvent.click(screen.getByRole("button", { name: "Remove 100A from list" }));
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("Remove denied"));
  expect(screen.getByText("100A")).toBeDefined();
  fireEvent.click(screen.getByRole("button", { name: "Remove 100A from list" }));
  await waitFor(() => expect(frontend.deleteProblemFromList).toHaveBeenCalledTimes(2));
  expect(frontend.deleteProblemFromList).toHaveBeenLastCalledWith(5, "100A");
});
