import "../support/spinnerMocks";
import { setupBackendMock, backendList } from "../support/backendMocks";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, afterEach, expect, test } from "vitest";
import { MemoryRouter } from "react-router";
import ListPage from "../../src/components/list/ListPage";
import { LocationProbe } from "../support/router";
let backend: ReturnType<typeof setupBackendMock>;
let name: string;
let removed: boolean;
beforeEach(() => {
  localStorage.clear(); backend = setupBackendMock(); name = "Practice"; removed = false;
  backend.fetchMock.mockImplementation(async input => {
    const request = new Request(input); backend.requests.push(request);
    if (request.method === "PUT") name = (await request.json()).name;
    if (request.method === "DELETE") removed = true;
    if (new URL(request.url).pathname === "/lists") return Response.json({ lists: removed ? [] : [{ ...backendList, name }] });
    return Response.json({ list: { ...backendList, name }, items: [] });
  });
});
afterEach(() => { cleanup(); backend.dispose(); localStorage.clear(); });
function page() { render(<MemoryRouter initialEntries={["/lists?listId=5"]}><ListPage /><LocationProbe /></MemoryRouter>, { wrapper: backend.wrapper }); }

// Generated by Codex and not thoroughly checked for correctness.
test("real list queries, rename invalidation and deletion keep visible selection in sync", async () => {
  page(); await screen.findByRole("button", { name: "Practice" });
  fireEvent.click(screen.getByRole("button", { name: "Edit list" }));
  fireEvent.change(screen.getByLabelText("Enter New Name"), { target: { value: "Renamed" } });
  fireEvent.click(screen.getByRole("button", { name: "Update List" }));
  await screen.findByRole("button", { name: "Renamed" });
  await waitFor(() => expect(screen.queryByLabelText("Enter New Name")).toBeNull());
  fireEvent.click(screen.getByRole("button", { name: "Edit list" }));
  fireEvent.click(screen.getByRole("button", { name: "Delete list" }));
  fireEvent.click(screen.getByRole("button", { name: "Yes" }));
  await waitFor(() => expect(screen.queryByRole("button", { name: "Add Problem" })).toBeNull());
  await waitFor(() => expect(screen.getByTestId("location").textContent).toBe("/lists"));
  expect(backend.requests.some(request => request.method === "PUT")).toBe(true);
  expect(backend.requests.some(request => request.method === "DELETE")).toBe(true);
});
