import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import ListPage from "../../src/components/list/ListPage";
import { createRouterWrapper, LocationProbe } from "../support/router";

beforeEach(() => {
  resetFrontendMocks();
  frontend.lists = [{ id: 5, userId: 1, name: "Practice", createdAt: "2026-01-01", items: [] }];
  frontend.individualList = frontend.lists[0];
});
afterEach(cleanup);
function page(entry = "/lists?listId=5&keep=yes") {
  return render(<><ListPage /><LocationProbe /></>, { wrapper: createRouterWrapper(entry) });
}
function openCreate() { fireEvent.click(screen.getByRole("button", { name: "Create new list" })); }
function openRename() { fireEvent.click(screen.getByRole("button", { name: "Edit list" })); }
function openDelete() { openRename(); fireEvent.click(screen.getByRole("button", { name: "Delete list" })); }

// Generated by Codex and not thoroughly checked for correctness.
test("empty collections render without selected-list actions", () => {
  frontend.lists = [];
  page("/lists");
  expect(screen.queryByRole("button", { name: "Add Problem" })).toBeNull();
  expect(screen.queryByRole("table")).toBeNull();
  expect(screen.getByRole("button", { name: "Create new list" })).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("collection loading and failures are visible", () => {
  frontend.listsLoading = true;
  const view = page();
  expect(screen.getByLabelText("three-dots-loading")).toBeDefined();
  frontend.listsLoading = false;
  frontend.listsError = { status: 401 };
  frontend.lists = [];
  view.rerender(<><ListPage /><LocationProbe /></>);
  expect(screen.getByRole("alert").textContent).toBe("Failed to load lists.");
  expect(screen.queryByLabelText("three-dots-loading")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("creating a Unicode list submits its name and closes on success", async () => {
  page("/lists"); openCreate();
  fireEvent.change(screen.getByLabelText("List Name"), { target: { value: "練習 list" } });
  fireEvent.click(screen.getByRole("button", { name: "Create List" }));
  await waitFor(() => expect(screen.queryByLabelText("List Name")).toBeNull());
  expect(frontend.createList).toHaveBeenCalledExactlyOnceWith("練習 list");
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed creation preserves the dialog and entered name for retry", async () => {
  frontend.createList.mockRejectedValueOnce(new Error("Duplicate name"));
  page("/lists"); openCreate();
  fireEvent.change(screen.getByLabelText("List Name"), { target: { value: "Practice" } });
  fireEvent.click(screen.getByRole("button", { name: "Create List" }));
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("Duplicate name"));
  expect((screen.getByLabelText("List Name") as HTMLInputElement).value).toBe("Practice");
  fireEvent.click(screen.getByRole("button", { name: "Create List" }));
  await waitFor(() => expect(screen.queryByLabelText("List Name")).toBeNull());
  expect(frontend.createList).toHaveBeenCalledTimes(2);
});

// Generated by Codex and not thoroughly checked for correctness.
test("renaming submits the selected ID and closes on success", async () => {
  page(); openRename();
  expect((screen.getByLabelText("Enter New Name") as HTMLInputElement).value).toBe("Practice");
  fireEvent.change(screen.getByLabelText("Enter New Name"), { target: { value: "Renamed" } });
  fireEvent.click(screen.getByRole("button", { name: "Update List" }));
  await waitFor(() => expect(screen.queryByLabelText("Enter New Name")).toBeNull());
  expect(frontend.updateListName).toHaveBeenCalledExactlyOnceWith(5, "Renamed");
});

// Generated by Codex and not thoroughly checked for correctness.
test("rename failures preserve edited text and allow retry", async () => {
  frontend.updateListName.mockRejectedValueOnce(new Error("Rename denied"));
  page(); openRename();
  fireEvent.change(screen.getByLabelText("Enter New Name"), { target: { value: "Retry name" } });
  fireEvent.click(screen.getByRole("button", { name: "Update List" }));
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("Rename denied"));
  expect((screen.getByLabelText("Enter New Name") as HTMLInputElement).value).toBe("Retry name");
  fireEvent.click(screen.getByRole("button", { name: "Update List" }));
  await waitFor(() => expect(screen.queryByLabelText("Enter New Name")).toBeNull());
});

// Generated by Codex and not thoroughly checked for correctness.
test("canceling deletion preserves the selected list without sending a mutation", async () => {
  page(); openDelete();
  fireEvent.click(screen.getByRole("button", { name: "No" }));
  await waitFor(() => expect(screen.queryByRole("button", { name: "Yes" })).toBeNull());
  expect(frontend.deleteList).not.toHaveBeenCalled();
  expect(screen.getByTestId("location").textContent).toBe("/lists?listId=5&keep=yes");
  expect(screen.getByLabelText("Enter New Name")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("confirmed deletion clears the selected content and preserves unrelated URL parameters", async () => {
  page(); openDelete();
  fireEvent.click(screen.getByRole("button", { name: "Yes" }));
  await waitFor(() => expect(screen.queryByRole("button", { name: "Add Problem" })).toBeNull());
  expect(frontend.deleteList).toHaveBeenCalledExactlyOnceWith(5);
  expect(screen.getByTestId("location").textContent).toBe("/lists?keep=yes");
  expect(screen.queryByRole("table")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed deletion keeps its confirmation open and selection intact for retry", async () => {
  frontend.deleteList.mockRejectedValueOnce(new Error("Delete denied"));
  page(); openDelete();
  fireEvent.click(screen.getByRole("button", { name: "Yes" }));
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("Delete denied"));
  expect(screen.getByRole("button", { name: "Yes" })).toBeDefined();
  expect(screen.getByTestId("location").textContent).toContain("listId=5");
  fireEvent.click(screen.getByRole("button", { name: "Yes" }));
  await waitFor(() => expect(screen.getByTestId("location").textContent).toBe("/lists?keep=yes"));
});
