import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import { useNavigate } from "react-router";
import useProblemPage from "../../src/components/problem/useProblemPage";
import { seedProblemFixtures } from "../support/problemFixtures";
import { createRouterWrapper } from "../support/router";
import type { ListWithItem } from "../../src/types/list";

const list: ListWithItem = { id: 5, userId: 1, name: "Practice", createdAt: "2026-01-01", items: [
  { listId: 5, problemId: "100A", position: 4, createdAt: "2026-01-01" },
] };
beforeEach(() => {
  resetFrontendMocks(); localStorage.clear(); seedProblemFixtures();
  frontend.getListWithItems.mockResolvedValue(list);
});
afterEach(() => { cleanup(); localStorage.clear(); });
function setup(entry = "/problems?listId=5&useFilterStorage=false") {
  return renderHook(() => ({ page: useProblemPage(), navigate: useNavigate() }), { wrapper: createRouterWrapper(entry) });
}

// Generated by Codex and not thoroughly checked for correctness.
test("list item controls initialize from membership and append after the highest existing position", async () => {
  const hook = setup();
  await waitFor(() => expect(hook.result.current.page.problemsAddedToList.has("100A")).toBe(true));
  await act(async () => { await hook.result.current.page.addProblemToList("100B"); });
  expect(frontend.addProblemToList).toHaveBeenCalledExactlyOnceWith(5, "100B", 5);
  expect([...hook.result.current.page.problemsAddedToList]).toEqual(["100A", "100B"]);
  await act(async () => { await hook.result.current.page.deleteProblemFromList("100A"); });
  expect(frontend.deleteProblemFromList).toHaveBeenCalledExactlyOnceWith(5, "100A");
  expect([...hook.result.current.page.problemsAddedToList]).toEqual(["100B"]);
  expect(hook.result.current.page.list?.items.map(item => item.problemId)).toEqual(["100B"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("concurrent additions reserve distinct positions and preserve both membership updates", async () => {
  const hook = setup();
  await waitFor(() => expect(hook.result.current.page.list?.id).toBe(5));
  await act(async () => { await Promise.all([
    hook.result.current.page.addProblemToList("100B"), hook.result.current.page.addProblemToList("101A"),
  ]); });
  expect(frontend.addProblemToList.mock.calls).toEqual([[5, "100B", 5], [5, "101A", 6]]);
  expect([...hook.result.current.page.problemsAddedToList]).toEqual(["100A", "100B", "101A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("duplicate clicks and already present problems do not create duplicate requests or items", async () => {
  const hook = setup();
  await waitFor(() => expect(hook.result.current.page.list?.id).toBe(5));
  await act(async () => { await Promise.all([
    hook.result.current.page.addProblemToList("100A"),
    hook.result.current.page.addProblemToList("100B"), hook.result.current.page.addProblemToList("100B"),
  ]); });
  expect(frontend.addProblemToList).toHaveBeenCalledExactlyOnceWith(5, "100B", 5);
  expect(hook.result.current.page.list?.items.map(item => item.problemId)).toEqual(["100A", "100B"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed item mutations preserve membership and remain retryable", async () => {
  const hook = setup();
  await waitFor(() => expect(hook.result.current.page.list?.id).toBe(5));
  frontend.addProblemToList.mockRejectedValueOnce(new Error("Add denied"));
  frontend.deleteProblemFromList.mockRejectedValueOnce(new Error("Remove denied"));
  await act(async () => {
    await expect(hook.result.current.page.addProblemToList("100B")).rejects.toThrow("Add denied");
    await expect(hook.result.current.page.deleteProblemFromList("100A")).rejects.toThrow("Remove denied");
  });
  expect([...hook.result.current.page.problemsAddedToList]).toEqual(["100A"]);
  await act(async () => { await hook.result.current.page.addProblemToList("100B"); });
  expect(hook.result.current.page.problemsAddedToList.has("100B")).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("superseded list responses cannot overwrite the new list and leaving list mode clears membership", async () => {
  let resolveOld!: (value: ListWithItem) => void;
  frontend.getListWithItems.mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve; }));
  frontend.getListWithItems.mockResolvedValueOnce({ ...list, id: 6, name: "Second", items: [] });
  const hook = setup();
  act(() => { void hook.result.current.navigate("/problems?listId=6&useFilterStorage=false"); });
  await waitFor(() => expect(hook.result.current.page.list?.id).toBe(6));
  await act(async () => { resolveOld(list); });
  expect(hook.result.current.page.list?.id).toBe(6);
  expect([...hook.result.current.page.problemsAddedToList]).toEqual([]);
  act(() => { void hook.result.current.navigate("/problems?useFilterStorage=false"); });
  expect(hook.result.current.page.showAddToList).toBe(false);
  expect(hook.result.current.page.list).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("failed list retrieval reports its error and leaves membership empty", async () => {
  frontend.getListWithItems.mockRejectedValue(new Error("List unavailable"));
  const hook = setup();
  await waitFor(() => expect(frontend.showErrorToast).toHaveBeenCalledWith("List unavailable"));
  expect(hook.result.current.page.list).toBeUndefined();
  expect([...hook.result.current.page.problemsAddedToList]).toEqual([]);
});
