import { backendItem, backendList, listApi, setupBackendMock } from "../support/backendMocks";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import useListApi from "../../src/data/hooks/useListApi";
import { StorageService } from "../../src/util/StorageService";

let backend: ReturnType<typeof setupBackendMock>;
beforeEach(() => { localStorage.clear(); backend = setupBackendMock(); vi.spyOn(console, "log").mockImplementation(() => {}); });
afterEach(() => { cleanup(); backend.dispose(); localStorage.clear(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("collection queries map backend fields and send the stored bearer token", async () => {
  StorageService.setJWTToken("test-session");
  backend.respond({ lists: [backendList] });
  const result = await backend.store.dispatch(listApi.endpoints.getAllLists.initiate()).unwrap();
  expect(result).toEqual([{ id: 5, userId: 7, name: "Practice", createdAt: "2026-01-01" }]);
  expect(backend.requests[0].headers.get("Authorization")).toBe("Bearer test-session");
  expect(backend.requests[0].credentials).toBe("include");
  expect(new URL(backend.requests[0].url).pathname).toBe("/lists");
});

// Generated by Codex and not thoroughly checked for correctness.
test("individual lists sort by position, date, then problem ID without losing sparse positions", async () => {
  backend.respond({ list: backendList, items: [
    { ...backendItem, problem_id: "101A", position: 9 },
    { ...backendItem, problem_id: "100B" },
    { ...backendItem, problem_id: "99A", created_at: "2025-12-31" }, backendItem,
  ] });
  const hook = renderHook(useListApi, { wrapper: backend.wrapper });
  await act(async () => {
    const list = await hook.result.current.getListWithItems(5);
    expect(list.items.map(item => item.problemId)).toEqual(["99A", "100A", "100B", "101A"]);
    expect(list.items[3]).toEqual({ listId: 5, problemId: "101A", position: 9, createdAt: "2026-01-02" });
    expect(list.name).toBe("Practice");
  });
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([{ items: [] }, { items: [backendItem] }])("empty and populated individual lists preserve their item count", async ({ items }) => {
  backend.respond({ list: backendList, items });
  const list = await backend.store.dispatch(listApi.endpoints.getList.initiate(5)).unwrap();
  expect(list.items).toHaveLength(items.length);
});

const operations = [
  { name: "create", method: "POST", path: "/lists", body: { name: "練習 list" }, response: { list: backendList }, invoke: (api: ReturnType<typeof useListApi>) => api.createList("練習 list"), fallback: "Failed to create a list!" },
  { name: "rename", method: "PUT", path: "/lists/5", body: { name: "Renamed" }, response: {}, invoke: (api: ReturnType<typeof useListApi>) => api.updateListName(5, "Renamed"), fallback: "Failed to update the list!" },
  { name: "delete", method: "DELETE", path: "/lists/5", body: undefined, response: {}, invoke: (api: ReturnType<typeof useListApi>) => api.deleteList(5), fallback: "Failed to delete the list!" },
  { name: "add item", method: "PUT", path: "/lists/5/item", body: { problem_id: "100A", position: 2 }, response: { item: backendItem }, invoke: (api: ReturnType<typeof useListApi>) => api.addProblemToList(5, "100A", 2), fallback: "Failed to add to list!" },
  { name: "remove item", method: "DELETE", path: "/lists/5/item/100A", body: undefined, response: {}, invoke: (api: ReturnType<typeof useListApi>) => api.deleteProblemFromList(5, "100A"), fallback: "Failed to delete from list!" },
  { name: "read item list", method: "GET", path: "/lists/5", body: undefined, response: { list: backendList, items: [] }, invoke: (api: ReturnType<typeof useListApi>) => api.getListWithItems(5), fallback: "Couldn't find the list" },
];

// Generated by Codex and not thoroughly checked for correctness.
test.each(operations)("$name sends the correct method, route and body", async ({ invoke, response, method, path, body }) => {
  backend.respond(response);
  const hook = renderHook(useListApi, { wrapper: backend.wrapper });
  await act(async () => { await invoke(hook.result.current); });
  const request = backend.requests[0];
  expect(request.method).toBe(method);
  expect(new URL(request.url).pathname).toBe(path);
  if (body !== undefined) expect(await request.json()).toEqual(body);
  else expect(await request.text()).toBe("");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(operations)("$name exposes server rejection text and fallback errors", async ({ invoke, fallback }) => {
  const hook = renderHook(useListApi, { wrapper: backend.wrapper });
  backend.respond({ error: "Permission denied" }, 403);
  await act(async () => { await expect(invoke(hook.result.current)).rejects.toThrow("Permission denied"); });
  backend.respond({}, 500);
  await act(async () => { await expect(invoke(hook.result.current)).rejects.toThrow(fallback); });
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["create", "rename", "delete"])("%s refreshes the subscribed collection", async operation => {
  let created = false;
  backend.fetchMock.mockImplementation(async input => {
    const request = new Request(input);
    backend.requests.push(request);
    if (request.method !== "GET") { created = true; return Response.json({ list: backendList }); }
    return Response.json({ lists: created ? (operation === "delete" ? [] : [{ ...backendList, name: "Updated" }]) : [backendList] });
  });
  const hook = renderHook(() => { const api = useListApi(); return { api, collection: api.useGetAllListsQuery() }; }, { wrapper: backend.wrapper });
  await waitFor(() => expect(hook.result.current.collection.data?.[0].name).toBe("Practice"));
  await act(async () => {
    if (operation === "create") await hook.result.current.api.createList("Updated");
    else if (operation === "rename") await hook.result.current.api.updateListName(5, "Updated");
    else await hook.result.current.api.deleteList(5);
  });
  await waitFor(() => {
    if (operation === "delete") expect(hook.result.current.collection.data).toEqual([]);
    else expect(hook.result.current.collection.data?.[0].name).toBe("Updated");
  });
});

// Generated by Codex and not thoroughly checked for correctness.
test("item mutations refresh the subscribed individual list", async () => {
  let items: typeof backendItem[] = [];
  backend.fetchMock.mockImplementation(async input => {
    const request = new Request(input);
    backend.requests.push(request);
    if (request.method === "PUT") { items = [backendItem]; return Response.json({ item: backendItem }); }
    if (request.method === "DELETE") { items = []; return Response.json({}); }
    return Response.json({ list: backendList, items });
  });
  const hook = renderHook(() => { const api = useListApi(); return { api, list: api.useGetListQuery(5) }; }, { wrapper: backend.wrapper });
  await waitFor(() => expect(hook.result.current.list.data?.items).toEqual([]));
  await act(async () => { await hook.result.current.api.addProblemToList(5, "100A", 2); });
  await waitFor(() => expect(hook.result.current.list.data?.items[0].problemId).toBe("100A"));
  await act(async () => { await hook.result.current.api.deleteProblemFromList(5, "100A"); });
  await waitFor(() => expect(hook.result.current.list.data?.items).toEqual([]));
});
