import { frontend, resetFrontendMocks } from "../support/frontendMocks";
// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { type PropsWithChildren } from "react";
import { act, cleanup, renderHook } from "@testing-library/react";
import { MemoryRouter, useLocation, useNavigate } from "react-router";
import { afterEach, beforeEach, expect, test } from "vitest";
import useListPage from "../../src/components/list/useListPage";
import { SearchKeys } from "../../src/util/constants";
import { Path } from "../../src/util/route/path";


beforeEach(() => {
  resetFrontendMocks();
  frontend.lists = [{ id: 5, userId: 1, name: "Test list", createdAt: "2026-01-01", items: [] }];
});

afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("adding a problem from a list opens URL-only filters", () => {
  const wrapper = ({ children }: PropsWithChildren) => <MemoryRouter>{children}</MemoryRouter>;
  const hook = renderHook(() => ({ list: useListPage(), location: useLocation() }), { wrapper });

  act(() => hook.result.current.list.listClicked("Test list"));
  act(() => hook.result.current.list.addButtonClicked());

  expect(hook.result.current.location.pathname).toBe(Path.PROBLEMS);
  const params = new URLSearchParams(hook.result.current.location.search);
  expect(params.get(SearchKeys.ListId)).toBe("5");
  expect(params.get(SearchKeys.UseFilterStorage)).toBe("false");
});

// Generated by Codex and not thoroughly checked for correctness.
test("deep links restore selection, renames refresh it, and removed lists clear stale content", () => {
  const wrapper = ({ children }: PropsWithChildren) => <MemoryRouter initialEntries={["/lists?listId=5&keep=yes"]}>{children}</MemoryRouter>;
  const hook = renderHook(useListPage, { wrapper });
  expect(hook.result.current.activeList?.name).toBe("Test list");
  frontend.lists = [{ ...frontend.lists[0], name: "Renamed" }];
  hook.rerender();
  expect(hook.result.current.activeList?.name).toBe("Renamed");
  frontend.lists = [];
  hook.rerender();
  expect(hook.result.current.activeList).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("list selection follows Back and Forward and preserves unrelated parameters", () => {
  frontend.lists.push({ id: 6, userId: 1, name: "Second", createdAt: "2026-01-01", items: [] });
  const wrapper = ({ children }: PropsWithChildren) => <MemoryRouter initialEntries={["/lists?listId=5&keep=yes"]}>{children}</MemoryRouter>;
  const hook = renderHook(() => ({ list: useListPage(), location: useLocation(), navigate: useNavigate() }), { wrapper });
  act(() => hook.result.current.list.listClicked("Second"));
  expect(hook.result.current.list.activeList?.id).toBe(6);
  expect(new URLSearchParams(hook.result.current.location.search).get("keep")).toBe("yes");
  act(() => { void hook.result.current.navigate(-1); });
  expect(hook.result.current.list.activeList?.id).toBe(5);
  act(() => { void hook.result.current.navigate(1); });
  expect(hook.result.current.list.activeList?.id).toBe(6);
});

// Generated by Codex and not thoroughly checked for correctness.
test("unknown list IDs do not select another user's or unrelated list", () => {
  const wrapper = ({ children }: PropsWithChildren) => <MemoryRouter initialEntries={["/lists?listId=999"]}>{children}</MemoryRouter>;
  const hook = renderHook(useListPage, { wrapper });
  expect(hook.result.current.activeList).toBeUndefined();
});
