// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { type PropsWithChildren } from "react";
import { act, cleanup, renderHook } from "@testing-library/react";
import { MemoryRouter, useLocation } from "react-router";
import { afterEach, expect, test, vi } from "vitest";
import useListPage from "../../src/components/list/useListPage";
import { SearchKeys } from "../../src/util/constants";
import { Path } from "../../src/util/route/path";

vi.mock("../../src/data/hooks/useTheme", () => ({ default: () => ({ theme: {} }) }));
vi.mock("../../src/data/hooks/useListApi", () => ({
  default: () => ({ useGetAllListsQuery: () => ({ data: [{ id: 5, name: "Test list" }] }) }),
}));

afterEach(cleanup);

test("adding a problem from a list opens URL-only filters", () => {
  const wrapper = ({ children }: PropsWithChildren) => <MemoryRouter>{children}</MemoryRouter>;
  const hook = renderHook(() => ({ list: useListPage(), location: useLocation() }), { wrapper });

  act(() => hook.result.current.list.listClicked("Test list"));
  act(() => hook.result.current.list.addButtonClicked());

  expect(hook.result.current.location.pathname).toBe(Path.PROBLEMS);
  const params = new URLSearchParams(hook.result.current.location.search);
  expect(params.get(SearchKeys.ListId)).toBe("5");
  expect(params.get(SearchKeys.UseFilterStorage)).toBe("false");
});
