import { frontend as data, resetFrontendMocks } from "../support/frontendMocks";
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { act, cleanup, render } from "@testing-library/react";
import { MemoryRouter, Route, Routes, useLocation, useNavigate, type NavigateFunction } from "react-router";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import useProblemPage from "../../src/components/problem/useProblemPage";
import useContestPage from "../../src/components/contest/useContestPage";
import Contest from "../../src/types/CF/Contest";
import Problem from "../../src/types/CF/Problem";
import { Verdict } from "../../src/types/CF/Submission";
import { StorageService } from "../../src/util/StorageService";
import { SearchKeys } from "../../src/util/constants";
import { Path } from "../../src/util/route/path";

function ProblemProbe() {
  page = useProblemPage();
  return null;
}

function ContestProbe() {
  contestPage = useContestPage();
  return null;
}

let page: ReturnType<typeof useProblemPage>;
let contestPage: ReturnType<typeof useContestPage>;
let navigate: NavigateFunction;
let location: ReturnType<typeof useLocation>;

function NavigationProbe() {
  navigate = useNavigate();
  location = useLocation();
  return null;
}

function TestApp({ initialEntry }: { initialEntry: string }) {
  return (
    <MemoryRouter initialEntries={[initialEntry]}>
      <NavigationProbe />
      <Routes>
        <Route path={Path.PROBLEMS} element={<ProblemProbe key="problems" />} />
        <Route path={Path.CONTESTS} element={<ContestProbe />} />
      </Routes>
    </MemoryRouter>
  );
}

const savedFilter = {
  minRating: 1200,
  maxRating: 1600,
  minContestId: 100,
  maxContestId: 200,
  tags: ["dp"],
  solveStatus: [Verdict.UNSOLVED],
  selected: 0,
  search: "saved",
};

beforeEach(() => {
  resetFrontendMocks();
  vi.useFakeTimers();
  localStorage.clear();
  StorageService.saveObject(StorageService.Keys.Problem.FilterV2, savedFilter);
  data.loading = false;
  data.contests = [100, 101].map((id) => {
    const contest = new Contest(id, `Codeforces Round ${id} (${id === 100 ? "one" : "two"}, Div. 2)`, "CF", "FINISHED", 7200, 1000);
    contest.count = 1;
    return contest;
  });
  data.problems = [
    new Problem(100, "A", "saved one", "PROGRAMMING", 1200, ["dp"]),
    new Problem(101, "A", "saved two", "PROGRAMMING", 1400, ["dp"]),
    new Problem(2, "A", "temporary", "PROGRAMMING", 800, []),
  ];
});
afterEach(() => {
  cleanup();
  vi.useRealTimers();
});


function randomPage(kind: "problem" | "contest") {
  return kind === "problem" ? {
    isRandomActive: page.isRandomActive,
    count: page.currentPageProblems.length,
    choose: page.setRandomProblem,
    updateSearch: (search: string) => page.updateFilter({ search }),
  } : {
    isRandomActive: contestPage.isRandomActive,
    count: contestPage.currentPageContests.length,
    choose: contestPage.setRandomContest,
    updateSearch: (search: string) => contestPage.updateFilter({ search }),
  };
}

function seedLegacyProblemFilters() {
  const { tags, solveStatus, selected, ...filter } = savedFilter;
  localStorage.removeItem(StorageService.Keys.Problem.FilterV2);
  StorageService.saveObject(StorageService.Keys.Problem.Filter, filter);
  StorageService.saveObject(StorageService.Keys.Problem.Tags, tags);
  StorageService.saveObject(StorageService.Keys.Problem.SolveStatus, solveStatus);
  StorageService.saveObject(StorageService.Keys.Problem.Page, selected);
}

// Generated by Codex and not thoroughly checked for correctness.
test("problem filters migrate before URL overrides are applied", () => {
  seedLegacyProblemFilters();
  render(<TestApp initialEntry={`/problems?${SearchKeys.Search}=url`} />, { reactStrictMode: true });
  expect(page.filter).toMatchObject({ ...savedFilter, search: "url" });
  expect(JSON.parse(localStorage.getItem(StorageService.Keys.Problem.FilterV2)!)).toEqual(savedFilter);
});

// Generated by Codex and not thoroughly checked for correctness.
test("URL-only filters defer migration until storage is enabled", async () => {
  seedLegacyProblemFilters();
  render(<TestApp initialEntry="/problems?useFilterStorage=false" />, { reactStrictMode: true });
  await act(async () => vi.advanceTimersByTimeAsync(300));
  expect(localStorage.getItem(StorageService.Keys.Problem.FilterV2)).toBeNull();
  await act(async () => navigate(Path.PROBLEMS));
  expect(page.filter).toMatchObject(savedFilter);
  expect(JSON.parse(localStorage.getItem(StorageService.Keys.Problem.FilterV2)!)).toEqual(savedFilter);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problem", "contest"] as const)("%s keeps the random flag through filter changes and cancels to its main page", async (kind) => {
  const mainPath = kind === "problem" ? Path.PROBLEMS : Path.CONTESTS;
  const randomPath = mainPath;
  render(<TestApp initialEntry={`${randomPath}?random=true&useFilterStorage=false`} />, { reactStrictMode: true });
  expect(randomPage(kind).isRandomActive).toBe(true);
  expect(randomPage(kind).count).toBe(1);
  expect(new URLSearchParams(location.search).get(SearchKeys.Random)).toBe("true");

  await act(async () => randomPage(kind).updateSearch("one"));
  expect(randomPage(kind).isRandomActive).toBe(true);
  expect(randomPage(kind).count).toBe(1);
  expect(new URLSearchParams(location.search).get(SearchKeys.Random)).toBe("true");

  await act(async () => randomPage(kind).updateSearch("no matching results"));
  expect(randomPage(kind).count).toBe(0);
  expect(new URLSearchParams(location.search).get(SearchKeys.Random)).toBe("true");
  await act(async () => randomPage(kind).updateSearch("one"));
  expect(randomPage(kind).isRandomActive).toBe(true);

  await act(async () => randomPage(kind).choose(undefined));
  expect(location.pathname).toBe(mainPath);
  expect(new URLSearchParams(location.search).has(SearchKeys.Random)).toBe(false);
  expect(randomPage(kind).isRandomActive).toBe(false);
  await act(async () => randomPage(kind).updateSearch("two"));
  expect(randomPage(kind).isRandomActive).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problem", "contest"] as const)("%s toolbar random selection is represented in the URL and can be cancelled", async (kind) => {
  const path = kind === "problem" ? Path.PROBLEMS : Path.CONTESTS;
  render(<TestApp initialEntry={path} />, { reactStrictMode: true });
  await act(async () => randomPage(kind).choose(0));
  expect(new URLSearchParams(location.search).get(SearchKeys.Random)).toBe("true");
  expect(randomPage(kind).count).toBe(1);
  await act(async () => randomPage(kind).choose(undefined));
  expect(location.pathname).toBe(path);
  expect(new URLSearchParams(location.search).has(SearchKeys.Random)).toBe(false);
  expect(randomPage(kind).isRandomActive).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("returning from temporary snapshot filters reloads saved preferences on the same route", async () => {
  render(<TestApp initialEntry="/problems?useFilterStorage=false&minContestId=2&maxContestId=2" />, { reactStrictMode: true });
  await act(async () => page.updateFilter({ search: "temporary" }));
  expect(StorageService.getObject(StorageService.Keys.Problem.FilterV2, {})).toEqual(savedFilter);
  await act(async () => navigate(Path.PROBLEMS));
  expect(page.filter).toMatchObject(savedFilter);
  await act(async () => page.updateFilter({ search: "updated" }));
  await act(async () => vi.advanceTimersByTimeAsync(300));
  expect(StorageService.getObject(StorageService.Keys.Problem.FilterV2, {})).toMatchObject({ ...savedFilter, search: "updated" });
});

// Generated by Codex and not thoroughly checked for correctness.
test("a defined storage key applies its latest value and disabling storage preserves state", async () => {
  render(<TestApp initialEntry="/problems?useFilterStorage=false&minContestId=2&maxContestId=2" />, { reactStrictMode: true });
  const latestFilter = { ...savedFilter, minRating: 1800, maxRating: 2000, search: "latest" };
  StorageService.saveObject(StorageService.Keys.Problem.FilterV2, latestFilter);
  const search = new URLSearchParams(location.search);
  search.set(SearchKeys.UseFilterStorage, "true");
  await act(async () => navigate({ search: search.toString() }));
  expect(page.filter).toMatchObject(latestFilter);
  expect(new URLSearchParams(location.search).get(SearchKeys.MinRating)).toBe("1800");
  expect(StorageService.getObject(StorageService.Keys.Problem.FilterV2, {})).toMatchObject(latestFilter);

  const updatedSearch = new URLSearchParams(location.search);
  updatedSearch.set(SearchKeys.UseFilterStorage, "false");
  await act(async () => navigate({ search: updatedSearch.toString() }));
  expect(page.filter).toMatchObject(latestFilter);
  expect(StorageService.getObject(StorageService.Keys.Problem.FilterV2, {})).toMatchObject(latestFilter);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["problem", "contest"] as const)("%s waits for data while keeping random mode in the URL", async (kind) => {
  data.loading = true;
  const path = kind === "problem" ? Path.PROBLEMS : Path.CONTESTS;
  const entry = `${path}?random=true&useFilterStorage=false`;
  const view = render(<TestApp initialEntry={entry} />, { reactStrictMode: true });
  expect(randomPage(kind).isRandomActive).toBe(false);
  expect(new URLSearchParams(location.search).get(SearchKeys.Random)).toBe("true");
  data.loading = false;
  view.rerender(<TestApp initialEntry={entry} />);
  expect(randomPage(kind).isRandomActive).toBe(true);
  expect(randomPage(kind).count).toBe(1);
});
