import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import usePersistentState from "../../src/hooks/usePersistentState";

beforeEach(() => localStorage.clear());
afterEach(() => { cleanup(); vi.restoreAllMocks(); localStorage.clear(); });

// Generated by Codex and not thoroughly checked for correctness.
test("persistent state restores stored values and functional updates survive remount", () => {
  localStorage.setItem("counter", "7");
  const hook = renderHook(() => usePersistentState("counter", 1));
  expect(hook.result.current[0]).toBe(7);
  act(() => hook.result.current[1](previous => previous + 2));
  expect(localStorage.getItem("counter")).toBe("9");
  hook.unmount();
  const restored = renderHook(() => usePersistentState("counter", 1));
  expect(restored.result.current[0]).toBe(9);
});

// Generated by Codex and not thoroughly checked for correctness.
test("initializer takes precedence over saved state and is not rerun by rerenders", () => {
  localStorage.setItem("counter", "7");
  const initialize = vi.fn(() => 3);
  const hook = renderHook(() => usePersistentState("counter", 1, initialize));
  hook.rerender();
  expect(initialize).toHaveBeenCalledTimes(1);
  expect(hook.result.current[0]).toBe(3);
  expect(localStorage.getItem("counter")).toBe("3");
});

// Generated by Codex and not thoroughly checked for correctness.
test("disabled persistence neither reads nor writes saved preferences", () => {
  localStorage.setItem("counter", "7");
  const read = vi.spyOn(Storage.prototype, "getItem");
  const write = vi.spyOn(Storage.prototype, "setItem");
  const hook = renderHook(() => usePersistentState("counter", 1, undefined, false));
  expect(hook.result.current[0]).toBe(1);
  act(() => hook.result.current[1](5));
  expect(read).not.toHaveBeenCalled();
  expect(write).not.toHaveBeenCalled();
  read.mockRestore();
  expect(localStorage.getItem("counter")).toBe("7");
});

// Generated by Codex and not thoroughly checked for correctness.
test("an initializer remains usable when persistence is disabled", () => {
  const write = vi.spyOn(Storage.prototype, "setItem");
  const hook = renderHook(() => usePersistentState("counter", 1, () => 4, false));
  expect(hook.result.current[0]).toBe(4);
  expect(write).not.toHaveBeenCalled();
});

// Generated by Codex and not thoroughly checked for correctness.
test("disabling persistence preserves saved state; reenabling saves current state", () => {
  const hook = renderHook(({ enabled }) => usePersistentState("counter", 1, undefined, enabled), { initialProps: { enabled: true } });
  hook.rerender({ enabled: false });
  act(() => hook.result.current[1](5));
  expect(localStorage.getItem("counter")).toBe("1");
  hook.rerender({ enabled: true });
  expect(localStorage.getItem("counter")).toBe("5");
});

// Generated by Codex and not thoroughly checked for correctness.
test("corrupt storage falls back to the default and subsequent updates repair it", () => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  localStorage.setItem("counter", "{invalid");
  const hook = renderHook(() => usePersistentState("counter", 1));
  expect(hook.result.current[0]).toBe(1);
  act(() => hook.result.current[1](2));
  expect(localStorage.getItem("counter")).toBe("2");
});

// Generated by Codex and not thoroughly checked for correctness.
test("blocked storage does not prevent in-memory updates", () => {
  vi.spyOn(console, "log").mockImplementation(() => {});
  vi.spyOn(Storage.prototype, "getItem").mockImplementation(() => { throw new DOMException("Blocked", "SecurityError"); });
  vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new DOMException("Full", "QuotaExceededError"); });
  const hook = renderHook(() => usePersistentState("counter", 1));
  act(() => hook.result.current[1](2));
  expect(hook.result.current[0]).toBe(2);
});
