import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, expect, test } from "vitest";
import { useLocation, useNavigate } from "react-router";
import useAppSearchParams from "../../src/hooks/useSearchParam";
import useAppNavigation from "../../src/hooks/useAppNavigation";
import { SearchKeys } from "../../src/util/constants";
import { Path } from "../../src/util/route/path";
import { createRouterWrapper } from "../support/router";

afterEach(cleanup);
function setup(entry = "/problems?q=old&keep=yes&keep=two") {
  return renderHook(() => ({ params: useAppSearchParams(), app: useAppNavigation(), location: useLocation(), navigate: useNavigate() }), { wrapper: createRouterWrapper(entry) });
}

// Generated by Codex and not thoroughly checked for correctness.
test("search getters distinguish absent values from present empty values", () => {
  const hook = setup("/problems?q=&page=0");
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBe("");
  expect(hook.result.current.params.getSearchParam(SearchKeys.ListId)).toBeUndefined();
  expect(hook.result.current.params.getSearchParams([SearchKeys.Search, SearchKeys.Page, SearchKeys.ListId])).toEqual(new Map([[SearchKeys.Search, ""], [SearchKeys.Page, "0"]]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("batched updates encode special text and preserve unrelated repeated keys", () => {
  const hook = setup();
  act(() => hook.result.current.params.updateSearchParams(new Map([[SearchKeys.Search, "dp + graphs & 漢字"], [SearchKeys.Page, "0"]])));
  const params = new URLSearchParams(hook.result.current.location.search);
  expect(params.get(SearchKeys.Search)).toBe("dp + graphs & 漢字");
  expect(params.get(SearchKeys.Page)).toBe("0");
  expect(params.getAll("keep")).toEqual(["yes", "two"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("multiple batched writes in the same event preserve both updates", () => {
  const hook = setup();
  act(() => {
    hook.result.current.params.updateSearchParams(new Map([[SearchKeys.Page, "2"]]));
    hook.result.current.params.updateSearchParams(new Map([[SearchKeys.Search, undefined]]));
  });
  const params = new URLSearchParams(hook.result.current.location.search);
  expect(params.get(SearchKeys.Page)).toBe("2");
  expect(params.has(SearchKeys.Search)).toBe(false);
  expect(params.getAll("keep")).toEqual(["yes", "two"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("push updates and deletion follow Back and Forward history", () => {
  const hook = setup();
  act(() => hook.result.current.params.updateSearchParam(SearchKeys.Page, "2"));
  act(() => hook.result.current.params.deleteSearchParam(SearchKeys.Search));
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBeUndefined();
  act(() => { void hook.result.current.navigate(-1); });
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBe("old");
  expect(hook.result.current.params.getSearchParam(SearchKeys.Page)).toBe("2");
  act(() => { void hook.result.current.navigate(1); });
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("batched normalization replaces its history entry", () => {
  const hook = setup();
  act(() => { void hook.result.current.navigate("/problems?q=new&keep=yes"); });
  act(() => hook.result.current.params.updateSearchParams(new Map([[SearchKeys.Page, "2"]])));
  act(() => { void hook.result.current.navigate(-1); });
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBe("old");
  expect(hook.result.current.params.getSearchParam(SearchKeys.Page)).toBeUndefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("consuming temporary keys preserves unrelated URL state and replaces history", () => {
  const hook = setup();
  act(() => { void hook.result.current.navigate("/problems?random=true&listId=5&q=keep"); });
  act(() => hook.result.current.params.consumeSearchParams([SearchKeys.Random, SearchKeys.ListId]));
  expect(hook.result.current.params.getSearchParam(SearchKeys.Random)).toBeUndefined();
  expect(hook.result.current.params.getSearchParam(SearchKeys.ListId)).toBeUndefined();
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBe("keep");
  act(() => { void hook.result.current.navigate(-1); });
  expect(hook.result.current.params.getSearchParam(SearchKeys.Search)).toBe("old");
});

// Generated by Codex and not thoroughly checked for correctness.
test("navigation preserves explicit zero/false/text and omits absent values", () => {
  const hook = setup();
  act(() => hook.result.current.app.navigateTo(Path.CONTESTS, { [SearchKeys.Page]: 0, [SearchKeys.Random]: false, [SearchKeys.Search]: "dp & +", [SearchKeys.ListId]: undefined }));
  const params = new URLSearchParams(hook.result.current.location.search);
  expect(hook.result.current.app.pathName).toBe(Path.CONTESTS);
  expect(params.get(SearchKeys.Page)).toBe("0");
  expect(params.get(SearchKeys.Random)).toBe("false");
  expect(params.get(SearchKeys.Search)).toBe("dp & +");
  expect(params.has(SearchKeys.ListId)).toBe(false);
  expect(params.has("keep")).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([undefined, {}])("navigation without destination parameters clears old query state (%j)", params => {
  const hook = setup();
  act(() => hook.result.current.app.navigateTo(Path.Home, params));
  expect(hook.result.current.location.pathname).toBe(Path.Home);
  expect(hook.result.current.location.search).toBe("");
});
