// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { act, cleanup, renderHook } from "@testing-library/react";
import { useLocation, useNavigate } from "react-router";
import { afterEach, expect, test, vi } from "vitest";
import useSearchParamState from "../../src/hooks/useSearchParamState";
import { SearchKeys } from "../../src/util/constants";
import { isPlainObject } from "../../src/util/util";
import { validators } from "../../src/util/validators";

afterEach(cleanup);

import { createRouterWrapper } from "../support/router";

test.each([SearchKeys.Page, undefined])("missing values stay undefined for key %s", (searchKey) => {
  const validator = vi.fn(() => 7);
  const hook = renderHook(() => useSearchParamState<number>(searchKey, validator), {
    wrapper: createRouterWrapper("/"),
  });

  expect(hook.result.current[0]).toBeUndefined();
  expect(validator).not.toHaveBeenCalled();
});

test("validates URL values reactively and can remove only its own key", () => {
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<number>(
      SearchKeys.Page,
      validators.nonNegativeInteger,
    );
    return { value, setValue, navigate: useNavigate(), search: useLocation().search };
  }, { wrapper: createRouterWrapper(`/?${SearchKeys.Page}=7&${SearchKeys.Search}=keep`) });

  expect(hook.result.current.value).toBe(7);
  act(() => hook.result.current.navigate(`?${SearchKeys.Page}=invalid&${SearchKeys.Search}=keep`));
  expect(hook.result.current.value).toBeUndefined();

  act(() => hook.result.current.setValue(12));
  expect(hook.result.current.value).toBe(12);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Page)).toBe("12");

  act(() => hook.result.current.setValue(undefined));
  expect(hook.result.current.value).toBeUndefined();
  expect(new URLSearchParams(hook.result.current.search).has(SearchKeys.Page)).toBe(false);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Search)).toBe("keep");
});

test("passes only present record properties to the validator", () => {
  interface Filter {
    page?: number;
    search?: string;
  }
  const validator = {
    page: validators.nonNegativeInteger,
    search: validators.optionalString,
  };
  const hook = renderHook(() => useSearchParamState<Filter>(
    { page: SearchKeys.Page, search: SearchKeys.Search },
    validator,
  ), { wrapper: createRouterWrapper(`/?${SearchKeys.Page}=7`) });

  expect(hook.result.current[0]).toStrictEqual({ page: 7, search: undefined });
});

test.each([
  [JSON.stringify({ page: 7 }), { page: 7 }],
  ["{invalid", undefined],
])("validates JSON objects from a single key: %s", (input, expected) => {
  const hook = renderHook(() => useSearchParamState<Record<string, unknown>>(
    SearchKeys.Search,
    (value, defaultValue) => isPlainObject(value) ? value : defaultValue,
  ), { wrapper: createRouterWrapper(`/?${SearchKeys.Search}=${encodeURIComponent(String(input))}`) });

  expect(hook.result.current[0]).toEqual(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test("array serialization encodes special tags and distinguishes empty selections from absent state", () => {
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<string[]>(SearchKeys.Tags, validators.stringArray);
    return { value, setValue, search: useLocation().search };
  }, { wrapper: createRouterWrapper("/problems?keep=yes") });
  act(() => hook.result.current.setValue(["dp", "graphs & trees", "漢字"]));
  expect(hook.result.current.value).toEqual(["dp", "graphs & trees", "漢字"]);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Tags)).toBe("dp,graphs & trees,漢字");
  act(() => hook.result.current.setValue([]));
  expect(hook.result.current.value).toEqual([]);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Tags)).toBe("");
  act(() => hook.result.current.setValue(undefined));
  expect(new URLSearchParams(hook.result.current.search).has(SearchKeys.Tags)).toBe(false);
  expect(new URLSearchParams(hook.result.current.search).get("keep")).toBe("yes");
});

// Generated by Codex and not thoroughly checked for correctness.
test("Set serialization round-trips membership in insertion order", () => {
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<Set<string>>(SearchKeys.Tags, (input, fallback) => {
      const values = validators.stringArray(input, undefined);
      return values === undefined ? fallback : new Set(values);
    });
    return { value, setValue, search: useLocation().search };
  }, { wrapper: createRouterWrapper("/problems") });
  act(() => hook.result.current.setValue(new Set(["graphs", "dp"])));
  expect(hook.result.current.value).toEqual(new Set(["graphs", "dp"]));
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Tags)).toBe("graphs,dp");
});

// Generated by Codex and not thoroughly checked for correctness.
test("JSON object serialization preserves nested false, zero and Unicode strings", () => {
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<Record<string, unknown>>(SearchKeys.Search, (value, fallback) => isPlainObject(value) ? value : fallback);
    return { value, setValue, search: useLocation().search };
  }, { wrapper: createRouterWrapper("/problems?keep=yes") });
  const expected = { page: 0, enabled: false, nested: { text: "漢字 & +" } };
  act(() => hook.result.current.setValue(expected));
  expect(hook.result.current.value).toEqual(expected);
  expect(JSON.parse(new URLSearchParams(hook.result.current.search).get(SearchKeys.Search)!)).toEqual(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test("record setters clear optional dates and update all keys without deleting unrelated parameters", () => {
  type Filter = { date?: string; page: number; enabled: boolean };
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<Filter>(
      { date: SearchKeys.MinContestDate, page: SearchKeys.Page, enabled: SearchKeys.ShowUnrated },
      { date: validators.date, page: validators.nonNegativeInteger, enabled: validators.boolean },
    );
    return { value, setValue, search: useLocation().search };
  }, { wrapper: createRouterWrapper("/problems?minContestDate=2026-01-01&keep=yes") });
  act(() => hook.result.current.setValue({ date: undefined, page: 0, enabled: false }));
  expect(hook.result.current.value).toStrictEqual({ date: undefined, page: 0, enabled: false });
  const params = new URLSearchParams(hook.result.current.search);
  expect(params.has(SearchKeys.MinContestDate)).toBe(false);
  expect(params.get(SearchKeys.Page)).toBe("0");
  expect(params.get(SearchKeys.ShowUnrated)).toBe("false");
  expect(params.get("keep")).toBe("yes");
  act(() => hook.result.current.setValue(undefined));
  expect(hook.result.current.search).toBe("?keep=yes");
});
