// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { type PropsWithChildren } from "react";
import { act, cleanup, renderHook } from "@testing-library/react";
import { MemoryRouter, useLocation, useNavigate } from "react-router";
import { afterEach, expect, test, vi } from "vitest";
import useSearchParamState from "../../src/hooks/useSearchParamState";
import { SearchKeys } from "../../src/util/constants";
import { isPlainObject } from "../../src/util/util";
import { validators } from "../../src/util/validators";

afterEach(cleanup);

function createRouterWrapper(initialEntry: string) {
  return function RouterWrapper({ children }: PropsWithChildren) {
    return <MemoryRouter initialEntries={[initialEntry]}>{children}</MemoryRouter>;
  };
}

test.each([SearchKeys.Page, undefined])("missing values stay undefined for key %s", (searchKey) => {
  const validator = vi.fn(() => 7);
  const hook = renderHook(() => useSearchParamState<number>(searchKey, validator), {
    wrapper: createRouterWrapper("/"),
  });

  expect(hook.result.current[0]).toBeUndefined();
  expect(validator).not.toHaveBeenCalled();
});

test("validates URL values reactively and can remove only its own key", () => {
  const hook = renderHook(() => {
    const [value, setValue] = useSearchParamState<number>(
      SearchKeys.Page,
      validators.nonNegativeInteger,
    );
    return { value, setValue, navigate: useNavigate(), search: useLocation().search };
  }, { wrapper: createRouterWrapper(`/?${SearchKeys.Page}=7&${SearchKeys.Search}=keep`) });

  expect(hook.result.current.value).toBe(7);
  act(() => hook.result.current.navigate(`?${SearchKeys.Page}=invalid&${SearchKeys.Search}=keep`));
  expect(hook.result.current.value).toBeUndefined();

  act(() => hook.result.current.setValue(12));
  expect(hook.result.current.value).toBe(12);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Page)).toBe("12");

  act(() => hook.result.current.setValue(undefined));
  expect(hook.result.current.value).toBeUndefined();
  expect(new URLSearchParams(hook.result.current.search).has(SearchKeys.Page)).toBe(false);
  expect(new URLSearchParams(hook.result.current.search).get(SearchKeys.Search)).toBe("keep");
});

test("passes only present record properties to the validator", () => {
  interface Filter {
    page?: number;
    search?: string;
  }
  const validator = {
    page: validators.nonNegativeInteger,
    search: validators.optionalString,
  };
  const hook = renderHook(() => useSearchParamState<Filter>(
    { page: SearchKeys.Page, search: SearchKeys.Search },
    validator,
  ), { wrapper: createRouterWrapper(`/?${SearchKeys.Page}=7`) });

  expect(hook.result.current[0]).toStrictEqual({ page: 7, search: undefined });
});

test.each([
  [JSON.stringify({ page: 7 }), { page: 7 }],
  ["{invalid", undefined],
])("validates JSON objects from a single key: %s", (input, expected) => {
  const hook = renderHook(() => useSearchParamState<Record<string, unknown>>(
    SearchKeys.Search,
    (value, defaultValue) => isPlainObject(value) ? value : defaultValue,
  ), { wrapper: createRouterWrapper(`/?${SearchKeys.Search}=${encodeURIComponent(String(input))}`) });

  expect(hook.result.current[0]).toEqual(expected);
});
