import { StrictMode } from "react";
import { cleanup, render } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import D3CalendarHeatMap from "../../../../src/components/common/charts/heat-maps/D3CalendarHeatMap";

beforeEach(() => vi.spyOn(console, "log").mockImplementation(() => {}));
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const days = [
  { date: new Date(2024, 0, 1), value: 0 },
  { date: new Date(2024, 0, 7), value: 8 },
];

// Generated by Codex and not thoroughly checked for correctness.
test("D3 renders dated cells at Sunday-start week coordinates with twelve month labels", () => {
  const view = render(<D3CalendarHeatMap data={days} />);
  const svg = view.container.querySelector("svg")!;
  const cells = svg.querySelectorAll("rect.day-cell");
  expect(svg.getAttribute("width")).toBe("800"); expect(svg.getAttribute("height")).toBe("200");
  expect(cells).toHaveLength(2);
  expect(cells[0].getAttribute("x")).toBe("0"); expect(cells[0].getAttribute("y")).toBe("20");
  expect(cells[1].getAttribute("x")).toBe("20"); expect(cells[1].getAttribute("y")).toBe("0");
  expect(cells[0].getAttribute("width")).toBe("20"); expect(cells[0].getAttribute("height")).toBe("20");
  expect(cells[0].getAttribute("stroke")).toBe("#ccc");
  expect([...svg.querySelectorAll("text")].map(label => label.textContent)).toEqual(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("D3 zero and maximum values use the lightest and darkest blue colors", () => {
  const view = render(<D3CalendarHeatMap data={days} />);
  const cells = view.container.querySelectorAll("rect.day-cell");
  expect(cells[0].getAttribute("fill")).toBe("rgb(247, 251, 255)");
  expect(cells[1].getAttribute("fill")).toBe("rgb(8, 48, 107)");
});

// Generated by Codex and not thoroughly checked for correctness.
test("all-zero data uses a valid scale and remains unchanged", () => {
  const data = [{ date: new Date(2024, 1, 29), value: 0 }];
  const view = render(<D3CalendarHeatMap data={data} />);
  expect(view.container.querySelector("rect")?.getAttribute("fill")).toBe("rgb(247, 251, 255)");
  expect(data[0]).toEqual({ date: new Date(2024, 1, 29), value: 0 });
});

// Generated by Codex and not thoroughly checked for correctness.
test("D3 redraws changed data and dimensions without accumulating groups or labels", () => {
  const view = render(<D3CalendarHeatMap data={days} />);
  view.rerender(<D3CalendarHeatMap data={[{ date: new Date(2025, 0, 1), value: 3 }]} width={1000} height={300} />);
  const svg = view.container.querySelector("svg")!;
  expect(svg.getAttribute("width")).toBe("1000"); expect(svg.getAttribute("height")).toBe("300");
  expect(svg.querySelectorAll("g")).toHaveLength(1); expect(svg.querySelectorAll("text")).toHaveLength(12);
  const cell = svg.querySelector("rect")!;
  expect(svg.querySelectorAll("rect")).toHaveLength(1);
  expect(cell.getAttribute("y")).toBe("60");
});

// Generated by Codex and not thoroughly checked for correctness.
test("D3 effect cleanup removes generated content from its captured SVG on unmount", () => {
  const view = render(<D3CalendarHeatMap data={days} />);
  const svg = view.container.querySelector("svg")!;
  view.unmount();
  expect(svg.childNodes).toHaveLength(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("D3 StrictMode effect replay keeps a single chart", () => {
  const view = render(<StrictMode><D3CalendarHeatMap data={days} /></StrictMode>);
  expect(view.container.querySelectorAll("g")).toHaveLength(1);
  expect(view.container.querySelectorAll("rect.day-cell")).toHaveLength(2);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty D3 data produces no cells or invented month labels and can recover", () => {
  const view = render(<D3CalendarHeatMap data={[]} />);
  expect(view.container.querySelectorAll("rect, text")).toHaveLength(0);
  view.rerender(<D3CalendarHeatMap data={days} />);
  expect(view.container.querySelectorAll("rect")).toHaveLength(2);
  view.rerender(<D3CalendarHeatMap data={[]} />);
  expect(view.container.querySelectorAll("rect, text")).toHaveLength(0);
});
