import { frontend, resetFrontendMocks } from "../../../support/frontendMocks";
import { cleanup, fireEvent, render } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import ReactCalendarHeatMap from "../../../../src/components/common/charts/heat-maps/ReactCalendarHeatMap";
import Theme, { ThemesType } from "../../../../src/util/Theme";

const originalWidth = window.innerWidth;
beforeEach(() => { resetFrontendMocks(); Object.defineProperty(window, "innerWidth", { configurable: true, value: 1000 }); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); Object.defineProperty(window, "innerWidth", { configurable: true, value: originalWidth }); });
function setup(data: { date: Date; value: number }[]) {
  const over = vi.fn(), leave = vi.fn();
  const props = { data, minimumValueForMaxColor: 5, onDayCellMouseOver: over, onDayCellMouseLeave: leave };
  return { ...render(<ReactCalendarHeatMap {...props} />), over, leave, props };
}

// Generated by Codex and not thoroughly checked for correctness.
test("React heatmap distinguishes explicit zero from missing data and passes hover metadata", () => {
  const view = setup([{ date: new Date(2024, 0, 1), value: 0 }]);
  const cells = view.container.querySelectorAll("rect");
  expect(cells).toHaveLength(366);
  expect(cells[0].getAttribute("fill")).toBe("rgba(58, 74, 148, 0)");
  expect(cells[1].getAttribute("fill")).toBe("#c7c9d4");
  fireEvent.mouseEnter(cells[1], { clientX: 30, clientY: 40 });
  expect(view.over).toHaveBeenCalledExactlyOnceWith({ date: new Date(2024, 0, 2), value: 0 }, 30, 40);
  fireEvent.mouseLeave(cells[1]); expect(view.leave).toHaveBeenCalledTimes(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("React heatmap updates values and calendar length when its year changes", () => {
  const view = setup([{ date: new Date(2024, 1, 29), value: 2 }]);
  view.rerender(<ReactCalendarHeatMap {...view.props} data={[{ date: new Date(2025, 0, 1), value: 10 }]} />);
  const cells = view.container.querySelectorAll("rect");
  expect(cells).toHaveLength(365); expect(cells[0].getAttribute("fill")).toBe("rgba(58, 74, 148, 1)");
  fireEvent.mouseEnter(cells[0]);
  expect(view.over.mock.calls[0][0]).toEqual({ date: new Date(2025, 0, 1), value: 10 });
});

// Generated by Codex and not thoroughly checked for correctness.
test("React heatmap crosses the 900px responsive boundary without remounting", () => {
  const view = setup([{ date: new Date(2024, 0, 1), value: 1 }]);
  const svg = view.container.querySelector("svg")!;
  expect(svg.getAttribute("width")).toBe("875");
  Object.defineProperty(window, "innerWidth", { configurable: true, value: 899 }); fireEvent(window, new Event("resize"));
  expect(svg.getAttribute("width")).toBe("451"); expect(svg.querySelector("rect")?.getAttribute("width")).toBe("5");
  Object.defineProperty(window, "innerWidth", { configurable: true, value: 900 }); fireEvent(window, new Event("resize"));
  expect(svg.getAttribute("width")).toBe("875"); expect(svg.querySelector("rect")?.getAttribute("width")).toBe("13");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([ThemesType.LIGHT, ThemesType.DARK])("React heatmap labels use the selected theme %s", themeType => {
  frontend.theme = new Theme(themeType);
  const view = setup([{ date: new Date(2024, 0, 1), value: 1 }]);
  expect([...view.container.querySelectorAll("text")].every(label => label.getAttribute("class") === frontend.theme?.text)).toBe(true);
  expect(view.container.querySelectorAll("text")).toHaveLength(19);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty React data renders no invalid-date cells and recovers when data arrives", () => {
  const view = setup([]);
  expect(view.container.querySelectorAll("rect")).toHaveLength(0);
  view.rerender(<ReactCalendarHeatMap {...view.props} data={[{ date: new Date(2024, 0, 1), value: 1 }]} />);
  expect(view.container.querySelectorAll("rect")).toHaveLength(366);
});
