import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import EditableText from "../../src/components/common/EditableText";
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test("editable text enters editing, trims submissions, and updates when its value changes", () => {
  const onSubmit = vi.fn();
  const view = render(<EditableText value="tourist" label="Handles" onSubmit={onSubmit} />);
  fireEvent.click(screen.getByRole("button", { name: "Handles" }));
  const input = screen.getByRole("textbox", { name: "Handles" });
  fireEvent.change(input, { target: { value: " jiangly " } }); fireEvent.submit(input.closest("form")!);
  expect(onSubmit).toHaveBeenCalledExactlyOnceWith("jiangly");
  view.rerender(<EditableText value="jiangly" label="Handles" onSubmit={onSubmit} />);
  expect(screen.getByText("jiangly")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("unchanged blur exits editing while explicit clearing submits an empty value", () => {
  const onSubmit = vi.fn();
  render(<EditableText value="tourist" label="Handles" onSubmit={onSubmit} />);
  fireEvent.click(screen.getByRole("button", { name: "Handles" }));
  fireEvent.blur(screen.getByRole("textbox", { name: "Handles" }));
  expect(screen.queryByRole("textbox")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Handles" }));
  const input = screen.getByRole("textbox", { name: "Handles" });
  fireEvent.change(input, { target: { value: " " } }); fireEvent.submit(input.closest("form")!);
  expect(onSubmit).toHaveBeenCalledWith("");
  expect(screen.getByRole("textbox", { name: "Handles" })).toBeDefined();
});
