import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
import InputNumber from "../../src/components/common/forms/Input/InputNumber";
import InputRangeSlider from "../../src/components/common/forms/Input/InputRangeSlider";
import Theme, { ThemesType } from "../../src/util/Theme";
beforeEach(() => vi.useFakeTimers());
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers(); });

// Generated by Codex and not thoroughly checked for correctness.
test("out-of-range numeric edits reset after 500ms and a valid replacement cancels the reset", () => {
  const onChange = vi.fn();
  render(<InputNumber name="rating" header="Rating" value={800} min={0} max={4000} onChange={onChange} />);
  const input = screen.getByRole("spinbutton");
  fireEvent.change(input, { target: { value: "5000" } });
  act(() => vi.advanceTimersByTime(499)); expect((input as HTMLInputElement).value).toBe("5000");
  act(() => vi.advanceTimersByTime(1)); expect((input as HTMLInputElement).value).toBe("800");
  fireEvent.change(input, { target: { value: "5000" } });
  fireEvent.change(input, { target: { value: "1200" } });
  act(() => vi.advanceTimersByTime(500));
  expect((input as HTMLInputElement).value).toBe("1200");
  expect(onChange).toHaveBeenCalledWith(1200);
});

// Generated by Codex and not thoroughly checked for correctness.
test("range sliders constrain crossed handles and expose accessible bounds", () => {
  const onChange = vi.fn();
  render(<InputRangeSlider name="Rating" min={0} max={4000} minValue={800} maxValue={1200} step={100} theme={new Theme(ThemesType.LIGHT)} onChange={onChange} />);
  const min = screen.getByRole("slider", { name: "Minimum rating" });
  const max = screen.getByRole("slider", { name: "Maximum rating" });
  expect(min.getAttribute("aria-valuemax")).toBe("1200");
  expect(max.getAttribute("aria-valuemin")).toBe("800");
  fireEvent.change(min, { target: { value: "2000" } }); expect(onChange).toHaveBeenLastCalledWith(1200, 1200);
  fireEvent.change(max, { target: { value: "500" } }); expect(onChange).toHaveBeenLastCalledWith(800, 800);
});
