import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import InputDateRange from "../../src/components/common/forms/Input/InputDateRange";
import Theme, { ThemesType } from "../../src/util/Theme";
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 9, 4, 12)); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers(); });
function setup(minValue?: string, maxValue?: string) {
  const onMinChange = vi.fn(), onMaxChange = vi.fn();
  render(<InputDateRange name="Date" theme={new Theme(ThemesType.LIGHT)} minValue={minValue} maxValue={maxValue} onMinChange={onMinChange} onMaxChange={onMaxChange} />);
  return { onMinChange, onMaxChange };
}

// Generated by Codex and not thoroughly checked for correctness.
test("date changes accept leap days but reject reversed and future bounds", () => {
  const callbacks = setup("2024-01-01", "2024-03-01");
  fireEvent.change(screen.getByLabelText("min date"), { target: { value: "2024-02-29" } });
  expect(callbacks.onMinChange).toHaveBeenCalledExactlyOnceWith("2024-02-29");
  fireEvent.change(screen.getByLabelText("min date"), { target: { value: "2024-03-02" } });
  expect(callbacks.onMinChange).toHaveBeenCalledTimes(1);
  fireEvent.change(screen.getByLabelText("max date"), { target: { value: "2023-12-31" } });
  fireEvent.change(screen.getByLabelText("max date"), { target: { value: "2026-10-05" } });
  expect(callbacks.onMaxChange).not.toHaveBeenCalled();
});

// Generated by Codex and not thoroughly checked for correctness.
test("clear actions return undefined independently without opening the picker", () => {
  const callbacks = setup("2024-01-01", "2024-03-01");
  fireEvent.click(screen.getByRole("button", { name: "Clear min date" }));
  expect(callbacks.onMinChange).toHaveBeenCalledExactlyOnceWith(undefined);
  expect(callbacks.onMaxChange).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Clear max date" }));
  expect(callbacks.onMaxChange).toHaveBeenCalledExactlyOnceWith(undefined);
});

// Generated by Codex and not thoroughly checked for correctness.
test("picker buttons focus inputs when native showPicker is unavailable", () => {
  setup();
  const input = screen.getByLabelText("min date");
  Object.defineProperty(input, "showPicker", { configurable: true, value: undefined });
  fireEvent.click(screen.getByRole("button", { name: "Open min date picker" }));
  expect(document.activeElement).toBe(input);
});

// Generated by Codex and not thoroughly checked for correctness.
test("native date picker is invoked once and clearing the field returns undefined", () => {
  const callbacks = setup("2024-01-01");
  const input = screen.getByLabelText("min date");
  const showPicker = vi.fn(); Object.defineProperty(input, "showPicker", { configurable: true, value: showPicker });
  fireEvent.click(screen.getByRole("button", { name: "Open min date picker" }));
  expect(showPicker).toHaveBeenCalledTimes(1);
  fireEvent.change(input, { target: { value: "" } });
  expect(callbacks.onMinChange).toHaveBeenCalledWith(undefined);
});
