import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import ProblemPage from "../../src/components/problem/ProblemPage";
import { createSubmission, seedProblemFixtures } from "../support/problemFixtures";
import { createRouterWrapper, LocationProbe } from "../support/router";
import { formatTimestampDate } from "../../src/util/time";
import { Verdict } from "../../src/types/CF/Submission";

beforeEach(() => { resetFrontendMocks(); localStorage.clear(); seedProblemFixtures(); });
afterEach(cleanup);

function setup(query = "") {
  return render(<><ProblemPage /><LocationProbe /></>, {
    wrapper: createRouterWrapper(`/problems?useFilterStorage=false&${query}`),
  });
}

function rowIds() {
  return within(screen.getByRole("table")).getAllByRole("row").slice(1)
    .map((row) => within(row).getAllByRole("cell")[1].textContent);
}

async function openFilters() {
  // The current filter trigger is icon-only; scope its lookup to the toolbar.
  fireEvent.click(screen.getByPlaceholderText("Problem Name or Id").closest("ul")!.querySelector("li:last-child button")!);
  return screen.findByRole("dialog");
}

// Generated by Codex and not thoroughly checked for correctness.
test("searching on a late page resets the page and clearing search restores results", () => {
  setup("perPage=2&page=2");
  expect(rowIds()).toEqual(["15000A"]);
  fireEvent.change(screen.getByPlaceholderText("Problem Name or Id"), { target: { value: " ALPHA " } });
  expect(rowIds()).toEqual(["100A"]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
  fireEvent.change(screen.getByPlaceholderText("Problem Name or Id"), { target: { value: "" } });
  expect(rowIds()).toEqual(["100A", "100B"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("rating sliders and unrated toggle update visible table rows", async () => {
  setup();
  const dialog = await openFilters();
  fireEvent.change(within(dialog).getByRole("slider", { name: "Minimum rating" }), { target: { value: "1200" } });
  fireEvent.change(within(dialog).getByRole("slider", { name: "Maximum rating" }), { target: { value: "1600" } });
  fireEvent.click(within(dialog).getByRole("checkbox"));
  fireEvent.click(within(dialog).getByRole("button", { name: "Close" }));
  await waitFor(() => expect(screen.queryByRole("dialog")).toBeNull());
  expect(rowIds()).toEqual(["100B", "101A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("tag buttons, Select All, and Deselect All update the table", async () => {
  setup();
  const dialog = await openFilters();
  fireEvent.click(within(dialog).getByRole("button", { name: "dp" }));
  expect(rowIds()).toEqual(["100A", "101A"]);
  fireEvent.click(within(dialog).getByRole("button", { name: "graphs" }));
  expect(rowIds()).toEqual(["100A", "100B", "101A"]);
  fireEvent.click(within(dialog).getByRole("button", { name: "Select All" }));
  expect(rowIds()).toEqual(["100A", "100B", "101A", "15000A"]);
  fireEvent.click(within(dialog).getByRole("button", { name: "Deselect All" }));
  expect(rowIds()).toEqual(["100A", "100B", "101A", "102A", "15000A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("sort headers toggle visible order and show the matching sort icon", () => {
  setup();
  const rating = screen.getByRole("button", { name: "Rating" });
  fireEvent.click(rating);
  expect(rowIds()).toEqual(["102A", "100A", "100B", "101A", "15000A"]);
  expect(rating.querySelector('svg[data-icon="sort-up"]')).not.toBeNull();
  fireEvent.click(rating);
  expect(rowIds()).toEqual(["15000A", "101A", "100B", "100A", "102A"]);
  expect(rating.querySelector('svg[data-icon="sort-down"]')).not.toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("next, last, first, and page size controls preserve row numbering", () => {
  setup("perPage=2");
  fireEvent.click(screen.getByRole("button", { name: ">" }));
  expect(rowIds()).toEqual(["101A", "102A"]);
  expect(screen.getByRole("link", { name: "101A" }).closest("tr")!.firstElementChild!.textContent).toBe("3");
  fireEvent.click(screen.getByRole("button", { name: ">>" }));
  expect(rowIds()).toEqual(["15000A"]);
  fireEvent.click(screen.getByRole("button", { name: "<<" }));
  fireEvent.change(screen.getByRole("combobox", { name: "Per Page" }), { target: { value: "5" } });
  expect(rowIds()).toEqual(["100A", "100B", "101A", "102A", "15000A"]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("direct filter changes recover from a page beyond the narrowed results", async () => {
  setup("perPage=2&page=2");
  const dialog = await openFilters();
  fireEvent.click(within(dialog).getByRole("button", { name: "dp" }));
  expect(rowIds()).toEqual(["100A", "101A"]);
  expect(screen.getByText("Page 1 of 1")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("random toolbar selects one matching row, disables pagination, and cancels to browsing", () => {
  setup("tags=dp");
  fireEvent.click(screen.getByTitle("Find Random Problem"));
  expect(rowIds()).toHaveLength(1);
  expect(["100A", "101A"]).toContain(rowIds()[0]);
  expect((screen.getByRole("combobox", { name: "Per Page" }) as HTMLSelectElement).disabled).toBe(true);
  const params = new URLSearchParams(screen.getByTestId("location").textContent!.split("?")[1]);
  expect(params.get("random")).toBe("true");
  fireEvent.click(screen.getByTitle("Cancel Random"));
  expect(screen.getByTestId("location").textContent!.split("?")[0]).toBe("/problems");
  expect(rowIds()).toEqual(["100A", "101A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty results disable pagination and random selection without rendering undefined rows", () => {
  setup("q=no-matching-problem");
  expect(rowIds()).toEqual([]);
  expect(screen.getByText("Showing 0 of 0")).toBeDefined();
  fireEvent.click(screen.getByTitle("Find Random Problem"));
  expect(rowIds()).toEqual([]);
  expect((screen.getByRole("combobox", { name: "Per Page" }) as HTMLSelectElement).disabled).toBe(true);
  expect(screen.getByText("Page 0 of 0")).toBeDefined();
});

// Generated by Codex and not thoroughly checked for correctness.
test("loading indicator is replaced by rows when problem data is ready", () => {
  frontend.loading = true;
  const view = setup();
  expect(screen.getByRole("status", { name: "three-dots-loading" })).toBeDefined();
  expect(screen.queryByRole("table")).toBeNull();
  frontend.loading = false;
  view.rerender(<><ProblemPage /><LocationProbe /></>);
  expect(screen.queryByRole("status", { name: "three-dots-loading" })).toBeNull();
  expect(rowIds()).toHaveLength(5);
});

// Generated by Codex and not thoroughly checked for correctness.
test("problem links and solved/attempted row indicators match their data", () => {
  setup();
  const solved = screen.getByRole("link", { name: "Alpha Dynamic" });
  expect(solved.getAttribute("href")).toBe("https://codeforces.com/contest/100/problem/A");
  expect(solved.getAttribute("target")).toBe("_blank");
  expect(solved.getAttribute("rel")).toBe("noreferrer");
  expect(solved.closest("td")!.classList.contains(frontend.theme!.bgSuccess)).toBe(true);
  expect(screen.getByRole("link", { name: "Beta Graph" }).closest("td")!.classList.contains(frontend.theme!.bgDanger)).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("submission banner reflects the same bounds used by status filtering", () => {
  setup("submittedAfter=100&submittedBefore=200&status=ATTEMPTED");
  expect(screen.getByText("Submission range").closest('[role="status"]')!.textContent).toContain(`From ${formatTimestampDate(100)}`);
  expect(screen.getByText("Submission range").closest('[role="status"]')!.textContent).toContain(`Before ${formatTimestampDate(200)}`);
  expect(rowIds()).toEqual(["100A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("an acceptance expanded from a shared contest marks its equivalent row solved with its own URL", () => {
  // The submission-store boundary supplies already-expanded shared submissions.
  const shared = createSubmission(2, frontend.problems[2], Verdict.OK, 200);
  shared.fromShared = true;
  frontend.submissions.push(shared);
  setup("status=SOLVED");
  expect(rowIds()).toEqual(["100A", "101A"]);
  const equivalent = screen.getByRole("link", { name: "Gamma Mixed" });
  expect(equivalent.getAttribute("href")).toBe("https://codeforces.com/contest/101/problem/A");
  expect(equivalent.closest("td")!.classList.contains(frontend.theme!.bgSuccess)).toBe(true);
});
