import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import useProblemPage from "../../src/components/problem/useProblemPage";
import { Verdict } from "../../src/types/CF/Submission";
import { SortOrder, SortProblemBy } from "../../src/util/sortMethods";
import { seedProblemFixtures } from "../support/problemFixtures";
import { createRouterWrapper } from "../support/router";

beforeEach(() => {
  resetFrontendMocks();
  localStorage.clear();
  seedProblemFixtures();
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

function setup(query = "") {
  return renderHook(useProblemPage, { wrapper: createRouterWrapper(`/problems?useFilterStorage=false&${query}`) });
}

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [" ALPHA ", ["100A"]], ["100b", ["100B"]], ["mixed", ["101A"]], ["", ["100A", "100B", "101A", "102A", "15000A"]],
])("FE-027 search %s matches names and IDs regardless of case or outer whitespace", (search, expected) => {
  const hook = setup();
  act(() => hook.result.current.updateFilter({ search }));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [[Verdict.SOLVED], ["100A"]], [[Verdict.ATTEMPTED], ["100B"]],
  [[Verdict.UNSOLVED], ["101A", "102A", "15000A"]],
  [[Verdict.SOLVED, Verdict.ATTEMPTED], ["100A", "100B"]], [[], []],
])("FE-028 statuses %j use acceptance precedence over failed attempts", (statuses, expected) => {
  const hook = setup();
  act(() => hook.result.current.setSolveStatus(new Set(statuses)));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-029 rating bounds include their endpoints and unrated inclusion follows the checkbox", () => {
  const hook = setup("minRating=800&maxRating=1200&showUnrated=false");
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["100A", "100B"]);
  act(() => hook.result.current.updateFilter({ showUnrated: true }));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["100A", "100B", "102A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-030 contest ID bounds include supported high IDs and their endpoints", () => {
  const hook = setup("minContestId=101&maxContestId=15000");
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["101A", "102A", "15000A"]);
  act(() => hook.result.current.updateFilter({ minContestId: 15000 }));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["15000A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-030 contest dates include both boundaries", () => {
  const hook = setup("minContestDate=2026-01-02&maxContestDate=2026-01-03");
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["101A", "102A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [["dp"], ["100A", "101A"]], [["dp", "graphs"], ["100A", "100B", "101A"]],
  [[], ["100A", "100B", "101A", "102A", "15000A"]],
])("FE-031 tags %j match any selected tag and empty selection disables tag filtering", (tags, expected) => {
  const hook = setup();
  act(() => hook.result.current.setTags(new Set(tags)));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(expected);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-032 combined filters produce no matches without invalid random rows", () => {
  const hook = setup("random=true&status=SOLVED&tags=graphs&minRating=1200&maxRating=1600");
  expect(hook.result.current.problemList.problems).toEqual([]);
  expect(hook.result.current.currentPageProblems).toEqual([]);
  expect(hook.result.current.isRandomActive).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  [SortProblemBy.Id, SortOrder.Descending, ["15000A", "102A", "101A", "100B", "100A"]],
  [SortProblemBy.Rating, SortOrder.Ascending, ["102A", "100A", "100B", "101A", "15000A"]],
  [SortProblemBy.SolveCount, SortOrder.Ascending, ["15000A", "102A", "101A", "100B", "100A"]],
])("FE-033 sort %s selects its initial order and toggles on the second click", (sort, initialOrder, expected) => {
  const hook = setup();
  act(() => hook.result.current.sortList(sort));
  expect(hook.result.current.filterState.order).toBe(initialOrder);
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(expected);
  act(() => hook.result.current.sortList(sort));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual([...expected].reverse());
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-034 page slices contain no skipped or duplicated problems", () => {
  const hook = setup("perPage=2");
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["100A", "100B"]);
  act(() => hook.result.current.setSelected(1));
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["101A", "102A"]);
  act(() => hook.result.current.setSelected(2));
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["15000A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-035 rerolls stay within filtered results and exit restores all matching problems", () => {
  const random = vi.spyOn(Math, "random").mockReturnValue(0);
  const hook = setup("random=true&tags=dp");
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["100A"]);
  random.mockReturnValue(0.99);
  act(() => hook.result.current.updateFilter({ search: "a" }));
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["101A"]);
  act(() => hook.result.current.setRandomProblem(undefined));
  expect(hook.result.current.isRandomActive).toBe(false);
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["100A", "101A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-036 one matching problem remains selectable and random selection waits for completed loading", () => {
  frontend.loading = true;
  const hook = setup("random=true&q=100b");
  expect(hook.result.current.isRandomActive).toBe(false);
  frontend.loading = false;
  hook.rerender();
  expect(hook.result.current.isRandomActive).toBe(true);
  expect(hook.result.current.currentPageProblems.map((problem) => problem.id)).toEqual(["100B"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-038 submission range includes start and excludes end when assigning solve status", () => {
  const hook = setup("submittedAfter=100&submittedBefore=200&status=ATTEMPTED");
  expect(hook.result.current.submissionRange).toEqual({ after: 100, before: 200 });
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["100A"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("FE-033 tied ratings and solve counts retain every problem without mutating source order", () => {
  frontend.problems[1].rating = 800;
  frontend.problems[1].solvedCount = 50;
  const sourceIds = frontend.problems.map((problem) => problem.id);
  const hook = setup();
  act(() => hook.result.current.sortList(SortProblemBy.Rating));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id)).toEqual(["102A", "100A", "100B", "101A", "15000A"]);
  act(() => hook.result.current.sortList(SortProblemBy.SolveCount));
  expect(hook.result.current.problemList.problems.map((problem) => problem.id).sort()).toEqual([...sourceIds].sort());
  expect(hook.result.current.problemList.problems.slice(0, 2).map((problem) => problem.solvedCount)).toEqual([50, 50]);
  expect(frontend.problems.map((problem) => problem.id)).toEqual(sourceIds);
});
