import { frontend, resetFrontendMocks } from "../support/frontendMocks";
import { cleanup, render } from "@testing-library/react";
import { afterEach, beforeEach, expect, test } from "vitest";
import CommentPage from "../../src/components/comment/CommentPage";
import Theme, { ThemesType } from "../../src/util/Theme";
beforeEach(resetFrontendMocks);
afterEach(cleanup);

// Generated by Codex and not thoroughly checked for correctness.
test.each([[ThemesType.LIGHT, "github-light"], [ThemesType.DARK, "dark-blue"]] as const)("comments configure a single embed for theme %s", (theme, expected) => {
  frontend.theme = new Theme(theme);
  const view = render(<CommentPage />);
  const script = view.container.querySelector("script")!;
  expect(script.src).toBe("https://utteranc.es/client.js");
  expect(script.getAttribute("repo")).toBe("mbashem/cftracker");
  expect(script.getAttribute("issue-term")).toBe("pathname");
  expect(script.getAttribute("label")).toBe("CFTracker Comments");
  expect(script.getAttribute("theme")).toBe(expected);
  expect(script.async).toBe(true); expect(script.crossOrigin).toBe("anonymous");
  view.rerender(<CommentPage />);
  expect(view.container.querySelectorAll("script")).toHaveLength(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("theme changes currently retain the existing embed without duplicating its script", () => {
  const view = render(<CommentPage />);
  frontend.theme = new Theme(ThemesType.DARK); view.rerender(<CommentPage />);
  expect(view.container.querySelectorAll("script")).toHaveLength(1);
  expect(view.container.querySelector("script")?.getAttribute("theme")).toBe("github-light");
  view.unmount();
  const next = render(<CommentPage />);
  expect(next.container.querySelector("script")?.getAttribute("theme")).toBe("dark-blue");
});
