"""Regression tests for preserving and refreshing growth snapshots."""
import contextlib
import csv
from datetime import datetime
import io
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import generate_timeline as timeline


class TimelineRefreshTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory(prefix='cftracker-timeline-test-')
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        self.root.joinpath('docs').mkdir()
        self.branch = 'dev'
        self.commit = '2222222' + '2' * 33
        self.today = datetime(2026, 10, 4)
        for name, value in [
            ('ROOT', self.root),
            ('CSV_PATH', self.root / 'docs/totals.csv'),
            ('BREAKDOWN_PATH', self.root / 'docs/breakdown.csv'),
            ('SVG_PATH', self.root / 'docs/growth.svg'),
        ]:
            patcher = patch.object(timeline, name, value)
            patcher.start()
            self.addCleanup(patcher.stop)
        clock = patch.object(timeline, 'datetime')
        self.clock = clock.start()
        self.addCleanup(clock.stop)
        git = patch.object(timeline, 'git', side_effect=self.git)
        git.start()
        self.addCleanup(git.stop)
        counter = patch.object(timeline, 'count_snapshot', return_value=(
            {'nFiles': 2, 'blank': 0, 'comment': 0, 'code': 10}, 2,
        ))
        self.counter = counter.start()
        self.addCleanup(counter.stop)

    def git(self, *args):
        if args == ('branch', '--show-current'):
            return self.branch
        if args == ('rev-parse', 'HEAD'):
            return self.commit
        if args[0] == 'rev-list':
            return ''
        raise AssertionError(f'Unexpected git command: {args}')

    def seed(self, timestamp='2026-10-04', branch='dev', commit='1111111'):
        row = dict(zip(timeline.FIELDS, [timestamp, branch, commit, 2, 0, 0, 10,
                                         'json', '.git;node_modules;dist;build']))
        with timeline.CSV_PATH.open('w', newline='') as file:
            writer = csv.DictWriter(file, fieldnames=timeline.FIELDS, lineterminator='\n')
            writer.writeheader()
            writer.writerow(row)
        with timeline.BREAKDOWN_PATH.open('w', newline='') as file:
            writer = csv.DictWriter(file, fieldnames=timeline.BREAKDOWN_FIELDS, lineterminator='\n')
            writer.writeheader()
            writer.writerow(dict(zip(timeline.BREAKDOWN_FIELDS, [timestamp, branch, commit, 8, 2, 10])))
        return timeline.CSV_PATH.read_bytes()

    def refresh(self):
        self.clock.now.return_value = self.today
        with contextlib.redirect_stdout(io.StringIO()):
            timeline.main()
        with timeline.CSV_PATH.open(newline='') as file:
            return list(csv.DictReader(file))

    # Generated by Codex and not thoroughly checked for correctness.
    def test_new_commit_on_same_day_appends_and_preserves_history(self):
        original = self.seed()
        rows = self.refresh()
        self.assertEqual([row['commit'] for row in rows], ['1111111', '2222222'])
        self.assertTrue(timeline.CSV_PATH.read_bytes().startswith(original))
        self.assertIn('2026-10-04 · dev · 2222222', timeline.SVG_PATH.read_text())
        self.assertIn('`2222222`', (self.root / 'PROJECT_TIMELINE.md').read_text())
        with timeline.BREAKDOWN_PATH.open(newline='') as file:
            self.assertEqual(len(list(csv.DictReader(file))), 2)

    # Generated by Codex and not thoroughly checked for correctness.
    def test_branch_change_with_same_commit_gets_its_own_snapshot(self):
        original = self.seed(commit='2222222')
        self.branch = 'feature/chart'
        rows = self.refresh()
        self.assertEqual([(row['branch'], row['commit']) for row in rows], [
            ('dev', '2222222'), ('feature/chart', '2222222'),
        ])
        self.assertTrue(timeline.CSV_PATH.read_bytes().startswith(original))
        self.assertIn('feature/chart · 2222222', timeline.SVG_PATH.read_text())

    # Generated by Codex and not thoroughly checked for correctness.
    def test_unchanged_snapshot_does_not_remeasure_or_duplicate(self):
        self.seed(commit='2222222')
        self.refresh()
        files = [timeline.CSV_PATH, timeline.BREAKDOWN_PATH, timeline.SVG_PATH,
                 self.root / 'PROJECT_TIMELINE.md']
        before = [path.read_bytes() for path in files]
        self.refresh()
        self.counter.assert_not_called()
        self.assertEqual(before, [path.read_bytes() for path in files])

    # Generated by Codex and not thoroughly checked for correctness.
    def test_return_to_recorded_branch_updates_latest_without_duplicate(self):
        self.seed(commit='2222222')
        self.branch = 'feature/chart'
        self.refresh()
        self.branch = 'dev'
        self.counter.reset_mock()
        rows = self.refresh()
        self.assertEqual(len(rows), 2)
        self.counter.assert_not_called()
        self.assertIn('Latest recorded: 2026-10-04 · dev · 2222222', timeline.SVG_PATH.read_text())

    # Generated by Codex and not thoroughly checked for correctness.
    def test_main_interval_is_preserved_while_current_branch_is_appended(self):
        self.today = datetime(2026, 8, 1)
        original = self.seed(timestamp='2026-08-01', branch='main')
        rows = self.refresh()
        self.assertEqual([(row['branch'], row['commit']) for row in rows], [
            ('main', '1111111'), ('dev', '2222222'),
        ])
        self.assertTrue(timeline.CSV_PATH.read_bytes().startswith(original))


if __name__ == '__main__':
    unittest.main()
