import { setupBackendMock, codeforcesApi } from "../support/backendMocks";
import { act, cleanup, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, afterEach, expect, test } from "vitest";
import { findNonSerializableValue } from "@reduxjs/toolkit";
import useProblemsStore from "../../src/data/hooks/useProblemsStore";
import useContestStore from "../../src/data/hooks/useContestStore";
import useSharedProblemsStore from "../../src/data/hooks/useSharedProblemsStore";
import useSubmissionsStore from "../../src/data/hooks/useSubmissionsStore";
import useUserStore from "../../src/data/hooks/useUserStore";
import Problem, { type ProblemData } from "../../src/types/CF/Problem";
import { Verdict } from "../../src/types/CF/Submission";
import { createSubmission } from "../support/submissionFixtures";
import { requestUserSubmissions, addUserSubmissions } from "../../src/data/reducers/userSubmissionsSlice";

let backend: ReturnType<typeof setupBackendMock>;
const problemData: ProblemData = {
  contestId: 100, index: "A", name: "Alpha", type: "PROGRAMMING", rating: 800, tags: ["dp"], solvedCount: 10,
};
const problem = new Problem(
  problemData.contestId, problemData.index, problemData.name, problemData.type,
  problemData.rating, problemData.tags, problemData.solvedCount,
);
beforeEach(async () => {
  localStorage.clear(); backend = setupBackendMock();
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getProblems", undefined, [problemData]));
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getContest", undefined, [{ id: 100, name: "Round", phase: "FINISHED" }, { id: 200, name: "Shared", phase: "FINISHED" }]));
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getSharedProblems", undefined, [{ contestId: 100, index: "A", shared: [{ contestId: 200, index: "B" }] }]));
});
afterEach(() => { cleanup(); backend.dispose(); localStorage.clear(); });

// Generated by Codex and not thoroughly checked for correctness.
test("real problem hooks hydrate models and preserve selector identity until catalog changes", async () => {
  const hook = renderHook(useProblemsStore, { wrapper: backend.wrapper });
  expect(hook.result.current.problemsById.get("100A")).toBeInstanceOf(Problem);
  expect(hook.result.current.problemList.tags).toEqual(["dp"]);
  const previous = hook.result.current.problemList;
  hook.rerender(); expect(hook.result.current.problemList).toBe(previous);
  await act(async () => { await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getProblems", undefined, [{ ...problemData, tags: ["math"], name: "Updated" }])); });
  await waitFor(() => expect(hook.result.current.problemsById.get("100A")?.name).toBe("Updated"));
  expect(hook.result.current.problemList.tags).toEqual(["math"]);
  expect(findNonSerializableValue(backend.store.getState())).toBe(false);
});

// Generated by Codex and not thoroughly checked for correctness.
test("shared catalog models hydrate canonical IDs and populate the corresponding contest", () => {
  const hook = renderHook(() => ({ shared: useSharedProblemsStore(), contests: useContestStore() }), { wrapper: backend.wrapper });
  expect(hook.result.current.shared.sharedProblems.problems[0].shared?.[0].id).toBe("200B");
  expect(hook.result.current.contests.contests.map(contest => contest.count)).toEqual([1, 1]);
  expect(backend.requests).toHaveLength(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("shared submission expansion preserves raw counts and uses the equivalent canonical problem ID", async () => {
  const action = requestUserSubmissions(["tourist"], true);
  backend.store.dispatch(action);
  const original = createSubmission(1, problem, Verdict.OK, 100);
  backend.store.dispatch(addUserSubmissions({ handle: "tourist", requestId: action.payload.requestId, submissions: [JSON.parse(JSON.stringify(original))] }));
  const hook = renderHook(useSubmissionsStore, { wrapper: backend.wrapper });
  expect(hook.result.current.rawSubmissions).toHaveLength(1);
  expect(hook.result.current.submissions.map(value => value.problem.id)).toEqual(["100A", "200B"]);
  expect(hook.result.current.submissions[1].author.contestId).toBe(200);
  expect(hook.result.current.submissions[1].fromShared).toBe(true);
  expect(original.problem.id).toBe("100A");
  hook.result.current.submissions[1].author.members[0].handle = "changed";
  expect(original.author.members[0].handle).toBe("tourist");
  await backend.store.dispatch(requestUserSubmissions([]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("real handle operations trim and deduplicate input, remove handles and clear all", () => {
  const hook = renderHook(useUserStore, { wrapper: backend.wrapper });
  act(() => hook.result.current.updateUsers(" tourist,jiangly,tourist, , "));
  expect(hook.result.current.userList.handles).toEqual(["tourist", "jiangly"]);
  act(() => hook.result.current.removeHandle("tourist"));
  expect(hook.result.current.userList.handles).toEqual(["jiangly"]);
  act(() => hook.result.current.addHandle(" jiangly "));
  expect(hook.result.current.userList.handles).toEqual(["jiangly"]);
  act(() => hook.result.current.updateUsers(" , "));
  expect(hook.result.current.userList.handles).toEqual([]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("shared expansion deduplicates identical targets while preserving split indexes in one contest", async () => {
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getSharedProblems", undefined, [{ contestId: 100, index: "A", shared: [
    { contestId: 100, index: "A" }, { contestId: 200, index: "B" }, { contestId: 200, index: "B" }, { contestId: 200, index: "C" },
  ] }]));
  const action = requestUserSubmissions(["tourist"], true); backend.store.dispatch(action);
  const original = createSubmission(1, problem, Verdict.OK, 100);
  backend.store.dispatch(addUserSubmissions({ handle: "tourist", requestId: action.payload.requestId, submissions: [JSON.parse(JSON.stringify(original))] }));
  const hook = renderHook(useSubmissionsStore, { wrapper: backend.wrapper });
  expect(hook.result.current.submissions.map(value => value.problem.id)).toEqual(["100A", "200B", "200C"]);
  expect(hook.result.current.rawSubmissions).toHaveLength(1);
  backend.store.dispatch(requestUserSubmissions([]));
});

// Generated by Codex and not thoroughly checked for correctness.
test("empty catalogs and missing shared sources do not invent contest problems", async () => {
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getProblems", undefined, []));
  const hook = renderHook(() => ({ problems: useProblemsStore(), contests: useContestStore(), submissions: useSubmissionsStore() }), { wrapper: backend.wrapper });
  expect(hook.result.current.problems.problemsById.size).toBe(0);
  expect(hook.result.current.contests.contests.map(value => value.count)).toEqual([0, 0]);
  expect(hook.result.current.submissions.rawSubmissions).toEqual([]);
  expect(hook.result.current.submissions.submissions).toEqual([]);
});
