import { expect, test } from "vitest";
import { normalizeProblemResult, normalizeContestResult, normalizeSharedProblemResult } from "../../src/data/queries/codeforcesApiResponse";

const problem = { contestId: 100, index: "A", name: "Alpha", type: "PROGRAMMING", tags: ["dp"] };

// Generated by Codex and not thoroughly checked for correctness.
test("problem statistics match canonical IDs when arrays are reordered or entries are missing", () => {
  const result = normalizeProblemResult({ status: "OK", result: {
    problems: [problem, { ...problem, index: "B" }, { ...problem, contestId: 101 }],
    problemStatistics: [{ contestId: 100, index: "B", solvedCount: 20 }, { contestId: 100, index: "A", solvedCount: 10 }],
  } });
  expect(result.map(value => [value.contestId, value.index, value.solvedCount])).toEqual([[100, "A", 10], [100, "B", 20], [101, "A", 0]]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("normalization excludes missing contest IDs, sorts numeric IDs and copies tags", () => {
  const result = normalizeProblemResult({ status: "OK", result: { problems: [{ ...problem, contestId: undefined }, { ...problem, contestId: 15000 }, problem], problemStatistics: [] } });
  expect(result.map(value => value.contestId)).toEqual([100, 15000]);
  result[0].tags.push("math");
  expect(problem.tags).toEqual(["dp"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("contest normalization excludes absent IDs and preserves optional fields", () => {
  expect(normalizeContestResult({ status: "OK", result: [{ name: "Missing", phase: "FINISHED" }, { id: 15000, name: "Round", phase: "FINISHED", startTimeSeconds: 100 }] })).toEqual([{ id: 15000, name: "Round", phase: "FINISHED", type: undefined, durationSeconds: undefined, startTimeSeconds: 100 }]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("shared normalization sorts sources, filters missing IDs and handles absent mappings", () => {
  expect(normalizeSharedProblemResult({ status: "OK", result: [{ index: "A" }, { contestId: 101, index: "A" }, { contestId: 100, index: "A", shared: [{ index: "B" }, { contestId: 200, index: "C" }] }] })).toEqual([{ contestId: 100, index: "A", shared: [{ contestId: 200, index: "C" }] }, { contestId: 101, index: "A", shared: [] }]);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([normalizeProblemResult, normalizeContestResult, normalizeSharedProblemResult])("normalizer %s rejects API failures", normalize => {
  expect(() => normalize({ status: "FAILED", result: [] } as never)).toThrow();
});
