import { setupBackendMock, codeforcesApi } from "../support/backendMocks";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
let backend: ReturnType<typeof setupBackendMock>;
function requestSavedCatalog(endpoint: "getContest" | "getSharedProblems") {
  return endpoint === "getContest"
    ? backend.store.dispatch(codeforcesApi.endpoints.getContest.initiate())
    : backend.store.dispatch(codeforcesApi.endpoints.getSharedProblems.initiate());
}
beforeEach(() => { backend = setupBackendMock(); vi.spyOn(console, "log").mockImplementation(() => {}); });
afterEach(() => { backend.dispose(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("problem queries normalize a real fetch response with matched statistics", async () => {
  backend.respond({ status: "OK", result: { problems: [{ contestId: 100, index: "A", name: "Alpha", type: "PROGRAMMING", tags: ["dp"] }], problemStatistics: [{ contestId: 100, index: "A", solvedCount: 7 }] } });
  const result = await backend.store.dispatch(codeforcesApi.endpoints.getProblems.initiate()).unwrap();
  expect(result[0].solvedCount).toBe(7);
  expect(backend.requests[0].url).toBe("https://codeforces.com/api/problemset.problems?lang=en");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([[{ status: "FAILED" }, 200], [{}, 500]] as const)("problem query errors stay observable for payload %j HTTP %i", async (response, status) => {
  backend.respond(response, status);
  await expect(backend.store.dispatch(codeforcesApi.endpoints.getProblems.initiate()).unwrap()).rejects.toBeDefined();
  expect(codeforcesApi.endpoints.getProblems.select()(backend.store.getState()).isError).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  { endpoint: "getContest" as const, filename: "contests_data.json", result: [{ id: 100, name: "Round", phase: "FINISHED" }] },
  { endpoint: "getSharedProblems" as const, filename: "related.json", result: [{ contestId: 100, index: "A", shared: [{ contestId: 200, index: "B" }] }] },
])("$endpoint fetches a same-origin JSON asset and caches normalized data", async ({ endpoint, filename, result }) => {
  backend.respond({ status: "OK", result });
  const data = await requestSavedCatalog(endpoint).unwrap();
  expect(data).toEqual(result);
  expect(backend.requests).toHaveLength(1);
  const url = new URL(backend.requests[0].url);
  expect(url.origin).toBe(window.location.origin);
  expect(url.pathname).toBe(`/src/data/saved_api/${filename}`);
  await requestSavedCatalog(endpoint).unwrap();
  expect(backend.requests).toHaveLength(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each(["getContest", "getSharedProblems"] as const)("%s exposes missing JSON assets as HTTP errors", async endpoint => {
  backend.respond({}, 404);
  await expect(requestSavedCatalog(endpoint).unwrap()).rejects.toMatchObject({ status: 404 });
  expect(codeforcesApi.endpoints[endpoint].select()(backend.store.getState()).isError).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([
  ["getContest", "Failed to load saved contestList."],
  ["getSharedProblems", "Error processing shared problems"],
] as const)("%s rejects failed JSON payloads with the existing error", async (endpoint, message) => {
  backend.respond({ status: "FAILED" });
  await expect(requestSavedCatalog(endpoint).unwrap()).rejects.toMatchObject({ status: "CUSTOM_ERROR", error: message });
});
