import { setupBackendMock, codeforcesApi } from "../support/backendMocks";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
let backend: ReturnType<typeof setupBackendMock>;
beforeEach(() => { backend = setupBackendMock(); vi.spyOn(console, "log").mockImplementation(() => {}); });
afterEach(() => { backend.dispose(); vi.restoreAllMocks(); });

// Generated by Codex and not thoroughly checked for correctness.
test("problem queries normalize a real fetch response with matched statistics", async () => {
  backend.respond({ status: "OK", result: { problems: [{ contestId: 100, index: "A", name: "Alpha", type: "PROGRAMMING", tags: ["dp"] }], problemStatistics: [{ contestId: 100, index: "A", solvedCount: 7 }] } });
  const result = await backend.store.dispatch(codeforcesApi.endpoints.getProblems.initiate()).unwrap();
  expect(result[0].solvedCount).toBe(7);
  expect(backend.requests[0].url).toBe("https://codeforces.com/api/problemset.problems?lang=en");
});

// Generated by Codex and not thoroughly checked for correctness.
test.each([[{ status: "FAILED" }, 200], [{}, 500]] as const)("problem query errors stay observable for payload %j HTTP %i", async (response, status) => {
  backend.respond(response, status);
  await expect(backend.store.dispatch(codeforcesApi.endpoints.getProblems.initiate()).unwrap()).rejects.toBeDefined();
  expect(codeforcesApi.endpoints.getProblems.select()(backend.store.getState()).isError).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("contest and shared queries load saved catalogs without external requests", async () => {
  const contests = await backend.store.dispatch(codeforcesApi.endpoints.getContest.initiate()).unwrap();
  const shared = await backend.store.dispatch(codeforcesApi.endpoints.getSharedProblems.initiate()).unwrap();
  expect(contests.length).toBeGreaterThan(0); expect(shared.length).toBeGreaterThan(0);
  expect(backend.requests).toHaveLength(0);
});
