import { setupBackendMock } from "../support/backendMocks";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
import { findNonSerializableValue } from "@reduxjs/toolkit";

let backend: ReturnType<typeof setupBackendMock>;
let catalogApi: typeof import("../../src/data/queries/codeforcesQuery").codeforcesApi;
beforeEach(async () => {
  vi.resetModules();
  vi.stubEnv("VITE_DEBUG_MODE", "true");
  vi.spyOn(console, "log").mockImplementation(() => {});
  ({ codeforcesApi: catalogApi } = await import("../../src/data/queries/codeforcesQuery"));
  backend = setupBackendMock(catalogApi);
});
afterEach(() => { backend.dispose(); vi.restoreAllMocks(); vi.unstubAllEnvs(); });

// Generated by Codex and not thoroughly checked for correctness.
test("debug problems fetch the same-origin JSON asset and normalize it into serializable cache data", async () => {
  backend.respond({ status: "OK", result: {
    problems: [
      { contestId: 200, index: "B", name: "Beta", type: "PROGRAMMING", tags: ["math"] },
      { contestId: 100, index: "A", name: "Alpha", type: "PROGRAMMING", tags: ["dp"] },
    ],
    problemStatistics: [
      { contestId: 100, index: "A", solvedCount: 7 },
      { contestId: 200, index: "B", solvedCount: 3 },
    ],
  } });
  const result = await backend.store.dispatch(catalogApi.endpoints.getProblems.initiate()).unwrap();
  expect(result.map(problem => [problem.contestId, problem.index, problem.solvedCount])).toEqual([[100, "A", 7], [200, "B", 3]]);
  expect(backend.requests).toHaveLength(1);
  const url = new URL(backend.requests[0].url);
  expect(url.origin).toBe(window.location.origin);
  expect(url.pathname).toBe("/src/data/saved_api/problems_data.json");
  expect(findNonSerializableValue(backend.store.getState())).toBe(false);
  await backend.store.dispatch(catalogApi.endpoints.getProblems.initiate()).unwrap();
  expect(backend.requests).toHaveLength(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("missing saved problems assets expose the HTTP error", async () => {
  backend.respond({}, 404);
  await expect(backend.store.dispatch(catalogApi.endpoints.getProblems.initiate()).unwrap()).rejects.toMatchObject({ status: 404 });
  expect(catalogApi.endpoints.getProblems.select()(backend.store.getState()).isError).toBe(true);
});

// Generated by Codex and not thoroughly checked for correctness.
test("invalid saved problems payloads expose the existing debug-mode error", async () => {
  backend.respond({ status: "FAILED" });
  await expect(backend.store.dispatch(catalogApi.endpoints.getProblems.initiate()).unwrap()).rejects.toMatchObject({
    status: "CUSTOM_ERROR", error: "Failed to load saved Problems list.",
  });
});
