import { setupBackendMock } from "../support/backendMocks";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
import { requestUserSubmissions, addUserSubmissions, errorFetchingUserSubmissions } from "../../src/data/reducers/userSubmissionsSlice";
import { removeHandle, removeAllHandle } from "../../src/data/reducers/userSlice";
import Problem from "../../src/types/CF/Problem";
import { Verdict } from "../../src/types/CF/Submission";
import { createSubmission } from "../support/submissionFixtures";

let backend: ReturnType<typeof setupBackendMock>;
const submission = JSON.parse(JSON.stringify(createSubmission(1, new Problem(100, "A", "Alpha", "PROGRAMMING", 800, []), Verdict.OK, 100)));
beforeEach(() => { localStorage.clear(); vi.useFakeTimers(); backend = setupBackendMock(); vi.spyOn(console, "log").mockImplementation(() => {}); });
afterEach(async () => { backend.store.dispatch(requestUserSubmissions([])); await vi.advanceTimersByTimeAsync(0); backend.dispose(); vi.restoreAllMocks(); vi.useRealTimers(); });

// Generated by Codex and not thoroughly checked for correctness.
test("synchronization waits between handles, retains partial success, and completes loading", async () => {
  backend.fetchMock.mockResolvedValueOnce(Response.json({ status: "OK", result: [submission] })).mockResolvedValueOnce(Response.json({ status: "FAILED" }));
  backend.store.dispatch(requestUserSubmissions(["tourist", "missing"]));
  await vi.advanceTimersByTimeAsync(0);
  expect(backend.store.getState().userSubmissions.loading).toBe(1);
  expect(backend.store.getState().userSubmissions.submissionsByHandle.tourist.submissions).toHaveLength(1);
  await vi.advanceTimersByTimeAsync(999); expect(backend.fetchMock).toHaveBeenCalledTimes(1);
  await vi.advanceTimersByTimeAsync(1); expect(backend.fetchMock).toHaveBeenCalledTimes(2);
  expect(backend.store.getState().userSubmissions.loading).toBe(0);
  expect(backend.store.getState().userSubmissions.error).toContain("missing");
});

// Generated by Codex and not thoroughly checked for correctness.
test("a delayed refresh is superseded before it sends a stale request", async () => {
  backend.respond({ status: "OK", result: [] });
  backend.store.dispatch(requestUserSubmissions(["old"], true));
  await vi.advanceTimersByTimeAsync(500);
  backend.store.dispatch(requestUserSubmissions(["new"]));
  await vi.advanceTimersByTimeAsync(1000);
  expect(backend.fetchMock).toHaveBeenCalledTimes(1);
  expect(backend.requests[0].url).toContain("handle=new");
  expect(Object.keys(backend.store.getState().userSubmissions.submissionsByHandle)).toEqual(["new"]);
});

// Generated by Codex and not thoroughly checked for correctness.
test("late responses cannot replace the latest user's results", async () => {
  let resolveOld!: (value: Response) => void;
  backend.fetchMock.mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve; })).mockResolvedValueOnce(Response.json({ status: "OK", result: [] }));
  backend.store.dispatch(requestUserSubmissions(["old"]));
  backend.store.dispatch(requestUserSubmissions(["new"]));
  await vi.advanceTimersByTimeAsync(0);
  resolveOld(Response.json({ status: "OK", result: [submission] }));
  await vi.advanceTimersByTimeAsync(0);
  expect(Object.keys(backend.store.getState().userSubmissions.submissionsByHandle)).toEqual(["new"]);
  expect(backend.store.getState().userSubmissions.loading).toBe(0);
});

// Generated by Codex and not thoroughly checked for correctness.
test("network failure finishes loading and the next refresh recovers", async () => {
  backend.fetchMock.mockRejectedValueOnce(new Error("Offline"));
  backend.store.dispatch(requestUserSubmissions(["tourist"]));
  await vi.advanceTimersByTimeAsync(0);
  expect(backend.store.getState().userSubmissions.loading).toBe(0);
  expect(backend.store.getState().userSubmissions.error).toContain("tourist");
  backend.respond({ status: "OK", result: [submission, { ...submission, contestId: undefined }, { ...submission, verdict: undefined }] });
  backend.store.dispatch(requestUserSubmissions(["tourist"]));
  await vi.advanceTimersByTimeAsync(0);
  expect(backend.store.getState().userSubmissions.error).toBeUndefined();
  expect(backend.store.getState().userSubmissions.submissionsByHandle.tourist.submissions).toHaveLength(1);
});

// Generated by Codex and not thoroughly checked for correctness.
test("reducers ignore repeated/stale responses and removed handles cannot be resurrected", () => {
  const action = requestUserSubmissions(["tourist", "other"], true); backend.store.dispatch(action);
  const payload = { handle: "tourist", requestId: action.payload.requestId, submissions: [submission] };
  backend.store.dispatch(addUserSubmissions(payload)); backend.store.dispatch(addUserSubmissions(payload));
  expect(backend.store.getState().userSubmissions.loading).toBe(1);
  backend.store.dispatch(errorFetchingUserSubmissions({ handle: "other", requestId: "old", error: "Stale" }));
  expect(backend.store.getState().userSubmissions.error).toBeUndefined();
  backend.store.dispatch(removeHandle({ handle: "other" }));
  backend.store.dispatch(addUserSubmissions({ ...payload, handle: "other" }));
  expect(backend.store.getState().userSubmissions.loading).toBe(0);
  expect(backend.store.getState().userSubmissions.submissionsByHandle.other).toBeUndefined();
  backend.store.dispatch(removeAllHandle());
  expect(backend.store.getState().userSubmissions.submissionsByHandle).toEqual({});
});
