import { setupBackendMock, codeforcesApi } from "../support/backendMocks";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, afterEach, expect, test, vi } from "vitest";
import { MemoryRouter } from "react-router";
import HomePage from "../../src/components/home/HomePage";
import { addHandle } from "../../src/data/reducers/userSlice";
import { requestUserSubmissions, addUserSubmissions, errorFetchingUserSubmissions } from "../../src/data/reducers/userSubmissionsSlice";
import Problem from "../../src/types/CF/Problem";
import { Verdict } from "../../src/types/CF/Submission";
import { createSubmission } from "../support/submissionFixtures";
import { StorageService } from "../../src/util/StorageService";

let backend: ReturnType<typeof setupBackendMock>;
beforeEach(async () => {
  localStorage.clear(); vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 9, 4, 12));
  backend = setupBackendMock();
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getProblems", undefined, []));
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getContest", undefined, []));
  await backend.store.dispatch(codeforcesApi.util.upsertQueryData("getSharedProblems", undefined, []));
});
afterEach(async () => { cleanup(); backend.store.dispatch(requestUserSubmissions([])); await vi.advanceTimersByTimeAsync(0); backend.dispose(); vi.restoreAllMocks(); vi.useRealTimers(); localStorage.clear(); });
function page() { return render(<MemoryRouter><HomePage /></MemoryRouter>, { wrapper: backend.wrapper }); }
function prepare() {
  backend.store.dispatch(addHandle({ id: 1, handle: "tourist" }));
  const action = requestUserSubmissions(["tourist"], true); backend.store.dispatch(action); return action.payload.requestId;
}

// Generated by Codex and not thoroughly checked for correctness.
test("Home without handles renders guidance and adds/removes a handle through real Redux", () => {
  page(); expect(screen.getByRole("status").textContent).toContain("Add a handle");
  fireEvent.click(screen.getByRole("button", { name: "Add Codeforces handle" }));
  const input = screen.getByRole("textbox", { name: "Add Codeforces handle" });
  fireEvent.change(input, { target: { value: " tourist " } }); fireEvent.submit(input.closest("form")!);
  expect(screen.getByText("@tourist")).toBeDefined();
  expect(backend.store.getState().userList.handles).toEqual(["tourist"]);
  fireEvent.click(screen.getByRole("button", { name: "Remove @tourist" }));
  expect(screen.getByRole("status").textContent).toContain("Add a handle");
});

// Generated by Codex and not thoroughly checked for correctness.
test("Home loading transitions to an empty-history message after successful synchronization", () => {
  const requestId = prepare(); page();
  expect(screen.getByRole("status").textContent).toContain("Loading submissions for @tourist");
  act(() => { backend.store.dispatch(addUserSubmissions({ handle: "tourist", requestId, submissions: [] })); });
  expect(screen.getByRole("status").textContent).toContain("No submissions found for @tourist");
});

// Generated by Codex and not thoroughly checked for correctness.
test("Home exposes failed synchronization feedback as inert text", () => {
  const requestId = prepare(); page();
  act(() => { backend.store.dispatch(errorFetchingUserSubmissions({ handle: "tourist", requestId, error: '<img src=x onerror="alert(1)">' })); });
  expect(screen.getByRole("alert").textContent).toContain("<img");
  expect(document.querySelector("img[src=x]")).toBeNull();
});

// Generated by Codex and not thoroughly checked for correctness.
test("Home uses raw history for populated snapshots and persists period changes", () => {
  const requestId = prepare();
  const submission = createSubmission(1, new Problem(100, "A", "Alpha", "PROGRAMMING", 800, []), Verdict.OK, new Date(2026, 9, 3, 12).getTime() / 1000);
  backend.store.dispatch(addUserSubmissions({ handle: "tourist", requestId, submissions: [JSON.parse(JSON.stringify(submission))] }));
  page(); expect(screen.queryByRole("status")).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Custom" }));
  expect(localStorage.getItem(StorageService.Keys.Home.SnapshotPeriod)).toBe('"Custom"');
});
