// Generated by Codex.
// Disclaimer: Tests in this file have not been thoroughly checked for correctness.
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter, useLocation } from "react-router";
import { afterEach, expect, test } from "vitest";
import QuickActions from "../../src/components/home/QuickActions";
import { Verdict } from "../../src/types/CF/Submission";
import { SearchKeys } from "../../src/util/constants";
import { Path } from "../../src/util/route/path";

afterEach(cleanup);

function LocationProbe() {
  const { pathname, search } = useLocation();
  return <output data-testid="location">{pathname}{search}</output>;
}

test("attempted problems use URL-only filters", () => {
  render(
    <MemoryRouter>
      <QuickActions />
      <LocationProbe />
    </MemoryRouter>,
  );

  fireEvent.click(screen.getByRole("button", { name: /Attempted problems/i }));

  const location = screen.getByTestId("location").textContent ?? "";
  const [path, search] = location.split("?");
  const params = new URLSearchParams(search);
  expect(path).toBe(Path.PROBLEMS);
  expect(params.get(SearchKeys.Status)).toBe(Verdict.ATTEMPTED);
  expect(params.get(SearchKeys.UseFilterStorage)).toBe("false");
});
